# Part 2: lessons 6-25
from _lesson_data_part1 import LESSON_CONTENT

LESSON_CONTENT.update({
    6: {
        "id": 6,
        "outcome": "You will read raw price movement without indicators, interpret candle sequences at key levels, and distinguish impulsive moves from corrective drift.",
        "intro": "Price action is the language of the market written directly on the chart. Every wick, gap, and pause tells you who acted and how aggressively.",
        "core": "Price action analysis studies what price itself does at structure — support, resistance, trendlines, and prior swings — without lagging formulas. You focus on speed, range expansion, rejection wicks, and acceptance beyond levels.\n\nImpulsive legs move fast with large bodies and shallow pullbacks; they signal initiative from one side. Corrective legs move slower with overlapping candles and longer wicks; they often retrace prior moves without reversing trend.\n\nAt support in an uptrend, bullish rejection candles (long lower wicks, strong closes) suggest buyers defending. At resistance, bearish rejection hints sellers remain active. Context determines whether the same candle is reversal or continuation.\n\nAvoid pattern hunting without location. A pin bar at random mid-range differs from an identical shape at a tested daily level after a liquidity sweep.",
        "chart_title": "Price action at key levels",
        "chart_caption": "Watch how candles behave as price approaches support or resistance — speed, wick length, and close location reveal control.",
        "example": "S&P 500 futures approach 5,200 resistance after a five-day rally. The first touch prints a long upper wick and red close — sellers active. Price pulls back to 5,165 support with smaller red bodies, then prints a bullish engulfing off support. You enter long at 5,178 with stop below 5,158, targeting 5,220, because rejection at resistance was followed by buyer defense at support.",
        "tip": "Describe the last three candles in plain English before placing a trade — if you cannot, you do not yet have a read.",
        "bullets": [
            "Price action reads speed, range, and rejection without indicators",
            "Impulsive legs show initiative; corrective legs retrace without reversing",
            "Location at structure matters more than candle pattern names",
            "Acceptance beyond a level means closes hold past the zone",
            "Always define invalidation before entry based on structure",
        ],
        "takeaway": "Indicators summarize price; price action is the source. Learn to read the chart naked first.",
    },
    7: {
        "id": 7,
        "outcome": "You will recognize valid breakouts from noise, understand volume and acceptance criteria, and plan entries when price escapes a defined range.",
        "intro": "A breakout occurs when price escapes a boundary where it previously balanced — and stays there. Not every poke above resistance qualifies.",
        "core": "Breakouts happen when one side absorbs the other's liquidity at a boundary — range high, triangle apex, or prior swing level. Genuine breaks show momentum: expanded range candles, follow-through closes, and often increased participation.\n\nWeak breaks print long wicks back inside the range — a sign of trapping breakout buyers or sellers. Acceptance means price closes beyond the level and subsequent pullbacks hold outside the old boundary.\n\nBreakout traders pay for immediacy; they risk false breaks in exchange for catching the start of a new leg. Retest entries after acceptance often improve reward-to-risk but may miss fast moves.\n\nTime spent in a base often correlates with energy released on break — long consolidations can produce larger expansions, though not always in the expected direction.",
        "chart_title": "Breakout from consolidation",
        "chart_caption": "Price compresses inside a range, then expands through resistance with a strong close. Retests of the broken level often act as entry zones.",
        "example": "Bitcoin consolidates between $62,000 and $64,500 for ten days. A 4-hour candle closes at $65,100 with range 1.8× the average of the prior week. You enter on retest hold above $64,500 with stop below $63,800, targeting $68,000. A wick-only spike to $65,400 that closes back at $64,200 would be a warning to stand down.",
        "tip": "Require a close beyond the level on your decision timeframe — intrabar pokes trap impatient entries.",
        "bullets": [
            "True breakouts show momentum and acceptance beyond the boundary",
            "Wicks back inside the range warn of false breaks",
            "Retests of broken levels can offer safer entries",
            "Longer consolidations can fuel larger expansions",
            "Define invalidation inside the old range before entering",
        ],
        "takeaway": "Breakouts reward patience at the close, not speed at the wick. Wait for the market to prove it is leaving the range.",
    },
    8: {
        "id": 8,
        "outcome": "You will identify healthy pullbacks within trends, differentiate them from reversals, and time entries when corrective price returns toward value.",
        "intro": "Trends do not move in straight lines. Pullbacks are the market catching its breath — and often the best place to join the dominant side.",
        "core": "A pullback is a temporary move against the prevailing trend — a dip in an uptrend or rally in a downtrend. Healthy pullbacks retrace a portion of the prior impulse (often 38–62% in strong trends) without breaking structure.\n\nIn uptrends, watch for decreasing sell volume, smaller bearish bodies, and support holding at prior swing lows or trendlines. In downtrends, weak bounces into resistance offer short entries.\n\nConfusing pullbacks with reversals destroys accounts. A reversal breaks key structure — lower low in an uptrend — while a pullback respects it. Until structure breaks, assume trend continuation is the higher-probability path.\n\nEntering mid-impulse chases price; entering on pullbacks aligns with better stop placement and reward-to-risk, though you may miss trades that never retrace deeply.",
        "chart_title": "Pullback in an uptrend",
        "chart_caption": "After an impulsive rally, price retraces toward support while higher lows remain intact. This is corrective, not necessarily a reversal.",
        "example": "Gold trends from $2,320 to $2,380 on the daily chart, then pulls back to $2,355 — the prior breakout zone. The 4-hour chart shows shrinking red candles and a hammer at $2,354. You enter long at $2,362 with stop below $2,348, targeting a new high above $2,385, treating the move as pullback until a daily close below $2,340.",
        "tip": "In strong trends, shallow pullbacks are normal — do not insist on deep retracements and miss the move.",
        "bullets": [
            "Pullbacks move against trend temporarily without breaking structure",
            "Healthy pullbacks often retrace 38–62% of the prior impulse",
            "Shrinking counter-trend candles suggest weakening opposition",
            "Structure breaks distinguish reversals from pullbacks",
            "Entries on pullbacks typically offer tighter stops than breakouts",
        ],
        "takeaway": "Buy dips in uptrends and sell rips in downtrends — until structure tells you the trend is done.",
    },
    9: {
        "id": 9,
        "outcome": "You will spot false breakouts and bull/bear traps, understand why they occur, and protect capital when price fakes out of a range.",
        "intro": "False breakouts look real until they aren't. They sweep liquidity above highs or below lows, then snap back — punishing traders who chased the break.",
        "core": "A false breakout pierces a key level but fails to achieve acceptance — price returns inside the prior range and often accelerates in the opposite direction. These moves frequently target stops clustered beyond obvious highs and lows.\n\nSigns include long wicks beyond the level, immediate rejection closes, low follow-through volume, and rapid re-entry to the range. News spikes and session open volatility produce many false breaks.\n\nSmart money concepts aside, the mechanics are simple: thin liquidity beyond a level allows a quick push, triggering breakout orders, then larger players fade the move.\n\nTrading false breaks means waiting for rejection evidence — close back inside the range — then entering toward the range center or opposite boundary with stop beyond the sweep wick.",
        "chart_title": "False breakout trap",
        "chart_caption": "Price spikes above resistance with a long upper wick, then closes back below. Breakout buyers are trapped as price reverses toward range support.",
        "example": "EUR/USD ranges between 1.0850 and 1.0920. Price spikes to 1.0935 during London open, then a 1-hour candle closes at 1.0910. You short at 1.0905 after rejection confirmation, stop above 1.0940, target 1.0860 — fading the failed upside break rather than buying the initial spike.",
        "tip": "If your breakout entry gets stopped and price immediately reverses through the range, study it — you may have been liquidity for a trap.",
        "bullets": [
            "False breakouts pierce levels but fail to hold outside the range",
            "Long wicks and closes back inside are classic warning signs",
            "Stops beyond obvious levels are often targeted deliberately",
            "Wait for rejection confirmation before fading a false break",
            "High-volatility opens produce more traps — reduce size or wait",
        ],
        "takeaway": "Not every level break is a breakout. Sometimes it is a hunt for stops — learn to tell the difference.",
    },
    10: {
        "id": 10,
        "outcome": "You will map swing highs and lows, read bullish and bearish structure, and recognize when market character shifts from trend to range or reversal.",
        "intro": "Price structure is the skeleton of the chart — the sequence of peaks and troughs that reveals whether bulls or bears lead.",
        "core": "Market structure organizes price into swings. In bullish structure, each rally peak exceeds the last and each dip holds above the prior trough. Bearish structure shows the opposite. When progression stalls, the market transitions toward balance or reversal.\n\nBreak of structure (BOS) occurs when price surpasses a prior swing in the trend direction — confirming continuation. Change of character (ChoCH) appears when counter-trend swings begin breaking prior pivots — an early reversal warning.\n\nStructure is fractal: swings exist within swings on every timeframe. Aligning higher-timeframe bullish structure with lower-timeframe long entries improves odds; fighting higher-timeframe structure reduces them.\n\nMark structure mechanically at first — label HH, HL, LH, LL — until reading swings becomes automatic during live sessions.",
        "chart_title": "Market structure swings",
        "chart_caption": "Swing highs and lows connect into a readable map. Breaks of prior swings signal continuation or potential character change.",
        "example": "On Tesla's daily chart, price makes HL at $240, HH at $265, HL at $252, HH at $278. A drop below $252 breaks the last higher low — structure shifts from bullish to neutral/bearish. You stop hunting long pullbacks until a new HL forms above $252 or accept short-bias setups on rallies toward $265 resistance.",
        "tip": "Update your last swing labels after every session close — stale structure maps cause stale decisions.",
        "bullets": [
            "Bullish structure: higher highs and higher lows",
            "Bearish structure: lower highs and lower lows",
            "Break of structure confirms trend continuation on your timeframe",
            "Breaking counter-trend pivots warns of character change",
            "Align entries with higher-timeframe structure when possible",
        ],
        "takeaway": "Structure tells you who leads. Trade with it until the swing map proves the leadership changed.",
    },
    11: {
        "id": 11,
        "outcome": "You will define risk per trade, set maximum loss limits, and understand why survival precedes profitability in trading.",
        "intro": "Risk management is not the boring part of trading — it is the part that keeps you in the game after a bad week.",
        "core": "Risk management defines how much capital you expose to loss on each decision. Without it, one oversized bet can erase months of progress. Professionals think in R — units of risk — not dollars won on lucky trades.\n\nCore rules include risking a small fixed percentage per trade (often 0.5–2%), using stop losses at logical invalidation points, and capping daily or weekly loss limits that halt trading when hit.\n\nRisk management does not reduce edge — it ensures edge can compound over enough trials. Even strong strategies produce losing streaks; position sizing determines whether those streaks are manageable.\n\nNever increase size to 'make back' losses. That is risk destruction, not management. Size should reflect current equity and plan compliance, not emotional state.",
        "chart_title": "Risk versus reward framework",
        "chart_caption": "Each trade maps entry, stop, and target. Risk is the distance to stop; reward is the distance to target. Visualizing both prevents impulsive entries.",
        "example": "Your account is $25,000. You risk 1% ($250) per trade. On a long from $150.00 with stop at $147.50, you buy 100 shares because $2.50 × 100 = $250 risk. Target at $157.50 offers 3R ($750). One loss does not threaten the account; consistent 2–3R wins compound over time.",
        "tip": "Calculate position size before you click buy — if you decide size after entry, emotion is driving risk.",
        "bullets": [
            "Risk a fixed small percentage of equity per trade",
            "Define stop loss at logical invalidation, not arbitrary distance",
            "Daily and weekly loss caps prevent spiral sessions",
            "Think in R-multiples to normalize outcomes across setups",
            "Never increase size to recover losses — that destroys edge",
        ],
        "takeaway": "You cannot control whether the next trade wins. You can control how much damage a loss does — that is risk management.",
    },
    12: {
        "id": 12,
        "outcome": "You will calculate position size from account equity, stop distance, and risk percentage — ensuring every trade risks a deliberate amount.",
        "intro": "Position sizing translates your risk plan into shares, contracts, or lots. Get it wrong and even good setups can bankrupt you.",
        "core": "Position size = (Account × Risk%) / (Entry − Stop) for longs, adjusted for instrument tick value on futures and forex lots. The formula links dollars at risk to price distance — wider stops require smaller size for the same dollar risk.\n\nMany traders pick round lot sizes (100 shares, 1 BTC) without calculation. That means risk fluctuates wildly trade to trade, making performance impossible to evaluate.\n\nVolatility affects sizing: identical percentage stops on calm and explosive days risk different outcomes. Some traders reduce size when average true range expands.\n\nAlways round down on size when the math lands between increments — slightly less risk beats accidentally exceeding your cap.",
        "chart_title": "Position sizing math",
        "chart_caption": "Given entry, stop, and account risk percentage, position size determines how much you lose if stopped out. Wider stops mean smaller size.",
        "example": "Account $40,000, risk 0.75% = $300. Short ES futures entry 5,300, stop 5,312 (12 points). ES point value $50 → $600 per point at 1 contract. 12 × $50 = $600 risk per contract — too much. You trade 0 contracts at full size or use micro contracts: 1 MES risks $60/point → 12 × $60 = $720 still high; size to 0 MES or tighten stop to 6 points for ~$300.",
        "tip": "Save a position size spreadsheet or use a calculator every time — mental math under pressure causes oversizing.",
        "bullets": [
            "Size = dollar risk divided by stop distance (adjusted for tick value)",
            "Fixed percentage risk keeps loss impact consistent",
            "Wider stops require smaller positions for the same risk",
            "Round down when between valid lot increments",
            "Never size based on conviction — size based on math",
        ],
        "takeaway": "Correct position sizing turns a strategy from a gamble into a repeatable process with controlled downside.",
    },
    13: {
        "id": 13,
        "outcome": "You will place stops at logical invalidation points based on structure, avoid noise stops that get hunted, and accept when a stop means the thesis was wrong.",
        "intro": "A stop loss is your trade's admission price for being wrong. Place it where your idea is invalidated — not where it merely hurts.",
        "core": "Logical stops sit beyond structure: below swing low for longs, above swing high for shorts, outside the range for breakouts. If price reaches your stop, the market rejected your scenario — exit and reassess.\n\nTight stops reduce dollar risk per share but increase stop-out frequency from normal noise. Wide stops survive noise but require smaller size. Balance stop placement with position sizing, not one alone.\n\nAvoid arbitrary stops (always $1 away) or percentage-only stops ignoring chart levels. Also avoid stops inside obvious liquidity pools where wicks commonly sweep before the real move.\n\nMoving stops farther from entry to avoid loss is denial, not management. Valid adjustments trail in profit or move to breakeven after defined progress — never widen into loss.",
        "chart_title": "Stop placement beyond structure",
        "chart_caption": "Place stops where the trade idea fails — below support for longs, above resistance for shorts — not at convenient but meaningless distances.",
        "example": "You go long NVIDIA at $875.00 on pullback to prior breakout near $872.00. Logical stop below the swing low at $868.50 — if price closes below, the pullback failed. A stop at $873.50 saves $1.50 per share but gets tagged by routine noise before rally to $892.00.",
        "tip": "Write your invalidation level before entry — if you cannot defend it on the chart, the trade is not ready.",
        "bullets": [
            "Stops belong at structural invalidation, not comfort zones",
            "Tighter stops need smaller size to maintain fixed risk",
            "Obvious stop clusters get swept — add minimal buffer, not huge distance",
            "Never widen a stop to avoid taking a loss",
            "A stopped trade is information, not failure",
        ],
        "takeaway": "Honor your stop. It is the line between a small planned loss and an unplanned disaster.",
    },
    14: {
        "id": 14,
        "outcome": "You will measure risk-to-reward before entering, filter low-quality setups, and understand how R-multiples drive long-term expectancy.",
        "intro": "Risk-to-reward ratio compares what you stand to lose against what you aim to gain. It is the arithmetic backbone of profitable trading.",
        "core": "If you risk $100 to make $300, your reward-to-risk is 3:1 — often written as 3R if you normalize risk to one unit. You can lose on more than half your trades and still profit if average winners exceed average losers.\n\nMinimum acceptable R depends on win rate. A 40% win rate strategy needs average winners above 1.5R to break even after costs. Many professionals target 2R+ on swing trades and accept lower R on high win-rate scalps — but the math must close.\n\nDo not take trades where target is arbitrary and stop is structural — that produces negative expectancy even with decent directional reads. Map both before entry.\n\nPartial exits change effective R. Scaling out at 1R and trailing the rest can smooth equity curves but requires tracking blended outcomes in your journal.",
        "chart_title": "Risk-reward mapping",
        "chart_caption": "Visualize entry, stop, and target before clicking. Trades with poor R need exceptional win rates — most traders overestimate theirs.",
        "example": "Short GBP/USD at 1.2750, stop 1.2785 (35 pips), target 1.2660 (90 pips) → ~2.6:1 R. Risk $350 on a standard lot → target $900. Even at 45% win rate over 100 trades, positive expectancy is achievable if execution matches plan.",
        "tip": "If the only way to justify a trade is 'it might run,' the R is probably too poor — pass.",
        "bullets": [
            "R-multiple = profit or loss divided by initial risk",
            "Higher reward-to-risk compensates for lower win rates",
            "Define target and stop before entry — not after",
            "Transaction costs reduce effective R — include them",
            "Track average R of winners and losers separately in your journal",
        ],
        "takeaway": "Edge is not picking direction alone — it is consistently taking trades where payoff justifies probability.",
    },
    15: {
        "id": 15,
        "outcome": "You will understand drawdowns, set recovery rules, reduce size during equity declines, and protect psychology when curves dip.",
        "intro": "Drawdown is the valley between equity peaks. Every trader walks through them — survivors adjust size and process; others double down and blow up.",
        "core": "Drawdown measures peak-to-trough decline in account equity — e.g., falling from $50,000 to $42,000 is a 16% drawdown. Even profitable systems spend significant time below prior highs.\n\nDeep drawdowns compound recovery difficulty: a 50% loss requires 100% gain to break even. Prevention through position sizing beats heroic recovery trades.\n\nRules during drawdown: reduce risk per trade (halve size at 10% DD, pause at 15%), return to sim or paper until process compliance restores, and ban 'make it back' trades.\n\nTrack maximum drawdown in backtests and live trading. If live DD exceeds backtest expectations, something changed — market regime, execution, or discipline.",
        "chart_title": "Equity curve drawdown",
        "chart_caption": "Equity rises over time but dips below prior peaks. Managing depth and duration of drawdowns determines whether you survive to compound.",
        "example": "You peak at $60,000, then lose 8 of 12 trades during a choppy month, dropping to $54,000 (10% DD). Plan says halve risk from 1% to 0.5% until new equity high. At 0.5%, you rebuild without needing heroic 5R trades. A peer keeps 1% risk, hits 20% DD, and revenge-trades into 35% DD.",
        "tip": "Predefine drawdown tiers and responses while calm — during losses, willpower is unreliable.",
        "bullets": [
            "Drawdown = decline from equity peak to trough",
            "Large losses require disproportionate gains to recover",
            "Reduce size or pause trading as drawdown deepens",
            "Compare live drawdown to backtest expectations",
            "Recovery comes from process, not oversized bets",
        ],
        "takeaway": "Protect the downside of your equity curve as fiercely as you chase the upside — compounding requires staying in the game.",
    },
    16: {
        "id": 16,
        "outcome": "You will build trading discipline through rules, pre-trade routines, and accountability systems that override impulsive decisions.",
        "intro": "Discipline is doing what your plan says when fear and greed scream otherwise. It is a skill built by repetition, not motivation.",
        "core": "Discipline means executing your defined process regardless of recent results. It includes taking valid setups after losses, skipping marginal trades after wins, and stopping when daily limits hit.\n\nRules must be specific: 'Only trade A+ setups with 2R minimum' beats 'be disciplined.' Vague intentions fail under stress.\n\nEnvironment supports discipline — same desk setup, written checklist, alarms for session end, phone away during execution window. Reduce friction for good behavior; add friction for impulsive clicks.\n\nDiscipline is not perfection. You will break rules occasionally. Track violations in your journal and analyze triggers — time of day, market conditions, emotional state — to patch leaks systematically.",
        "chart_title": "Discipline workflow",
        "chart_caption": "A repeatable pre-trade and post-trade routine reduces impulsive decisions. Structure protects you when emotions run hot.",
        "example": "Your plan allows two trades per London session. After one loss, you spot a B-grade setup. Discipline says pass. You watch it work without you — frustrating but irrelevant. Next day, a valid A-setup appears; you take it clean because capital and mind were preserved.",
        "tip": "Use a printed checklist and physically check boxes — small rituals increase follow-through under pressure.",
        "bullets": [
            "Discipline is rule-following when emotions oppose",
            "Specific rules outperform vague intentions",
            "Environment design reduces impulsive trading",
            "Log rule breaks to find patterns and fix leaks",
            "Consistency of process matters more than any single trade",
        ],
        "takeaway": "Motivation fades; systems persist. Build rules and routines that execute even on your worst days.",
    },
    17: {
        "id": 17,
        "outcome": "You will recognize fear and greed in your trading behavior, understand their market impact, and apply techniques to stay balanced.",
        "intro": "Fear and greed move markets — and your cursor. Every blown account story includes both emotions overriding a plan.",
        "core": "Fear manifests as hesitation on valid entries, early exits on winners, and freezing after losses. Greed manifests as oversizing, chasing extended moves, and holding losers hoping for recovery.\n\nMarkets exploit crowd psychology at extremes: euphoric breakouts attract late buyers before reversal; panic selloffs shake out weak hands before bounce. Recognizing crowd emotion helps you avoid being the crowd.\n\nCountermeasures include fixed rules (automatic stops/targets), pre-written trade plans, breathing breaks after losses, and capping daily profit targets to prevent overtrading from euphoria.\n\nNeither emotion disappears — professionals acknowledge them and return to process. 'I feel FOMO' is data; acting on it without checklist approval is the mistake.",
        "chart_title": "Emotional extremes in price",
        "chart_caption": "Parabolic moves and capitulation selloffs often mark emotional extremes. Calm process outlasts reactive chasing.",
        "example": "After three winners, you feel invincible and double size on a mediocre breakout. It fails for -2R while normal size would have been -1R. Greed turned a standard loss into a dent. Next session you cap size at plan maximum regardless of streak.",
        "tip": "Name the emotion out loud when it spikes — labeling reduces amygdala hijack and buys seconds to consult your plan.",
        "bullets": [
            "Fear causes missed entries, early exits, and paralysis",
            "Greed causes oversizing, chasing, and holding losers",
            "Crowd extremes often appear at market turning points",
            "Automate exits where possible to reduce emotional interference",
            "Acknowledge emotion without granting it veto power over rules",
        ],
        "takeaway": "You will always feel fear and greed. Edge comes from acting on your plan while they run in the background.",
    },
    18: {
        "id": 18,
        "outcome": "You will cultivate patience to wait for A-grade setups, avoid forcing trades in chop, and understand that inactivity is often the optimal position.",
        "intro": "The market presents endless opportunities — and endless traps. Patience is the filter that separates professionals from participants.",
        "core": "Patience means waiting until price, structure, and your criteria align — not clicking because boredom or FOMO demands action. Most account damage comes from overtrading mediocre setups, not missing great ones.\n\nProfessional traders often report trading fewer times with higher quality. A month with twelve A-setups beats sixty C-setups with similar screen time.\n\nPatience pairs with preparation: while waiting, mark levels, review higher timeframes, and update watchlists. Active patience differs from passive scrolling.\n\nImpatience after losses pushes revenge entries. Impatience after wins pushes overconfidence trades. Both violate timing discipline.",
        "chart_title": "Waiting for the setup",
        "chart_caption": "Price spends most time consolidating. Patience preserves capital for the minority of moments when edge is clearest.",
        "example": "Your strategy needs pullback to 20-day EMA in uptrend with bullish rejection. Stock runs eight days without touching the EMA. You wait. On day nine, price tags the EMA at $142.30 and prints a hammer — entry with stop at $140.80. Forced entries days 3–7 would have been stopped in chop.",
        "tip": "Schedule 'no-trade' alerts when price is mid-range — permission to wait reduces guilt about inactivity.",
        "bullets": [
            "Patience filters B and C setups that erode edge",
            "Most chart time is noise — edge clusters at key moments",
            "Use waiting periods for preparation, not random clicking",
            "Losses and wins both trigger impatience — guard against both",
            "Not trading is a position when no edge is present",
        ],
        "takeaway": "Amateurs overtrade; professionals wait. Your P&L often improves when trade count drops.",
    },
    19: {
        "id": 19,
        "outcome": "You will process losses constructively, prevent emotional spirals, and extract learning without damaging self-trust.",
        "intro": "Losses are tuition — but only if you pay attention instead of rage-quitting or revenge trading.",
        "core": "Every trader loses. Expectancy comes from the distribution of outcomes, not any single trade. Treating losses as proof you 'cannot trade' destroys confidence; treating them as data preserves it.\n\nAfter a loss, follow a cooldown: step away, hydrate, review whether the loss was plan-compliant (good loss) or rule-breaking (bad loss). Good losses are acceptable; bad losses require process fixes.\n\nAvoid immediate re-entry to 'get it back.' The market does not owe you redemption on the next candle. Reset on the next valid setup tomorrow.\n\nStreaks of losses happen. Size reduction and session stops are mechanical responses — not judgments on your worth.",
        "chart_title": "Loss as part of the curve",
        "chart_caption": "Even profitable equity curves contain many losing trades. How you respond to losses shapes whether the curve recovers or collapses.",
        "example": "You lose -1R on a valid breakout that failed — stop hit at planned level. Journal tags: plan-compliant, no rule breaks. You stop for the day per rules. Next morning, fresh A-setup appears; you take it normal size. A peer revenge-trades three times that evening for -4R additional.",
        "tip": "Classify every loss as 'good' (followed plan) or 'bad' (broke rules) — only bad losses require behavioral fixes.",
        "bullets": [
            "Losses are inevitable in any probabilistic strategy",
            "Good losses follow the plan; bad losses break rules",
            "Cooldown periods prevent revenge spirals",
            "The market does not owe immediate recovery trades",
            "Reduce size during losing streaks mechanically",
        ],
        "takeaway": "A planned small loss is a successful execution of risk management — not a personal failure.",
    },
    20: {
        "id": 20,
        "outcome": "You will maintain a structured trade journal, capture setup quality and emotions, and use records to improve decisions over months.",
        "intro": "Memory lies; journals don't. The traders who improve fastest review what they actually did — not what they think they did.",
        "core": "A trade journal records entry/exit, setup type, timeframe, risk (R), outcome, screenshots, and emotional state. Without it, you repeat the same mistakes while believing you improved.\n\nTag trades by strategy version, market condition (trend/range), and grade (A/B/C). Over time, patterns emerge: maybe you crush trend pullbacks but bleed in ranges.\n\nWeekly reviews aggregate stats — win rate, average R, rule violations, best/worst hours. Monthly reviews adjust plan filters based on evidence, not one memorable trade.\n\nJournaling is work. Keep fields minimal but consistent — five minutes per trade beats sporadic essays.",
        "chart_title": "Journal review cycle",
        "chart_caption": "Record trades immediately, review weekly, refine monthly. Feedback loops turn experience into edge.",
        "example": "After 40 journaled trades, you notice 70% win rate on London open pullbacks but 30% on New York afternoon breakouts. You drop PM breakouts from plan and focus on AM pullbacks — expectancy jumps without new indicators.",
        "tip": "Screenshot the chart at entry and paste into the journal — future you needs visual context, not memory.",
        "bullets": [
            "Log every trade with setup, R, and rule compliance",
            "Tag market regime and session for pattern discovery",
            "Review weekly aggregates, not individual outcomes alone",
            "Use data to cut strategies that bleed silently",
            "Keep the format simple enough to maintain daily",
        ],
        "takeaway": "If it is not journaled, it did not happen — at least not in a way that improves your trading.",
    },
    21: {
        "id": 21,
        "outcome": "You will define what a trading strategy is, separate it from random clicking, and identify the components every robust strategy must include.",
        "intro": "A strategy is a repeatable set of rules for when to enter, exit, and size — not a gut feeling dressed in indicators.",
        "core": "A trading strategy answers: what market conditions do I trade, what triggers entry, where is invalidation, where is target, and how much do I risk. Without each piece, you have opinions, not a system.\n\nStrategies align with personality and schedule — scalping demands screen time; swing trading suits part-time monitors. Mismatch causes abandonment mid-drawdown.\n\nEdge comes from exploiting a recurring market behavior — trend continuation, mean reversion, volatility expansion — with defined filters that skip low-quality occurrences.\n\nDocument strategies in writing. Vague mental rules mutate under stress. Written rules enable backtesting, journaling tags, and objective review.",
        "chart_title": "Strategy components map",
        "chart_caption": "Every strategy links market filter, entry trigger, stop, target, and sizing into one repeatable flow.",
        "example": "Your written strategy: daily uptrend stocks only, enter on 4H pullback to 20 EMA with bullish rejection, stop below swing low, target 2.5R, risk 1%. Monday's random meme stock spike does not qualify — no filter match, no trade.",
        "tip": "If you cannot explain your strategy on one page, it is not ready for live capital.",
        "bullets": [
            "Strategy = defined conditions + entry + exit + sizing",
            "Must fit your schedule and psychological tolerance",
            "Edge targets a repeatable market behavior",
            "Write rules before live trading to prevent drift",
            "Random trades without filters are entertainment, not strategy",
        ],
        "takeaway": "Trade a written plan or donate to those who do — the market taxes unstructured participation heavily.",
    },
    22: {
        "id": 22,
        "outcome": "You will implement trend-following logic, enter on pullbacks or breakouts in direction of trend, and manage trades until structure breaks.",
        "intro": "Trend following does not predict tops or bottoms — it rides established direction until evidence says the trend ended.",
        "core": "Trend-following strategies assume momentum persists. Entries occur on pullbacks to moving averages or structure in uptrends (long) and downtrends (short), or on breakouts of consolidation in trend direction.\n\nExits use trailing stops, structure breaks, or fixed R targets. Win rate is often moderate — many small losses or breakevens, occasional large winners in strong trends.\n\nTrend following struggles in choppy ranges — whipsaws accumulate. Filters like ADX, higher-timeframe alignment, or minimum trend slope reduce but do not eliminate chop damage.\n\nAccept missing the first 20% and last 20% of moves. Trend systems profit the middle where structure is clearest.",
        "chart_title": "Trend following entries",
        "chart_caption": "In established trends, entries on pullbacks or breakouts align with dominant flow. Exits trigger when structure breaks.",
        "example": "USD/JPY daily uptrend from 148.00 to 152.50. Strategy buys 4H pullbacks to rising 20 EMA near 151.20 with stop below last HL at 150.60. Three attempts in chop produce small losses; fourth catches run to 154.80 — classic trend-following payoff asymmetry.",
        "tip": "Measure trend on a higher timeframe than entry — alignment filters many false signals.",
        "bullets": [
            "Trend following rides existing momentum, not predictions",
            "Entries: pullbacks to value or breakouts with trend",
            "Expect moderate win rate with occasional large winners",
            "Choppy ranges are enemy — use regime filters",
            "You will miss extremes — profit the middle segment",
        ],
        "takeaway": "Do not fight the trend on your timeframe until structure objectively breaks — trend followers win by staying onboard.",
    },
    23: {
        "id": 23,
        "outcome": "You will trade mean reversion setups at range extremes, understand when fading moves works, and know when not to catch falling knives.",
        "intro": "Mean reversion bets that stretched price returns toward average — profitable in ranges, dangerous in runaway trends.",
        "core": "Mean reversion sells strength and buys weakness relative to a mean — moving average, VWAP, or range midpoint. It assumes temporary overextension corrects.\n\nBest in defined ranges with clear boundaries. Worst in strong trends where 'overbought' stays overbought for weeks.\n\nEntries need confirmation — rejection wicks, RSI divergence alone is insufficient without structure. Stops beyond the extreme; targets at mean or opposite range boundary.\n\nCombine with regime filter: only mean revert when higher timeframe is ranging or counter-move is corrective within larger trend.",
        "chart_title": "Mean reversion in a range",
        "chart_caption": "Price oscillates around a mean between support and resistance. Fading extremes toward the middle works until a breakout ends the range.",
        "example": "Oil ranges $78–$82 for two weeks. At $81.90, RSI elevated and upper wick rejection appears. Short at $81.70, stop $82.15, target $79.50 (range mid). Works twice; third attempt fails when price closes above $82.30 — range broke, mean reversion disabled until new range forms.",
        "tip": "Never mean revert without a defined range or clear corrective context — trends punish fade traders.",
        "bullets": [
            "Mean reversion fades overextension toward average",
            "Works best in ranges; fails in strong trends",
            "Require price rejection, not indicator alone",
            "Stop beyond extreme; target mean or opposite boundary",
            "Disable strategy after range breakout acceptance",
        ],
        "takeaway": "Buy cheap and sell rich only when the market is actually ranging — otherwise you are stepping in front of freight trains.",
    },
    24: {
        "id": 24,
        "outcome": "You will design a breakout strategy with filters for consolidation quality, volume confirmation, and retest entries to improve expectancy.",
        "intro": "Breakout strategies monetize transitions from balance to imbalance — but require strict filters to avoid death by false breaks.",
        "core": "Define the base: minimum consolidation duration, decreasing volatility, clear boundary levels. Trigger: close beyond boundary on decision timeframe. Filter: volume expansion, trend alignment, or time-of-day liquidity.\n\nEntry variants: immediate on break (higher miss rate on fakes), retest of broken level (better R, may miss fast moves), or partial size on break plus add on retest.\n\nStop inside the range invalidates breakout thesis. Target measured move (range height projected) or next structure level.\n\nTrack false break rate by instrument — some markets trap more than others; adjust filters accordingly.",
        "chart_title": "Breakout strategy setup",
        "chart_caption": "Consolidation, boundary break with acceptance, optional retest entry. Measured move projects target from range height.",
        "example": "Semiconductor ETF consolidates $220–$228 for 15 sessions. Close at $229.50 on 1.4× average volume. Retest holds $228.20; enter $228.80, stop $226.90, target $236 (range height $8 projected from break). False break filter: no entry if close back below $228 within two bars.",
        "tip": "Backtest your breakout rules on at least 50 historical examples before sizing live — false break rate surprises most traders.",
        "bullets": [
            "Define base quality before trading the break",
            "Acceptance (hold beyond level) filters many fakes",
            "Retest entries improve R but may miss fast moves",
            "Measured move targets use range height projection",
            "Track false break rate per market and adjust filters",
        ],
        "takeaway": "Breakout trading is a filter game — the setup is common; edge lives in which breaks you skip.",
    },
    25: {
        "id": 25,
        "outcome": "You will backtest strategies on historical data, interpret results critically, and avoid curve-fitting that fails live.",
        "intro": "Backtesting lets you pay tuition with time instead of money — if you respect its limits and lie to yourself about neither.",
        "core": "Backtesting applies your written rules to past data to estimate win rate, average R, max drawdown, and profit factor. It validates whether edge might exist — not whether it will continue unchanged.\n\nUse realistic assumptions: include spread, commission, slippage, and avoid lookahead bias (using future data unknowingly). Walk-forward testing reserves out-of-sample periods.\n\nOverfitting optimizes parameters to past noise — 47-period MA because it worked in 2019. Robust edges work across reasonable parameter ranges and multiple years.\n\nBacktest minimum 100+ trades for statistical relevance. One great year means little; five mediocre years with controlled DD means more.",
        "chart_title": "Backtest equity curve",
        "chart_caption": "Historical simulation produces equity curve and drawdown stats. Scrutinize assumptions as closely as results.",
        "example": "You backtest pullback strategy on 200 trades over five years: 48% win rate, avg win 2.3R, avg loss 1R, max DD 14%. Adding slippage 0.1R per trade drops profit factor from 1.6 to 1.4 — still viable. Curve-fit variant with 53% win rate on same data fails out-of-sample 2024 chunk.",
        "tip": "If small parameter changes destroy performance, you fitted noise — simplify the strategy.",
        "bullets": [
            "Backtest written rules on sufficient sample size (100+ trades)",
            "Include costs, slippage, and realistic fill assumptions",
            "Beware lookahead bias and survivorship bias in data",
            "Walk-forward / out-of-sample tests reduce overfitting",
            "Robust strategies tolerate reasonable parameter variation",
        ],
        "takeaway": "Backtesting does not guarantee future profits — it eliminates strategies that never had edge in the first place.",
    },
})
