# Part 3: lessons 26-50
from _lesson_data_part2 import LESSON_CONTENT

LESSON_CONTENT.update({
    26: {
        "id": 26,
        "outcome": "You will distinguish market, limit, and stop order types, choose the right tool for each scenario, and understand how order selection affects fill quality and risk.",
        "intro": "Order types are the controls on your execution — they decide whether you get in immediately, at a price, or only when conditions trigger. Using the wrong type turns a good setup into a bad fill.",
        "core": "Market orders execute immediately at the best available price. You pay for certainty of entry with potential slippage — especially in fast markets or around news. Use them when speed matters more than a few ticks of price improvement.\n\nLimit orders specify the maximum you will pay (buy) or minimum you will accept (sell). They offer price control but no fill guarantee — price may never reach your limit, and you miss the move. Ideal for planned entries at support, resistance retests, or scale-in levels.\n\nStop orders become market orders once price reaches your stop price. Buy stops trigger above current price (breakout entries); sell stops trigger below (stop losses or breakdown shorts). Stop-limit orders add a limit cap after trigger — safer on price but risk no fill in a crash.\n\nProfessional execution matches order type to intent: market for urgent exits on invalidation, limits for patient entries at levels, stops for breakout triggers and protective exits. Never use market orders casually on illiquid symbols where spreads widen violently.",
        "chart_title": "Order types at key levels",
        "chart_caption": "Market orders fill now; limit orders wait at your price; stop orders activate when price reaches a trigger. Each serves a different execution goal.",
        "example": "Apple trades at $192.40. Your plan buys pullback to $191.50 support — you place a buy limit at $191.55 instead of market chasing. Fill occurs at $191.55; stop sell at $190.20 triggers as stop-market if breached. For a breakout above $194.00 resistance, you place buy stop at $194.10 — it triggers only if acceptance confirms, avoiding a wick-only poke to $193.95.",
        "tip": "Before every order, ask: do I need speed, a specific price, or a conditional trigger? That answer picks the order type.",
        "bullets": [
            "Market orders prioritize fill speed over exact price",
            "Limit orders control price but may never execute",
            "Stop orders trigger at a price then behave as market orders",
            "Stop-limit orders cap fill price but may not fill in fast moves",
            "Match order type to setup intent — not habit or convenience",
        ],
        "takeaway": "Order types are not interchangeable. The right choice protects edge; the wrong one taxes it through slippage, missed fills, or late exits.",
    },
    27: {
        "id": 27,
        "outcome": "You will define slippage, recognize when it spikes, and adjust order type, size, and timing to minimize execution cost.",
        "intro": "Slippage is the gap between the price you expected and the price you actually received. It is invisible on the chart but visible on your P&L.",
        "core": "Slippage occurs when your order consumes available liquidity at the best bid/ask and walks the book — or when price moves between click and fill. Market orders during volatility, thin books, and news events produce the worst slippage.\n\nPositive slippage happens occasionally (better fill than expected) but negative slippage dominates costs for active traders. On ES futures, 1–2 ticks is normal in calm conditions; 5–10 ticks during CPI releases is common if you market in.\n\nReduce slippage by trading liquid instruments during peak hours, using limits for entries when urgency is low, splitting large orders, and avoiding market orders in the first minute after major data.\n\nAccount for slippage in backtests — assuming perfect fills at the close inflates expectancy. Adding 0.05–0.15R slippage per trade to simulations often separates viable strategies from fantasy.",
        "chart_title": "Expected vs actual fill",
        "chart_caption": "The distance between your intended entry and actual fill is slippage. It widens when liquidity thins and volatility expands.",
        "example": "You market buy EUR/USD at quoted 1.0872 during NFP release. Fill prints at 1.0879 — 7 pip slippage on a 25 pip stop cuts effective R by nearly 30%. Next month you use a limit at pre-defined level 1.0865 after volatility settles, or reduce size 50% during the release window. Average slippage drops from 4 pips to 1.2 pips per entry.",
        "tip": "Log expected vs actual fill for 20 trades — if slippage consistently exceeds your plan allowance, execution is leaking edge.",
        "bullets": [
            "Slippage = difference between expected and actual fill price",
            "Market orders in fast markets produce the largest slippage",
            "Thin liquidity and news events widen slippage dramatically",
            "Limits and scaled entries reduce cost when speed is not critical",
            "Include realistic slippage assumptions in backtests",
        ],
        "takeaway": "Edge on the chart means little if execution gives it away at the fill. Treat slippage as a line item, not an accident.",
    },
    28: {
        "id": 28,
        "outcome": "You will read liquidity conditions, understand bid-ask spread and depth, and avoid trading when the book cannot absorb your size cleanly.",
        "intro": "Liquidity is how easily you can enter and exit without moving price against yourself. Thin liquidity turns small mistakes into large costs.",
        "core": "Liquidity reflects the volume of resting orders at each price level — depth at the bid and ask. High liquidity means tight spreads and minimal price impact; low liquidity means wide spreads, partial fills, and slippage on modest size.\n\nMajor forex pairs, large-cap stocks, and front-month index futures trade deep during overlapping sessions (London–New York). Mid-cap stocks, altcoins, and off-hours markets often lack depth — charts look clean but fills are expensive.\n\nSpread is the immediate cost of liquidity — the difference between bid and ask. A stock with $0.05 spread on a $0.50 stop distance consumes 10% of risk before the trade moves. Always compare spread to stop distance.\n\nLiquidity also clusters at obvious levels — stops beyond round numbers, prior highs, and option strikes. Sweeps through these pools are often liquidity events, not random noise.",
        "chart_title": "Liquidity and spread",
        "chart_caption": "Deep books show tight bid-ask spreads and stacked orders. Thin books widen spreads and increase slippage on market orders.",
        "example": "You want 500 shares of a small-cap biotech at $12.40. Average daily volume is 200K; spread is $0.08. Your 500-share market buy lifts price to $12.52 — effective entry $0.12 worse than chart. Same setup on liquid ETF XBI with penny spread fills at $12.41. Liquidity choice saved 11 cents per share on identical thesis.",
        "tip": "Check average volume and current spread before sizing — if spread exceeds 5% of your stop distance, reconsider instrument or order type.",
        "bullets": [
            "Liquidity = ease of trading without significant price impact",
            "Tight spreads signal depth; wide spreads signal caution",
            "Peak session overlap usually offers best forex and index liquidity",
            "Compare spread size to stop distance before entering",
            "Obvious levels concentrate stops and resting liquidity",
        ],
        "takeaway": "Trade where the market can absorb you. Illiquid instruments tax edge through spread and slippage before your thesis is even tested.",
    },
    29: {
        "id": 29,
        "outcome": "You will time entries using confirmation, session context, and trigger rules — reducing premature entries and impulsive chasing.",
        "intro": "Seeing the setup and clicking are two different skills. Entry timing separates traders who catch moves from those who feed them.",
        "core": "Early entries anticipate levels before the market confirms — lower win rate but better R when right. Confirmed entries wait for price action evidence — close beyond level, rejection wick, or retest hold — trading some R for higher probability.\n\nSession timing matters: London open and New York open often produce false breaks and volatility spikes; mid-session trends can be cleaner. Avoid entries in the dead zone between major closes unless your strategy specifically targets it.\n\nUse triggers, not hope: 'If 15-min closes above $450, buy retest to $448' beats 'looks like it might go.' Triggers remove real-time debate and align with pre-written plans.\n\nChasing extended moves after you missed the trigger is not late entry — it is a new trade without edge. Pass and wait for the next A-setup rather than paying premium for FOMO.",
        "chart_title": "Entry timing triggers",
        "chart_caption": "Planned triggers at structure — breakout close, retest hold, or rejection candle — filter impulsive clicks from validated entries.",
        "example": "Crude oil bases at $76.80–$77.60. Your plan: enter long on 1H close above $77.60, then buy retest to $77.45. At 10:00, wick spikes to $77.75 but closes $77.52 — no entry. At 14:00, candle closes $77.68; retest dips to $77.48 and holds. Entry $77.55, stop $77.15, target $79.20. The 10:00 chase would have stopped on noise.",
        "tip": "Write your entry trigger in one sentence before the session — if the sentence needs updating every bar, you are not timing, you are guessing.",
        "bullets": [
            "Confirmed entries wait for evidence; early entries anticipate levels",
            "Session opens often produce volatility — adjust size or wait",
            "Written triggers remove impulsive real-time decisions",
            "Missing a trigger is not permission to chase extended price",
            "Retest entries often improve R versus first break chase",
        ],
        "takeaway": "Good analysis with bad timing still loses. Define when you enter before price arrives at your level.",
    },
    30: {
        "id": 30,
        "outcome": "You will manage open trades with scaling, trailing stops, breakeven rules, and time-based exits — protecting profit without strangling winners.",
        "intro": "Entry gets attention; trade management determines whether a correct read becomes meaningful P&L. Amateurs set and forget — or panic adjust.",
        "core": "Trade management begins at entry with planned partials, trail rules, and invalidation updates — not improvised reactions to every tick. Define upfront: take 50% at 1R and trail stop on remainder, or hold full size to structure target.\n\nMoving to breakeven after 1R protects against give-back but increases stop-out rate on trades that would have reached 3R. Test breakeven rules on your journal data — they help some setups, harm others.\n\nTrailing stops follow structure — below last higher low on longs, above last lower high on shorts — not arbitrary moving averages alone. Structure trails respect market behavior; tight arbitrary trails get shaken out.\n\nTime stops exit trades that fail to progress — if price stalls X bars without reaching first target, scratch or reduce. Capital and attention have opportunity cost in dead trades.",
        "chart_title": "Trade management flow",
        "chart_caption": "From entry through partials, breakeven, and trail — management rules should be defined before the trade, not invented under stress.",
        "example": "Long Microsoft at $420.00, stop $415.00 (1R = $5). Plan: sell 50% at $425.00, move stop to $420.00 on rest, trail below 4H swing lows. Price hits $425 — half off, stop breakeven. Price reaches $432; trail sits at $427.50 under last HL. Stopped at $427.50 on pullback — blended exit ~$426.25 vs unmanaged round-trip that gave back to $422.",
        "tip": "Simulate three management variants on past journal trades — full hold, partial plus trail, fixed target — and adopt what your data supports.",
        "bullets": [
            "Define partials, trails, and time stops before entry",
            "Breakeven rules reduce give-back but can cap winners",
            "Trail stops using structure, not arbitrary distance",
            "Time stops free capital from trades going nowhere",
            "Management rules should be consistent and journal-tested",
        ],
        "takeaway": "A winning idea without management plan often becomes a small win or loss. Manage the trade you planned, not the tick on screen.",
    },
    31: {
        "id": 31,
        "outcome": "You will conduct structured post-trade reviews, separate process from outcome, and build a repeatable feedback loop after every session.",
        "intro": "Trade review is where experience becomes skill. Without it, you repeat the same errors while remembering only the highlights.",
        "core": "Post-trade review captures what happened versus what you planned: setup grade, entry trigger compliance, stop placement, management decisions, and emotional state. Outcome alone is misleading — a bad process can win on luck; a good process can lose on variance.\n\nDaily review takes 10–15 minutes: list trades, mark plan-compliant yes/no, note one improvement for tomorrow. Weekly review aggregates patterns — which setups, sessions, and conditions produced positive expectancy.\n\nUse screenshots at entry, management, and exit. Memory reconstructs narratives; images show what you actually faced. Tag each trade with strategy version so rule changes do not blur statistics.\n\nReview is diagnosis, not punishment. The goal is one actionable adjustment per week — cut a bleeding setup, tighten entry filter, or fix a recurring rule break — not exhaustive self-criticism.",
        "chart_title": "Daily review workflow",
        "chart_caption": "Record, tag, and review trades on a fixed schedule. Consistency in review beats intensity once a month.",
        "example": "Friday review of 8 trades: 5 plan-compliant (3 wins, 2 losses, net +1.2R), 3 rule breaks (all losses, -2.8R). Pattern: rule breaks cluster after 15:00 when fatigue hits. Action: hard stop trading at 14:30 next week. Following week rule breaks drop from 3 to 0; net R improves despite similar win rate.",
        "tip": "End each session with two sentences per trade — 'What I did right' and 'What to repeat or fix' — before closing the platform.",
        "bullets": [
            "Review process compliance separately from P&L outcome",
            "Daily short reviews plus weekly aggregation beat sporadic deep dives",
            "Screenshots preserve truth better than memory",
            "Tag trades by setup type and strategy version",
            "One actionable fix per week compounds into real edge",
        ],
        "takeaway": "Review is not optional homework — it is the mechanism that converts trades into improvement. Skip it and you are guessing forever.",
    },
    32: {
        "id": 32,
        "outcome": "You will categorize trading mistakes into execution, analysis, and psychology errors — and target fixes instead of vague 'try harder' resolutions.",
        "intro": "Not all losses are equal. Identifying mistake type tells you whether to fix your chart, your click, or your head.",
        "core": "Analysis mistakes: wrong read of structure, trading against higher timeframe, ignoring regime filter. Fix with study, backtesting, and clearer market classification rules.\n\nExecution mistakes: late entry, wrong order type, stop too tight for noise, moving stop wider, ignoring trigger. Fix with checklists, automation, and pre-written execution scripts.\n\nPsychology mistakes: revenge trading, oversizing after wins, FOMO entries, holding losers past invalidation. Fix with loss limits, cooldown rules, and environment design — not more indicators.\n\nRisk mistakes overlap all three: oversizing, no stop, correlated double exposure. Tag every losing trade with primary mistake category in your journal. After 30 trades, the dominant leak becomes obvious — most traders have one recurring category responsible for majority of damage.",
        "chart_title": "Mistake categories",
        "chart_caption": "Classify errors as analysis, execution, psychology, or risk. Each category demands a different fix — indicators won't cure revenge trading.",
        "example": "You review 20 losses: 8 tagged FOMO/chase (psychology), 5 stop too tight (execution), 4 traded range as trend (analysis), 3 oversize (risk). Biggest bucket is FOMO — you implement mandatory 5-minute delay after missed trigger and drop -6R from next month's FOMO trades to -1R.",
        "tip": "When you take a bad loss, ask 'If I showed this trade to a mentor, what would they flag first?' — that is your mistake category.",
        "bullets": [
            "Analysis errors: wrong read or wrong market regime",
            "Execution errors: fills, stops, and rule drift at the click",
            "Psychology errors: emotion overriding written plan",
            "Risk errors: size and exposure beyond defined limits",
            "Tag losses by category — fix the biggest bucket first",
        ],
        "takeaway": "You cannot fix what you cannot name. Classify mistakes precisely and the solution becomes obvious.",
    },
    33: {
        "id": 33,
        "outcome": "You will calculate expectancy from win rate and average R, identify leaks dragging performance, and prioritize changes that move expectancy most.",
        "intro": "Expectancy is the average amount you make per dollar risked over many trades. Improving it beats chasing win rate alone.",
        "core": "Expectancy formula: (Win% × Avg Win R) − (Loss% × Avg Loss R). Example: 45% win rate, avg win 2.2R, avg loss 1R → (0.45 × 2.2) − (0.55 × 1) = 0.44R per trade — profitable over sample.\n\nImproving expectancy paths: raise win rate on same R (better filters), raise average R on same win rate (better targets/trails), or cut average loss (tighter process, no rule breaks). Cutting losers from 1.2R to 1R via stop discipline often moves expectancy faster than adding indicators.\n\nSegment expectancy by setup, session, and grade. Your A-setups may show +0.8R while B-setups show -0.3R — cutting B's doubles account growth without new strategy invention.\n\nTrack rolling 20-trade expectancy, not lifetime fantasy. Regime shifts can flip a +0.5R system to negative until filters adapt.",
        "chart_title": "Expectancy components",
        "chart_caption": "Win rate and average R combine into expectancy. Small improvements in either compound significantly over hundreds of trades.",
        "example": "Journal shows 52 trades: 42% win rate, avg win 2.5R, avg loss 1.1R → expectancy = (0.42×2.5)−(0.58×1.1) = +0.41R. Removing B-grade setups (18 trades, -0.6R expectancy) leaves 34 A-trades at +0.72R. Same screen time, nearly double edge per trade.",
        "tip": "Calculate expectancy separately for longs and shorts — many traders have edge on one side only and bleed on the other.",
        "bullets": [
            "Expectancy = (Win% × Avg Win R) − (Loss% × Avg Loss R)",
            "Positive expectancy over sample size defines viable strategy",
            "Segment by setup grade to find what to cut or scale",
            "Reducing average loss often beats raising win rate",
            "Monitor rolling expectancy — regimes change",
        ],
        "takeaway": "Stop asking 'Am I winning enough?' Start asking 'Does each trade average positive R over my last 50?' That is expectancy.",
    },
    34: {
        "id": 34,
        "outcome": "You will track consistency metrics — rule compliance, trade count, R distribution — and detect drift before it shows up as drawdown.",
        "intro": "Consistency is doing the same quality process repeatedly. Tracking it reveals drift long before your account statement screams.",
        "core": "Consistency metrics include: plan compliance rate (% trades matching written rules), trades per session vs cap, average R variance week to week, and time-in-market versus planned windows.\n\nA trader with 85% compliance and modest positive expectancy often outperforms 60% compliance with higher raw win rate — rule breaks inject negative tail risk that statistics hide until a bad week.\n\nTrack streaks of compliance: '12 consecutive plan-compliant trades' builds identity; breaking streak triggers mandatory review before next entry. Gamifying compliance beats willpower alone.\n\nDashboard minimum: weekly compliance %, net R, number of rule violations, best/worst setup by R. Red flags: compliance dropping while trade count rises (overtrading), or average loss expanding (stop discipline slipping).",
        "chart_title": "Consistency dashboard",
        "chart_caption": "Track compliance, trade count, and R weekly. Divergence between process metrics and P&L warns of luck masking drift or drift masking skill.",
        "example": "Week 1: 90% compliance, +3.2R. Week 4: 55% compliance, -4.1R despite similar market. Drill-down shows 6 extra PM trades outside plan window — all rule breaks, -5R combined. Reinstating session cap restores Week 5 to 88% compliance and +2.8R.",
        "tip": "Plot compliance rate and net R on the same weekly chart — when they diverge, trust compliance as the leading indicator.",
        "bullets": [
            "Plan compliance rate is the core consistency metric",
            "High compliance stabilizes expectancy over time",
            "Track trade count against session caps to catch overtrading",
            "Weekly dashboards reveal drift before deep drawdowns",
            "Compliance streaks reinforce identity as a rule-follower",
        ],
        "takeaway": "Consistency is a measurable skill. Track it like P&L — because process consistency predicts P&L more reliably than yesterday's win.",
    },
    35: {
        "id": 35,
        "outcome": "You will design a daily and weekly trading routine covering prep, execution, review, and recovery — reducing decision fatigue and impulsive gaps.",
        "intro": "Routine turns trading from reactive clicking into a professional workflow. Structure frees mental bandwidth for the decisions that matter.",
        "core": "Pre-market routine (15–30 min): review economic calendar, mark higher-timeframe levels, update watchlist, read written plan aloud. No orders until routine completes.\n\nExecution window: defined hours matching your edge (e.g., London 08:00–11:00). Phone silent, one monitor for charts, checklist visible. Max trades per session pre-set.\n\nPost-session routine (10 min): log trades, compliance tags, one note for tomorrow. Physical break before personal life blends with market stress.\n\nWeekly routine (30–60 min): aggregate stats, one process adjustment, backtest or study block. Monthly: strategy review, drawdown check, time-off planning. Routines fail when too ambitious — start minimal and add only what you actually sustain.",
        "chart_title": "Daily trading routine",
        "chart_caption": "Prep, execute, review, recover — the same sequence daily builds habit and reduces impulsive gaps in process.",
        "example": "Your routine: 07:30 calendar and levels, 08:00–10:30 execution only, 10:35 journal, 11:00 gym. Before routine, you traded randomly 08:00–16:00 with 14 trades/week and -2R. After routine: 6 trades/week, 82% compliance, +4R over three weeks — not from new setups, from structured hours and caps.",
        "tip": "Anchor routine to fixed clock times, not 'when I feel ready' — feelings are unreliable triggers.",
        "bullets": [
            "Pre-market prep marks levels and filters before live prices tempt you",
            "Define execution windows aligned with your edge sessions",
            "Post-session journal closes the feedback loop same day",
            "Weekly review drives one evidence-based adjustment",
            "Keep routine minimal enough to maintain every trading day",
        ],
        "takeaway": "Amateurs trade when bored; professionals trade when routine says go. Build the schedule and let it carry you through weak days.",
    },
    36: {
        "id": 36,
        "outcome": "You will read complex swing sequences, identify breaks of structure and change of character, and map premium/discount zones within larger swings.",
        "intro": "Advanced market structure goes beyond labeling highs and lows — it reads how swings build, fail, and shift institutional narrative.",
        "core": "On a chosen timeframe, map swing points sequentially. Bullish structure requires higher highs and higher lows; bearish the inverse. When a counter-trend swing breaks the last protective pivot (HL in uptrend, LH in downtrend), character shifts — often called change of character (ChoCH).\n\nBreak of structure (BOS) in trend direction confirms continuation — price exceeds prior swing high in uptrend with acceptance. Failed BOS — wick beyond, close back inside — signals liquidity grab or weakening trend.\n\nPremium and discount divide the current dealing range: above equilibrium (50% of last impulse) is premium — favorable for shorts in bearish context; below is discount — favorable for longs in bullish context. Entries aligned with zone improve R versus chasing extremes.\n\nStructure is fractal — daily ChoCH may be hourly noise. Always declare primary structure timeframe and do not flip bias on every lower-timeframe wiggle.",
        "chart_title": "Advanced structure map",
        "chart_caption": "Swing labels, BOS/ChoCH events, and premium/discount zones combine into a multi-layer structure read on one timeframe.",
        "example": "Ethereum daily: HH at $3,450, HL at $3,180, HH at $3,520, then drop breaks $3,180 — ChoCH bearish. Rally to $3,280 (discount zone of prior range) fails at prior broken HL now resistance. Short at $3,265, stop $3,340, target $3,050 liquidity below $3,120 cluster.",
        "tip": "Print one chart weekly with only swing labels and BOS/ChoCH marks — over-labeling intraday creates bias whipsaw.",
        "bullets": [
            "ChoCH breaks the last protective swing pivot against trend",
            "BOS in trend direction confirms continuation with acceptance",
            "Premium/discount zones filter entry location within range",
            "Failed BOS warns of traps or weakening momentum",
            "Declare one primary structure timeframe and respect it",
        ],
        "takeaway": "Structure is the market's narrative arc. Read the story on your timeframe before trading the sentence on a lower one.",
    },
    37: {
        "id": 37,
        "outcome": "You will stack independent confluence factors — structure, level, session, timeframe — and score setups so only high-alignment trades reach live capital.",
        "intro": "Confluence is when multiple unrelated reasons point to the same trade. One reason is a guess; three aligned reasons is a plan.",
        "core": "Confluence combines factors from different categories: structural (HL at support), technical (200 EMA alignment), temporal (London open), liquidity (sweep of prior low), and higher-timeframe bias (daily uptrend). Same-category stacking (five indicators) is redundancy, not confluence.\n\nScore setups before entry: require minimum 3 of 5 defined factors for A-grade. B-grade gets half size; C-grade is journal-only. This prevents 'looks good' trades with single-factor justification.\n\nMore confluence is not infinite edge — five factors on a low-liquidity stock during holidays still fails. Confluence filters quality within tradable conditions; it does not override regime and liquidity gates.\n\nDocument your confluence checklist in the trading plan. Post-trade, tag which factors were present on winners vs losers — prune factors that do not correlate with outcomes.",
        "chart_title": "Confluence checklist",
        "chart_caption": "Independent factors aligning at one price zone increase probability. Score them before entry to filter marginal trades.",
        "example": "Long GBP/USD at 1.2680: daily uptrend (factor 1), 4H pullback to 1.2675 support (2), London open liquidity sweep to 1.2670 then reclaim (3), 1H bullish engulfing (4), not into major news (5). Five factors — full size. Contrast: afternoon breakout with only momentum, no structure — C-grade, skip.",
        "tip": "If you cannot list three independent reasons in writing, the trade fails confluence — pass regardless of FOMO.",
        "bullets": [
            "Confluence stacks independent factors from different categories",
            "Redundant indicators count as one factor, not three",
            "Minimum confluence score filters A vs B vs C setups",
            "Confluence works inside regime and liquidity filters",
            "Journal which factors actually correlate with your winners",
        ],
        "takeaway": "One reason trades are lottery tickets. Confluence turns discretion into a repeatable scoring system.",
    },
    38: {
        "id": 38,
        "outcome": "You will align analysis across multiple timeframes, define top-down bias, and execute on lower timeframes only when direction agrees.",
        "intro": "Multi-timeframe analysis prevents fighting the tide on your entry chart while the daily chart screams the opposite direction.",
        "core": "Top-down workflow: monthly/weekly for macro bias (optional), daily for primary trend and key levels, 4H/1H for setup development, 15m/5m for precise entry and stop. Each lower timeframe serves the higher — not the reverse.\n\nAlignment rule example: daily bullish, 4H pullback to support, 1H trigger long — three layers agree. Daily bearish but 5m long signal — misalignment; skip or reduce to counter-trend scalp with tight risk only if explicitly allowed.\n\nHigher timeframe levels dominate — a 1H resistance means little if daily supply sits above; a 5m support means little if 4H structure broke bearish. Mark higher levels first; lower setups must respect them.\n\nAvoid analysis paralysis — pick three timeframes maximum for live decisions (e.g., daily, 1H, 15m). More charts create conflicting narratives and hesitation.",
        "chart_title": "Multi-timeframe alignment",
        "chart_caption": "Higher timeframe sets bias and key levels; lower timeframe times entry. Trade lower only when direction aligns with higher.",
        "example": "S&P 500 daily uptrend, holding above 5,180. 4H pulls to 5,195 (prior breakout). 15m prints higher low at 5,198 with bullish close. Long at 5,202, stop 5,188, target 5,245 (4H extension). Same 15m signal at 5,260 into daily resistance with daily overextension — skip despite pretty trigger.",
        "tip": "Write higher-timeframe bias in one word — bull, bear, or range — before opening lower timeframe charts.",
        "bullets": [
            "Top-down: higher timeframe bias guides lower timeframe entries",
            "Three timeframes maximum for live decisions reduces paralysis",
            "Higher timeframe levels override lower timeframe patterns",
            "Misaligned signals across timeframes warrant skip or reduced size",
            "Mark daily/4H levels first; build lower setup inside that map",
        ],
        "takeaway": "The timeframe you execute on is zoom; the timeframe you bias on is context. Never trade zoom without context.",
    },
    39: {
        "id": 39,
        "outcome": "You will map Asian, London, and New York sessions, understand volatility and liquidity by hour, and match strategies to session character.",
        "intro": "The market is not one continuous auction — it is three regional sessions stitched together, each with distinct rhythm and traps.",
        "core": "Asian session (Tokyo/Sydney): often lower volatility in EUR/USD and indices, range development, JPY pairs more active. Useful for marking ranges; breakouts may lack follow-through until London.\n\nLondon open (08:00 GMT): liquidity surge, trend initiation, false breaks common first hour. Many forex and gold strategies target London sweep of Asian high/low then reversal or continuation.\n\nNew York open (13:30 GMT): US data, equity index volatility, overlap with London until ~17:00 GMT — peak liquidity. Afternoon NY often trends or mean-reverts depending on morning direction.\n\nMatch strategy to session: breakout systems often favor London/NY overlap; mean reversion may suit Asian range or late NY fade. Trading your edge at wrong hours injects losses unrelated to setup quality.",
        "chart_title": "Session volatility map",
        "chart_caption": "Volatility and volume swell at London and New York opens. Asian hours often compress range that later sessions expand or break.",
        "example": "Gold ranges $2,340–$2,352 during Asian. London sweeps $2,352 to $2,354, reverses — your plan fades false break above Asian high, short $2,350, stop $2,356, target $2,342. Same fade strategy at 02:00 GMT on thin book produced 3 pip slippage and chop — session mismatch.",
        "tip": "Log session tag on every trade for 30 days — if one session shows negative expectancy, stop trading it before changing strategy.",
        "bullets": [
            "Asian session often builds ranges; JPY pairs most active",
            "London open brings liquidity and frequent initial false breaks",
            "New York overlap with London is peak forex and index liquidity",
            "Strategies should match session volatility character",
            "Journal by session to find when your edge actually lives",
        ],
        "takeaway": "Time of day is a filter, not decoration. The same pattern behaves differently at London open versus Asian midday.",
    },
    40: {
        "id": 40,
        "outcome": "You will document a complete trading plan — markets, setups, risk, sessions, review — as a single reference that governs live decisions.",
        "intro": "A trading plan is the contract between calm-you and stressed-you. If it is not written, it will not survive the first losing streak.",
        "core": "Essential sections: account and risk (size per trade, daily/weekly loss limits), markets and instruments (liquid only, defined list), session windows, setup definitions with entry/stop/target rules, confluence or grade criteria, management rules, and review schedule.\n\nEach setup needs a one-page card: market condition, trigger, invalidation, target logic, example screenshot, and common failure modes. Vague plans ('trade trends') fail under pressure; specific plans ('daily uptrend, 1H pullback to 20 EMA, stop below swing') execute.\n\nInclude disqualifiers: no trade into major news, no revenge after two losses, no new positions after daily loss cap. Disqualifiers protect edge when judgment is impaired.\n\nRevise the plan monthly based on journal evidence — not after one trade. Version the document so journal tags match plan v2 vs v3 when comparing stats.",
        "chart_title": "Trading plan structure",
        "chart_caption": "Risk, markets, setups, sessions, management, and review — one document links every decision to pre-written rules.",
        "example": "Plan v3: $50K account, 0.75% risk, ES and NQ only, trade 09:30–11:30 ET, two setups (opening range break, pullback to VWAP), max 2 trades/day, -2R daily stop. March journal: 41 trades, 78% compliance, +6.8R. April you add disqualifier: no ORB if pre-market range < 0.3% — cuts false breaks, compliance unchanged, +8.2R on fewer trades.",
        "tip": "Keep the plan open on a second monitor during execution — visibility beats memory when adrenaline rises.",
        "bullets": [
            "Plan covers risk, markets, sessions, setups, and review",
            "Each setup needs written trigger, stop, target, and disqualifiers",
            "Disqualifiers protect you when judgment is impaired",
            "Version the plan and tag journal trades to version",
            "Update monthly from data, not from one emotional session",
        ],
        "takeaway": "Your plan is the boss. Deviate and you are gambling with extra steps — follow it and you have a business.",
    },
    41: {
        "id": 41,
        "outcome": "You will define volatility, read it on charts with ATR and range expansion, and adjust size and expectations when conditions change.",
        "intro": "Volatility measures how far and fast price moves. Ignoring it sizes you for calm days and bankrupts you on explosive ones.",
        "core": "Volatility is the magnitude of price fluctuation over time — not direction. High volatility means wider candles, larger daily ranges, and more frequent stop touches; low volatility means compression, often preceding expansion.\n\nAverage True Range (ATR) quantifies typical daily or hourly range. A stock with $2 ATR and $4 stop distance is tight; same stop on $0.80 ATR day is wide relative to noise — adjust stop or size accordingly.\n\nVolatility clusters — calm follows calm, storms follow storms (GARCH effect). After volatility expansion (earnings, FOMC), expect wider swings for days; after long compression, breakouts can accelerate violently.\n\nTraders respond to volatility mechanically: reduce size when ATR exceeds 1.5× your 20-day average, widen targets modestly in expansion, avoid mean reversion when ATR slope rises sharply.",
        "chart_title": "Volatility expansion and compression",
        "chart_caption": "ATR and candle range show when markets are quiet versus explosive. Size and stop logic should adapt to current volatility regime.",
        "example": "NASDAQ ETF QQQ average 14-day ATR $3.20. Normal day: stop $4 below entry, 1% account risk = calculated shares. Post-FOMC day ATR spikes to $5.80 — you halve size so dollar risk stays 1% despite needing $6 stop to avoid noise. Full size on spike day would have been 1.8× intended risk.",
        "tip": "Compare stop distance to current ATR — stops inside 0.5× ATR on your timeframe get random-tagged often.",
        "bullets": [
            "Volatility measures range and speed, not direction",
            "ATR quantifies typical range for sizing and stop placement",
            "Volatility clusters — high vol periods persist",
            "Reduce size when ATR expands beyond your normal baseline",
            "Compression often precedes expansion — plan for both",
        ],
        "takeaway": "Volatility is the market's volume knob. Turn your size down when the market turns it up.",
    },
    42: {
        "id": 42,
        "outcome": "You will interpret volume as participation confirmation, distinguish climax from absorption, and avoid trading breakouts on weak volume.",
        "intro": "Volume shows how many shares or contracts changed hands — the footprint of conviction behind a move.",
        "core": "Volume confirms participation: rising volume on trend moves suggests institutional involvement; declining volume on rallies warns of weak hands. Volume alone does not predict direction — context at structure matters.\n\nBreakouts on volume 1.5–2× recent average suggest genuine interest; breakouts on below-average volume often fail or retest sharply. Compare to same time-of-day average, not arbitrary global average.\n\nClimax volume at extremes — huge spike at range top after extended rally — can signal exhaustion (buyers exhausted) or initiation (new buyers aggressive). Require price response: rejection wick favors exhaustion; close beyond level favors continuation.\n\nIn forex, true volume is decentralized — use tick volume or futures proxy. In stocks and futures, exchange volume is reliable. Do not ignore volume on instruments where it is meaningful.",
        "chart_title": "Volume at breakouts",
        "chart_caption": "Volume bars expand on strong moves and shrink on weak drifts. Breakouts with participation differ from those on thin interest.",
        "example": "Amazon breaks $185 resistance. Break day volume 18M shares vs 10-day avg 11M — 1.6× confirmation. Hold above $185 on retest; trend to $192. Peer stock breaks resistance on 0.7× avg volume, closes back inside range next day — classic weak break fade to range mid.",
        "tip": "Mark volume relative to 10-day average at your entry bar — below 1.0× on breakout trades is a yellow flag.",
        "bullets": [
            "Volume measures participation, not direction by itself",
            "Breakouts with expanded volume confirm stronger moves",
            "Declining volume on trend leg warns of weakening momentum",
            "Climax spikes need price response to read exhaustion vs initiation",
            "Use exchange volume on stocks/futures; tick volume on spot forex",
        ],
        "takeaway": "Price tells you where; volume hints how many cared. Strong moves need participants — verify before you commit.",
    },
    43: {
        "id": 43,
        "outcome": "You will use market orders correctly for urgency, understand immediate fill mechanics, and know when market orders destroy edge.",
        "intro": "Market orders say 'get me in or out now.' That simplicity is powerful for exits and dangerous for impatient entries.",
        "core": "A market buy lifts the ask; a market sell hits the bid. Fill is guaranteed (for liquid instruments) at the best available prices walking the order book until your size fills. Large orders in thin markets move price against you — that's market impact plus slippage.\n\nAppropriate uses: emergency exit when thesis invalidated and speed beats ticks; stop-loss execution when stop triggers; small size on highly liquid symbols where spread is negligible.\n\nInappropriate uses: entering extended moves FOMO; illiquid small caps mid-day; size that exceeds typical top-of-book depth; entries where limit at planned level would fill with patience.\n\nMarketable limit orders (limit slightly through current price) blend urgency with price cap — often better than pure market on fast but not crashing moves.",
        "chart_title": "Market order fill path",
        "chart_caption": "Market orders walk the book from best bid/ask until filled. Size and liquidity determine how far price slips from the last quote.",
        "example": "You hold 200 shares Tesla, stop triggered at $245.00. Market sell fills $244.92 — 8 cents slippage acceptable to exit now. Contrast: market buy chasing extended move at $248.50 fills $248.71; price reverses to $246.00 — slippage plus bad location. Limit at $247.00 on planned pullback would have filled or saved capital.",
        "tip": "Default to limit for entries, market for urgent exits — flip that habit and slippage tax rises immediately.",
        "bullets": [
            "Market orders prioritize immediate fill at available prices",
            "Large market orders in thin books cause significant slippage",
            "Best for urgent exits and stop triggers on liquid symbols",
            "Avoid market entries on extended or illiquid moves",
            "Marketable limits cap price while seeking fast fill",
        ],
        "takeaway": "Market orders are exit tools and emergency tools — not the default entry button. Use them when seconds matter, not when patience pays.",
    },
    44: {
        "id": 44,
        "outcome": "You will place limit orders at planned levels, manage partial fills and duration, and accept non-fill as a valid outcome.",
        "intro": "Limit orders let you name your price — but the market is not obligated to meet you there.",
        "core": "Buy limit sits at or below current price (buy cheaper); sell limit at or above (sell higher). Order rests in the book until filled, cancelled, or expired (DAY, GTC). You control price; you sacrifice certainty.\n\nPlace limits at pre-defined structure — support bid, retest of broken resistance, scale-in grid — not round numbers alone. Offset one tick through level for fill priority on fast retests (buy limit slightly above support).\n\nPartial fills common on limits in moving markets — track remaining size and adjust stop for filled portion only. Unfilled balance is not failure; it preserved capital when price never offered your price.\n\nGTC limits require maintenance — stale orders at old levels trigger unintended entries weeks later. Cancel unfilled orders at session end unless strategy explicitly carries them.",
        "chart_title": "Limit order at support",
        "chart_caption": "Resting buy limits wait at support for price to come to you. Non-fill means the market never validated your price — often a blessing.",
        "example": "Long setup on USD/CAD pullback to 1.3580 support. Current 1.3595. Buy limit at 1.3582 — filled on dip to 1.3580, entry 1.3582 vs market chase at 1.3595 saved 13 pips (~0.5R on 25 pip stop). Prior week limit at 1.3620 never filled as price reversed from 1.3625 — avoided long into failing support.",
        "tip": "Set calendar alert to cancel unfilled DAY limits at session close — orphan limits cause surprise entries.",
        "bullets": [
            "Limits specify max buy or min sell price — fill not guaranteed",
            "Place at structural levels with optional one-tick offset",
            "Partial fills require separate stop management on filled size",
            "Non-fill preserves capital when price never reaches your level",
            "Cancel stale GTC orders — they become landmines later",
        ],
        "takeaway": "Limits reward patience and planning. Missing a move because your limit did not fill is cheaper than chasing with a market order.",
    },
    45: {
        "id": 45,
        "outcome": "You will deploy stop and stop-limit orders for protection and conditional entries, and understand trigger mechanics versus guaranteed exit.",
        "intro": "Stop orders wait inactive until price hits your trigger — then they transform into action. They are the bridge between plan and automatic execution.",
        "core": "Sell stop below market: activates when price falls to stop price — used for long protection or breakdown shorts. Buy stop above market: activates on rise — used for breakout longs or short cover. Once triggered, standard stop becomes market order (fill likely, price uncertain).\n\nStop-limit adds limit price after trigger — e.g., sell stop $100, limit $99.50. Protects against catastrophic fill in gap but may not fill if price gaps through limit. Use stop-limit when slippage terror exceeds gap risk; use stop-market when exit certainty is paramount.\n\nBrokers may not guarantee stop fills in extreme gaps — stock halts, weekend crypto gaps. Size accordingly; stops reduce risk, they do not eliminate gap risk entirely.\n\nConditional entry stops (buy stop above resistance) must include invalidation if trigger fires on false break — same as manual breakout rules: acceptance criteria still apply.",
        "chart_title": "Stop order trigger",
        "chart_caption": "Stop orders activate at trigger price. Stop-market seeks fill; stop-limit caps fill price but may leave position open in fast markets.",
        "example": "Long 100 shares AMD at $160.00, sell stop-market at $157.50 below swing low. Price drops to $157.50, triggers, fills $157.44 — protected. Alternative stop-limit $157.50/$157.30: fast drop gaps to $156.80, limit never fills, still holding — gap risk realized. For liquid AMD, stop-market appropriate; stop-limit better for thin after-hours.",
        "tip": "After entry, place protective stop immediately — every minute without stop is unplanned risk exposure.",
        "bullets": [
            "Stop orders activate at trigger then execute as market or limit",
            "Sell stops protect longs; buy stops trigger breakout longs",
            "Stop-limit caps fill price but may not exit in fast gaps",
            "Stops reduce risk but do not guarantee fill in halts or gaps",
            "Entry stops still require false-break filters in your plan",
        ],
        "takeaway": "Stops automate discipline. Place them when you enter, not when fear finally forces your hand.",
    },
    46: {
        "id": 46,
        "outcome": "You will trade defined ranges with fade entries at boundaries, manage mid-range chop, and exit when acceptance breaks the range.",
        "intro": "Range trading profits from balance — buying support, selling resistance — until the market picks a direction and leaves.",
        "core": "A range exists when price oscillates between horizontal support and resistance without sustained acceptance beyond either boundary. Identify range after at least two touches per side with rejection evidence.\n\nFade entries at boundaries: long near support with stop below range, target mid or opposite side; short near resistance with stop above. Mid-range entries have poor R and ambiguous direction — avoid the middle third.\n\nRange quality degrades over time — each test weakens level. Third and fourth fades carry higher break risk. Reduce size or require stronger rejection signals on later touches.\n\nExit range strategy when daily close accepts beyond boundary with volume — do not fade the first hour of breakout; switch to breakout or stand aside until new range forms.",
        "chart_title": "Range trading zones",
        "chart_caption": "Buy near support, sell near resistance, avoid mid-range. Stops beyond boundaries; targets at mean or opposite edge.",
        "example": "EUR/USD ranges 1.0800–1.0880 for twelve days. Long at 1.0815 off third support touch, stop 1.0792, target 1.0865. Two wins (+1.5R, +1.2R). Fourth touch, price closes 1.0785 — range broken, stop -1R. You disable fades until new 1.0750–1.0820 range establishes with two touches.",
        "tip": "Measure range height — if stop beyond boundary exceeds 1/3 of range width, R to opposite side may be negative; pass.",
        "bullets": [
            "Ranges need defined support/resistance with multiple touches",
            "Fade boundaries; avoid trading mid-range chop",
            "Later touches weaken levels — reduce size or tighten criteria",
            "Acceptance beyond boundary ends range strategy",
            "Target range mid or opposite side; stop outside boundary",
        ],
        "takeaway": "Range traders sell expensive and buy cheap inside a box — the moment the box breaks, stop fading and respect the new trend.",
    },
    47: {
        "id": 47,
        "outcome": "You will identify trend continuation setups — pullbacks, flags, and breakouts in trend direction — and enter when structure remains intact.",
        "intro": "Trend continuation trades join the dominant move after a pause, not at its exhausted end. Structure intact is the non-negotiable filter.",
        "core": "Continuation requires established trend on your timeframe — series of HH/HL or LH/LL. Pullback entry: wait for corrective move to prior structure, moving average, or trendline, then trigger on resumption candle.\n\nFlag and pennant patterns are compressed pullbacks — shallow, decreasing volatility, breaking in trend direction. Entry on break of flag high in uptrend with stop below flag low.\n\nBreakout continuation: price consolidates below prior high in uptrend, breaks above with acceptance — buys strength. Differs from reversal breakout — here higher lows preceded the base under resistance.\n\nInvalidation is structure break against trend — long continuation invalid if price closes below last HL. Do not label every dip continuation; choppy markets produce false flags that bleed trend strategies.",
        "chart_title": "Trend continuation pullback",
        "chart_caption": "In established trends, pullbacks to support or flags offer continuation entries. Structure must remain intact — higher lows in uptrends.",
        "example": "Copper daily uptrend, HL at $4.12, HH at $4.28. Pullback to $4.18 (prior breakout zone), 4H bullish engulfing. Long $4.21, stop $4.10 below HL, target $4.38 extension. Structure break below $4.12 would cancel all long continuation attempts.",
        "tip": "Ask 'Is this pullback making a higher low?' before every continuation long — if no, it may be reversal forming.",
        "bullets": [
            "Continuation requires clear trend structure on your timeframe",
            "Pullbacks to structure offer favorable R continuation entries",
            "Flags are shallow pullbacks — entry on break with trend",
            "Invalidation is break of last protective swing pivot",
            "Chop produces false flags — use regime filter",
        ],
        "takeaway": "Trend continuation is joining the leader after a breath — not guessing the first breath is the last.",
    },
    48: {
        "id": 48,
        "outcome": "You will recognize reversal signals at extremes — structure breaks, rejection, divergence — and distinguish early reversals from pullbacks.",
        "intro": "Reversals change who is in control. They pay well when caught early and punish badly when you confuse them with pullbacks.",
        "core": "Reversal evidence stacks: break of key structure (LL after uptrend), failure at major resistance/support, double top/bottom with neckline break, or sharp rejection after extended move (climax).\n\nEarly reversal entries offer best R but lowest win rate — entering on first ChoCH before full trend change confirms. Confirmed reversal waits for retest of broken structure (breakdown retest short) — higher win rate, worse R.\n\nDivergence (price higher high, momentum lower high) warns of weakening trend but is not entry alone — require price structure break. Many divergences resolve as consolidations, not reversals.\n\nReversal trading against strong trend without structure break is catching knives. Minimum requirement: broken pivot that was protecting prior trend.",
        "chart_title": "Reversal at structure break",
        "chart_caption": "Reversals show structure breaks, failed extremes, and rejection. Confirmation reduces false tops and bottoms.",
        "example": "Bitcoin rallies $58,000 to $64,800, prints lower high at $64,200, breaks $62,400 last HL — reversal structure. Retest $62,400 from below fails at $62,350. Short $62,200, stop $63,100, target $59,500. Prior 'reversal' at $63,500 without structure break was only pullback to $61,000 then resume — no pivot break, no trade.",
        "tip": "Counter-trend trades need a written invalidation for the old trend — without it you are hoping, not reversing.",
        "bullets": [
            "Reversals break protective structure of prior trend",
            "Stack structure break with rejection at key level",
            "Divergence warns but requires price confirmation",
            "Early vs confirmed reversal trades off R vs win rate",
            "Never fade strong trend without objective structure break",
        ],
        "takeaway": "Reversals are proven by broken structure, not by feeling 'too high.' Wait for the market to fire the old trend before betting on the new one.",
    },
    49: {
        "id": 49,
        "outcome": "You will measure and trade market swings using swing highs/lows, Fibonacci retracements, and swing projection for targets.",
        "intro": "Market swings are the natural rhythm of price — impulse legs followed by corrections. Reading swings turns chaos into measurable segments.",
        "core": "Identify swings with consistent rules — e.g., 3-candle pivot or fractal high/low. Connect swing points to see impulse (A to B) and correction (B to C). Next impulse often targets symmetry or extension of prior leg.\n\nFibonacci retracements of impulse (38.2%, 50%, 61.8%) commonly host corrective ends in trends. Confluence of 50% retrace with prior structure beats Fib alone.\n\nSwing projection: measured move — if AB leg was $10, CD target near $10 extension from C. Multiple equal swings in trend suggest rhythm continuation until broken.\n\nSwing analysis fails in formless chop — when swings overlap and pivots unclear, downgrade to range logic or stand aside. Swings require readable alternation of impulse and correction.",
        "chart_title": "Swing measurement",
        "chart_caption": "Impulse and corrective swings connect into measurable legs. Retracement and projection levels guide entries and targets.",
        "example": "Natural gas swings: $2.80 low to $3.15 high ($0.35 impulse), pulls to $2.98 (~50% retrace + prior resistance flip support). Long $3.02, stop $2.92, target $3.33 ($0.35 projected from $2.98). Fill and target hit as next impulse mirrors prior $0.35 leg.",
        "tip": "Use one swing measurement method consistently — mixing five Fib tools on every chart creates conflicting levels.",
        "bullets": [
            "Define swing pivots with consistent mechanical rules",
            "Impulse-correction alternation structures trend moves",
            "Fib retracements work best confluent with structure",
            "Measured move targets project prior leg length",
            "Unclear overlapping swings signal chop — reduce activity",
        ],
        "takeaway": "Swings give price a ruler. Measure legs, respect retracements, and project targets from what the market already did.",
    },
    50: {
        "id": 50,
        "outcome": "You will read momentum through candle bodies, range expansion, rate of change, and volume — distinguishing strong moves from exhausted drift.",
        "intro": "Momentum is the speed and force behind price. Reading it tells you whether to hold for extension or take profit before the stall.",
        "core": "Visual momentum: large directional bodies, small opposing wicks, consecutive closes in trend direction, and expanding range versus recent average. Weak momentum: overlapping candles, long wicks both sides, declining range, and fades on volume.\n\nRate of change (ROC) or short MACD histogram quantify momentum but lag slightly — use as filter, not sole trigger. Rising ROC in uptrend supports continuation; ROC divergence from price warns of slowdown.\n\nMomentum leads price at extremes — parabolic momentum often marks late trend phase where reward shrinks and reversal risk rises. Trail tighter or take partials when candles double average range late in trend.\n\nMomentum without structure is chasing — always anchor momentum read to location. Strong momentum into daily resistance differs from strong momentum breaking out of base with room above.",
        "chart_title": "Momentum expansion",
        "chart_caption": "Strong momentum shows wide bodies and follow-through. Weakening momentum shows overlap, wicks, and shrinking range before turns.",
        "example": "NVDA trends $850 to $920 over eight sessions — daily bodies expanding, volume rising. Momentum strong; hold trail. At $915, bodies shrink to 30% of prior week average, upper wicks lengthen, volume drops — momentum divergence. Partial at $912, trail rest at $895. Price tops $918 then reverses to $870 — momentum read preserved gains.",
        "tip": "Compare current candle range to 10-bar average — below 0.7× average after strong trend often precedes consolidation or reversal.",
        "bullets": [
            "Momentum reflects speed and force of price movement",
            "Strong trends show expanding bodies and directional closes",
            "Weakening momentum: overlap, wicks, declining volume/range",
            "Parabolic momentum late in trend warrants tighter management",
            "Combine momentum read with structure location always",
        ],
        "takeaway": "Momentum tells you how aggressively the market agrees with direction — ride it while expanding, respect it when it fades at structure.",
    },
})
