# Part 4: lessons 51-75
from _lesson_data_part3 import LESSON_CONTENT

LESSON_CONTENT.update({
    51: {
        "id": 51,
        "outcome": "You will prioritize capital preservation over aggressive growth, understand why survival is the first edge, and apply rules that protect your account through losing streaks.",
        "intro": "Capital preservation is not about avoiding risk — it is about ensuring one bad week cannot end your trading career. The market will always offer another opportunity; a blown account will not.",
        "core": "Capital preservation means structuring every decision so your account survives variance. Profits are optional in any single week; survival is mandatory across years. Professionals treat drawdown depth as a hard constraint, not a suggestion.\n\nPreservation flows from position sizing, loss limits, and refusing to trade when conditions fall outside your edge. A 1% risk per trade on a $30,000 account caps any single loss at $300 — painful but recoverable. The same setup at 5% risk turns one stop into a $1,500 wound that triggers emotional decisions.\n\nGrowth and preservation are not opposites when sized correctly. Compounding requires staying in the game long enough for edge to express itself over hundreds of trades. Aggressive sizing shortens that runway.\n\nAsk before every session: if I lose today, will I still have capital and confidence to trade tomorrow? If the answer is no, size is too large or limits are too loose.",
        "chart_title": "Capital preservation framework",
        "chart_caption": "Small, consistent risk per trade keeps equity curves recoverable. Large bets create cliffs that take months or years to climb back from.",
        "example": "Two traders start with $50,000. Trader A risks 0.75% ($375) per trade. After a brutal 10-trade losing streak, equity drops to $46,800 — a 6.4% drawdown, still fully operational. Trader B risks 3% ($1,500) per trade; the same streak cuts the account to $35,500 — a 29% hole requiring a 44% gain just to break even. Same market, same signals — different preservation rules.",
        "tip": "Write your maximum acceptable account decline for the month before you trade — when you hit it, stop, regardless of how 'close' the next setup looks.",
        "bullets": [
            "Survival precedes profitability — protect the account first",
            "Fixed small risk per trade limits damage from any single loss",
            "Compounding requires enough runway for edge to play out",
            "Oversizing turns normal losing streaks into career-ending events",
            "If today's loss threatens tomorrow's ability to trade, size is wrong",
        ],
        "takeaway": "You cannot compound what you do not keep. Capital preservation is the discipline of staying alive until your edge wins.",
    },
    52: {
        "id": 52,
        "outcome": "You will set and honor daily loss limits, recognize when to stop trading for the session, and prevent one bad day from becoming a catastrophic week.",
        "intro": "A daily loss limit is a circuit breaker — it stops the bleeding before fatigue, frustration, and revenge trading take over.",
        "core": "Daily loss limits cap total realized loss for a session, measured in dollars, percentage of account, or R-multiples. Common rules: stop after -2R, -3R, or -2% of equity, whichever you define in advance.\n\nLimits work because decision quality degrades after consecutive losses. Studies of discretionary traders show increased rule-breaking after the third loss of a day. A hard stop removes the option to 'make it back' on trade six or seven.\n\nSet limits when calm, not mid-drawdown. Tie them to your average risk per trade — if you risk $200 per trade, a -3R daily cap means $600 max loss, then screens off.\n\nHonoring limits matters more than setting them. Moving the limit 'just once' trains your brain that rules are negotiable under stress — the exact moment they must be fixed.",
        "chart_title": "Daily loss limit circuit breaker",
        "chart_caption": "When cumulative session loss hits your predefined cap, trading stops. Capital and mental clarity are preserved for the next session.",
        "example": "Your plan: risk $250 per trade (1% of $25,000), daily max -3R ($750). Trade 1: -1R stop on ES long at 5,280, stopped at 5,268. Trade 2: -1R on AAPL short, stopped at $182.40. Trade 3: -1R on EUR/USD breakout fade. Down $750 — you close platforms, log the session, and walk away. Trade 4 would have been a revenge entry on oil that worked — irrelevant. You saved the remaining $24,250 and your judgment for tomorrow.",
        "tip": "Set a phone alarm labeled 'Daily limit hit — close charts' so the stop is physical, not willpower alone.",
        "bullets": [
            "Daily limits cap total session loss in R, dollars, or percentage",
            "Decision quality drops after consecutive losses — limits prevent spirals",
            "Define limits before the session when emotions are neutral",
            "Moving the limit once teaches your brain that rules are optional",
            "Stopping early preserves capital and cognitive bandwidth",
        ],
        "takeaway": "The best trade after hitting your daily limit is no trade. Tomorrow's session starts with a full mind and intact capital.",
    },
    53: {
        "id": 53,
        "outcome": "You will scale into positions with predefined rules, manage average entry and total risk, and avoid doubling down on hope when a trade moves against you.",
        "intro": "Scaling in adds to a position in stages — a tool for conviction and better average price when used with rules, a trap when used to avoid admitting a loss.",
        "core": "Scaling in divides your intended full size across multiple entries at planned levels — initial entry on trigger, add on pullback hold, final add on confirmation. Total risk is calculated across all legs, not per leg independently.\n\nLegitimate scaling requires a written plan before the first click: entry prices, add conditions, maximum total size, and combined stop. If the second add only happens 'if it comes back,' you are averaging down on hope, not scaling in on strategy.\n\nCombined risk must still fit your account cap. Three adds of 0.33% risk each equal 1% total — not three separate 1% bets totaling 3%.\n\nScaling in suits trends and range boundaries with clear invalidation. It fails in counter-trend knife catches where each add increases exposure to a move that may not revert.",
        "chart_title": "Planned scale-in levels",
        "chart_caption": "Entries split across predefined levels with a combined stop and total size cap. Each add requires its own confirmation, not just lower price.",
        "example": "You plan a long on Microsoft targeting a breakout above $420. Full intended risk: 1% of $40,000 ($400). Entry 1: $415.50 on pullback hold, 0.4% risk, stop combined at $412.00. Entry 2: $413.80 if price retests rising 20 EMA with bullish rejection, add 0.35% risk. Entry 3: $421.20 on daily close above $420, add 0.25% risk. Combined stop remains $412.00 — if hit, entire position exits. Average entry improves without exceeding $400 total risk.",
        "tip": "Never add to a losing position unless your written plan explicitly allowed that add level before entry one.",
        "bullets": [
            "Scale-in splits size across planned entries, not random clicks",
            "Calculate total risk across all legs before the first entry",
            "Each add needs its own confirmation trigger, not just cheaper price",
            "Averaging down on hope without a plan is not scaling — it is denial",
            "Combined stop exits the entire position when thesis fails",
        ],
        "takeaway": "Scale in with a map, not with emotion. Planned adds improve average entry; unplanned adds often improve your loss size.",
    },
    54: {
        "id": 54,
        "outcome": "You will scale out of winners systematically, lock in partial profits, and manage the trade-off between capturing gains and letting trends run.",
        "intro": "Scaling out takes profits in pieces instead of all-or-nothing exits — smoothing equity curves while leaving room for outsized winners.",
        "core": "Scaling out sells portions of a position at predefined targets while trailing or holding the remainder. Common structure: exit one-third at 1R, one-third at 2R, trail the rest with structure or ATR stop.\n\nBenefits include reduced regret when price reverses after a good move, psychological relief that supports holding runners, and more consistent small wins funding patience for larger trends.\n\nCosts include reduced average R on trades that go straight to target without pullback — full exit at 3R beats partials if price never retraces. Track blended outcomes in your journal; scaling rules must improve expectancy, not just feel comfortable.\n\nDefine scale-out levels before entry alongside your stop. Moving targets after price moves invites greed-driven adjustments that leave profits on the table or give back gains.",
        "chart_title": "Scale-out profit ladder",
        "chart_caption": "Partial exits at 1R and 2R lock gains while a trailing stop on the remainder captures extended moves.",
        "example": "Long gold from $2,340, stop $2,328 (12 points, $120 risk per mini contract). Target plan: sell 1 contract at $2,352 (+1R, $120 profit), 1 at $2,364 (+2R, $240), trail final contract with stop below each 4H higher low. Price reaches $2,378 before trailing stop hits at $2,368. Blended result: $120 + $240 + $280 = $640 on three-contract position versus $720 if you held all to $2,364 — but the trail captured an extra $140 on the runner the full-exit trader missed.",
        "tip": "Log effective R after partial exits — a trade that 'felt like a win' may be 0.8R blended if you scaled too early.",
        "bullets": [
            "Scale-out sells portions at predefined R or structure targets",
            "Partials reduce regret and support holding trend runners",
            "Blended R matters — track whether scaling improves expectancy",
            "Early scaling sacrifices max R on trades that never pull back",
            "Define exit tiers before entry, not after price moves in your favor",
        ],
        "takeaway": "Scaling out trades maximum profit on some trades for smoother equity and better psychology on most — if the math supports it.",
    },
    55: {
        "id": 55,
        "outcome": "You will move stops to breakeven at defined progress points, understand when breakeven stops help versus hurt, and avoid getting shaken out of valid trends.",
        "intro": "A breakeven stop removes initial risk after price moves in your favor — but moved too early, it turns winners into scratch trades and hides real edge.",
        "core": "Breakeven means adjusting stop to entry price (plus costs) after the trade reaches a predefined milestone — often +1R or after structure break confirming momentum. You no longer risk loss on the trade; worst case is a flat exit minus commissions.\n\nBreakeven stops protect capital during choppy follow-through. They also increase stop-out rate when normal pullbacks tag entry before the trend resumes. The trade-off is psychological safety versus statistical win rate.\n\nRules beat discretion: move to breakeven only after daily close beyond a level, or after +1.5R, not the moment you see green. Include spread and commission buffer — 'breakeven' at exact entry still costs money on exit.\n\nNever move to breakeven to avoid feeling wrong. That is emotional stop management. Valid breakeven moves follow written plan milestones tied to structure, not comfort.",
        "chart_title": "Breakeven stop placement",
        "chart_caption": "After price reaches a defined profit threshold, stop moves to entry plus costs. Normal pullbacks to entry exit flat instead of at a loss.",
        "example": "Short crude oil at $78.50, stop $79.10 (60 cents, $600 risk per contract). Plan: move stop to $78.52 (breakeven plus tick) after price closes below $77.90 support (-1R achieved). Price dips to $77.60, then rallies to $78.55 — stopped breakeven for -$20 commission. Annoying, but capital preserved. Without the rule, you might have held through $79.10 stop for full -$600 when the bounce failed and oil dropped to $76.80 later — breakeven saved $580 on that path.",
        "tip": "Track how often breakeven stops get tagged before target — if it exceeds 40% of trades, your trigger is too early.",
        "bullets": [
            "Breakeven stops move risk to zero after defined progress milestones",
            "Include commission and spread buffer — true breakeven is not exact entry",
            "Early breakeven increases scratch exits from normal pullbacks",
            "Define move-to-breakeven rules before entry, tied to structure or R",
            "Review whether breakeven rules help or hurt your strategy's expectancy",
        ],
        "takeaway": "Breakeven stops are insurance, not a guarantee of profit. Use them at planned milestones — not at the first sign of green.",
    },
    56: {
        "id": 56,
        "outcome": "You will build genuine confidence from process and data while avoiding arrogance that leads to oversizing, rule-breaking, and ignoring risk after winning streaks.",
        "intro": "Confidence comes from repeatable process; arrogance comes from recent profits. One keeps you in the game — the other precedes most blow-ups.",
        "core": "Trading confidence is trust in your preparation, rules, and ability to execute under uncertainty — not certainty that the next trade will win. It grows from journaled evidence: 'I follow my plan 90% of the time' beats 'I am hot right now.'\n\nArrogance inflates after winning streaks: size creeps up, filters loosen, stops feel optional. Markets do not know you won yesterday; the next trade has the same independent probability as always.\n\nConfident traders take valid setups after losses because the process says so. Arrogant traders skip rules after wins because they feel special. Both states feel powerful — only one is grounded in reality.\n\nBuild confidence through small verified wins in process compliance, not P&L alone. 'I stopped at my daily limit' is a confidence deposit even on a red day.",
        "chart_title": "Confidence versus arrogance",
        "chart_caption": "Process-based confidence stays steady through wins and losses. Ego-driven arrogance spikes after profits and crashes after drawdowns.",
        "example": "After five winners totaling +8R, you feel unstoppable and double size on a B-grade setup — a marginal breakout on a thinly traded stock at $14.75. It fails for -2R at doubled size (-4R effective). Confidence would have taken the same setup at normal size (-1R) or passed entirely per your filter. Arrogance turned a manageable loss into a session wrecker and triggered revenge trading.",
        "tip": "After three consecutive winners, read your written rules aloud before the next entry — streaks are when arrogance attacks.",
        "bullets": [
            "Confidence trusts process; arrogance trusts recent profits",
            "Winning streaks increase oversizing and filter violations",
            "The next trade's odds do not improve because you won yesterday",
            "Process compliance builds durable confidence independent of P&L",
            "Treat streaks as noise — size and rules stay constant",
        ],
        "takeaway": "Be confident in your system and humble about any single trade. The market humbles arrogance quickly and expensively.",
    },
    57: {
        "id": 57,
        "outcome": "You will recognize FOMO triggers, avoid chasing extended moves, and apply practical techniques to stay aligned with your plan when others are profiting without you.",
        "intro": "Fear of missing out is the urge to enter because price is moving — not because your setup appeared. It is one of the most expensive emotions in trading.",
        "core": "FOMO activates when you watch a move run without you, see social media gains, or miss an entry by seconds. The brain treats missed profit as loss, pushing impulsive entries at poor locations — extended breakouts, parabolic tops, illiquid spikes.\n\nFOMO entries typically have worse reward-to-risk: chasing Bitcoin from $67,000 to $68,500 with stop at $66,800 risks $700 to make $300 if the move is already exhausted. The math inverts.\n\nCountermeasures: pre-written 'no chase' rules (only enter on pullback or retest), mandatory 5-minute pause before any unplanned entry, and a watchlist of A-setups so you redirect attention from random movers.\n\nMissing a trade is not a loss — it is zero. Entering late and getting reversed is a real loss. Professionals accumulate missed moves; amateurs accumulate chase scars.",
        "chart_title": "FOMO chase versus planned entry",
        "chart_caption": "Chasing extended moves offers poor reward-to-risk. Waiting for retest or the next setup preserves capital for higher-quality entries.",
        "example": "NVDA gaps from $118 to $125 on news. You missed the open. FOMO says buy $125.20. Your plan requires pullback to prior resistance-turned-support near $121.50. You chase at $125.20; price reverses to $119.80 by close — -5.4% in hours. The planned entry at $121.80 with stop $119.50 would have offered 3:1 R toward $128 with defined risk. FOMO paid $5.40 per share for impatience.",
        "tip": "When FOMO spikes, write down the trade you want to take and wait one full candle on your entry timeframe — most urges fade.",
        "bullets": [
            "FOMO pushes entries based on movement, not on your setup criteria",
            "Chase entries typically offer inverted reward-to-risk",
            "Missing a trade costs nothing; a bad chase costs real capital",
            "Use pause rules and retest requirements before unplanned entries",
            "Redirect attention to your watchlist, not the day's biggest mover",
        ],
        "takeaway": "There is always another trade. FOMO makes you pay premium prices for tickets to moves that already left the station.",
    },
    58: {
        "id": 58,
        "outcome": "You will identify overtrading patterns, set trade count limits, and understand how excessive activity erodes edge through costs, fatigue, and B-grade setups.",
        "intro": "Overtrading is trading when there is no edge — often driven by boredom, FOMO, or the false belief that more activity equals more profit.",
        "core": "Overtrading manifests as exceeding daily trade limits, taking setups that fail your filters, flipping direction repeatedly in chop, or trading outside planned sessions. Each extra trade adds commission, slippage, and decision fatigue.\n\nEdge clusters in specific conditions — trend pullbacks, range fades, breakout retests. Most clock time on charts is noise. Trading noise converts capital into broker revenue.\n\nTrack trades per day and per week. Many profitable discretionary traders report fewer than five quality trades per week. If you logged forty trades last week, ask how many were A-grade per your journal tags.\n\nCures include hard daily trade caps (max 2–3), mandatory minimum time between entries, and 'no-trade' conditions when price is mid-range without structure touch.",
        "chart_title": "Trade frequency versus quality",
        "chart_caption": "P&L often improves when trade count drops. Edge concentrates in a few high-quality moments, not in constant clicking.",
        "example": "You log 18 trades in one week on EUR/USD: 6 winners, 12 losers, net -4.2R before spread. Review shows 4 winners came from planned London pullback setups; 14 trades were afternoon chop entries not in your plan. Next week you cap at 2 trades per day, London session only — 8 trades, 5 winners, net +3.1R. Same market, same strategy — less overtrading.",
        "tip": "Count your trades every Friday — if the number surprises you, overtrading is already happening.",
        "bullets": [
            "Overtrading is activity without edge — boredom and FOMO drive most of it",
            "Each extra trade adds costs and decision fatigue",
            "Most chart time is noise — edge appears at specific structural moments",
            "Hard daily trade caps and session limits reduce impulsive entries",
            "Review journal tags — B and C trades often fund broker, not you",
        ],
        "takeaway": "Amateurs measure success by activity; professionals measure it by selectivity. Do less, but do it better.",
    },
    59: {
        "id": 59,
        "outcome": "You will recover emotionally after intense sessions — wins or losses — reset mental state, and return to process without carrying euphoria or frustration into the next trade.",
        "intro": "Emotional recovery is the skill of closing one session's feelings before opening the next chart. Unprocessed emotion becomes the next trade's invisible hand.",
        "core": "Intense sessions — big wins, sharp losses, near-misses — flood your nervous system with adrenaline and cortisol. Decisions made in that state bypass your plan. Recovery means deliberate decompression before the next decision.\n\nProtocols work: fixed cooldown after session end (20–30 minutes away from screens), physical movement, journaling three sentences on emotional state, and prohibiting new entries until a checklist confirms calm.\n\nWinning sessions need recovery too. Euphoria causes oversizing and filter drops as surely as anger causes revenge trades. 'I am on fire' is as dangerous as 'I need it back.'\n\nSeparate identity from P&L. One session does not define your skill; it defines one sample from a distribution you are building over hundreds of trades.",
        "chart_title": "Emotional recovery cycle",
        "chart_caption": "After intense P&L, a deliberate reset period prevents the next session's first trade from being an emotional reaction.",
        "example": "You lose -3R by 10:30 AM on a volatile CPI day — stopped on gap, then revenge-chased oil. Daily limit should have halted you at -3R but you broke rules. Recovery protocol: close platform, walk 15 minutes, journal 'frustrated, broke limit, chased.' No trading until next calendar day. Next morning, calm checklist complete, you take one A-setup on S&P pullback at 5,190 with normal size — plan-compliant regardless of yesterday's scar.",
        "tip": "Rate your emotional state 1–10 before the first trade each session — if above 7 or below 4, wait 15 minutes and re-rate.",
        "bullets": [
            "Intense wins and losses both require deliberate emotional reset",
            "Cooldown periods prevent carry-over into the next decision",
            "Euphoria after wins causes oversizing as reliably as anger after losses",
            "Journal emotional state to spot patterns linking mood to rule breaks",
            "Your worth as a trader is not today's P&L — it is process over time",
        ],
        "takeaway": "The trade after your worst day — or best day — is the most dangerous if you have not recovered. Reset first, click second.",
    },
    60: {
        "id": 60,
        "outcome": "You will build mental resilience through routines, reframing, and gradual exposure to uncertainty so drawdowns and variance feel manageable rather than catastrophic.",
        "intro": "Mental resilience is not ignoring pain — it is training your response to uncertainty so setbacks become data instead of identity crises.",
        "core": "Trading is probabilistic. Even valid edges produce losing streaks that feel personal. Resilience comes from expecting variance, preparing responses in advance, and measuring yourself on process metrics — rule compliance, journal consistency — not daily P&L.\n\nBuild resilience incrementally: size small while learning, increase only after sustained process compliance, maintain non-trading identity (health, relationships, hobbies) so one red month does not hollow your life.\n\nCognitive reframing helps: 'This is a good loss — plan followed' versus 'I am terrible.' Streaks are normal in binomial distributions; your job is surviving them at controlled size.\n\nPhysical foundations matter — sleep deprivation cuts prefrontal function exactly when you need discipline. Resilience is partly a body problem, not only a mindset problem.",
        "chart_title": "Resilience through variance",
        "chart_caption": "Equity curves include drawdowns even for profitable systems. Resilience is continuing process through valleys without self-destruction.",
        "example": "Your backtest shows 12% max drawdown; live trading hits 11% over six weeks of choppy conditions. Without resilience, you abandon the strategy and chase a new system — restarting the learning curve. With resilience, you halve size per drawdown rules, journal every trade, and continue. Month eight returns to new equity high as conditions normalize. The edge did not disappear — variance did its job.",
        "tip": "Keep a 'process scorecard' weekly: journal rate, rule compliance %, sleep average — track inputs you control, not just outputs.",
        "bullets": [
            "Resilience expects variance — losing streaks are normal, not proof of failure",
            "Measure process compliance, not just daily P&L",
            "Maintain life outside trading so drawdowns do not define you",
            "Predefine drawdown responses while calm — execute mechanically when hit",
            "Sleep and physical health directly affect decision quality",
        ],
        "takeaway": "Edge without resilience dies in the first serious drawdown. Train your mind to survive variance the way you train your rules to survive temptation.",
    },
    61: {
        "id": 61,
        "outcome": "You will define trading edge as statistical advantage over many trades, distinguish edge from luck, and identify where your strategy might possess positive expectancy.",
        "intro": "Edge is not knowing the next candle — it is a repeatable advantage that produces positive average results over a large sample of similar trades.",
        "core": "Trading edge exists when your strategy's expectancy is positive after costs: Expectancy = (Win% × Avg Win) − (Loss% × Avg Loss). A 45% win rate with 2.5R average winners and 1R average losers yields positive expectancy even though most trades lose.\n\nEdge comes from exploiting recurring market behavior — trend continuation after pullback, false break fade, volatility expansion — with filters that skip low-quality occurrences. Without filters, you have a concept, not edge.\n\nShort samples lie. Ten lucky trades prove nothing; two hundred plan-compliant trades begin to reveal truth. Edge is a property of the system over time, not of today's P&L.\n\nEdge erodes when markets regime-shift, costs rise, or execution slips. It requires periodic review — but first you must define what edge means for your specific written strategy.",
        "chart_title": "Edge as positive expectancy",
        "chart_caption": "Over many trades, average profit per trade minus average loss per trade defines whether your approach has statistical advantage.",
        "example": "Your pullback strategy over 150 journaled trades: 44% win rate, average winner +2.4R, average loser -1R. Expectancy = (0.44 × 2.4) − (0.56 × 1.0) = 1.056 − 0.56 = +0.496R per trade. At $300 risk per trade, expected value ≈ $149 per trade over the sample — edge exists. A friend with 60% win rate but 0.8R winners and 1.2R losers has negative expectancy despite 'winning more often.'",
        "tip": "Calculate expectancy from your journal before searching for new indicators — you may already have edge you are sabotaging with rule breaks.",
        "bullets": [
            "Edge = positive average result per trade over a large sample",
            "Expectancy combines win rate with average win and loss size",
            "Edge targets repeatable market behavior with quality filters",
            "Small samples confuse luck with skill — require 100+ trades",
            "High win rate alone does not mean edge if losers exceed winners",
        ],
        "takeaway": "Edge is math over many trades, not intuition on one chart. Find it, measure it, protect it with execution discipline.",
    },
    62: {
        "id": 62,
        "outcome": "You will design trade filters that screen for your best conditions, reject marginal setups automatically, and improve expectancy by trading less but better.",
        "intro": "Filters are the gates your setup must pass before capital is risked. They turn a vague idea into a selective system with definable edge.",
        "core": "Trade filters answer: under what conditions does my strategy work, and when do I stand aside? Common filters include trend alignment (daily uptrend only), volatility band (ATR not extreme), session window (London open only), minimum reward-to-risk (2R+), and liquidity (average volume threshold).\n\nEach filter removes trades — that is the point. A breakout strategy without a 'no trade during first 5 minutes' filter bleeds on open noise. A pullback strategy without 'above 200-day MA' filter fights bear markets.\n\nFilters must be testable yes/no questions before entry: 'Is price above the 50 EMA on daily?' Not 'does this feel strong?' Feelings are not filters.\n\nReview filter performance in your journal quarterly. Cut filters that remove winners and keep losers; tighten filters that let through bleeding trades.",
        "chart_title": "Trade filter funnel",
        "chart_caption": "Watchlist candidates pass through sequential filters — trend, structure, session, R-ratio — until only A-grade setups remain.",
        "example": "Your swing long filter stack: (1) daily close above 50 and 200 EMA, (2) 4H pullback to 20 EMA, (3) bullish rejection candle, (4) stop distance allows 2R+ to next resistance, (5) average daily volume above 500K shares. Of 40 watchlist stocks Monday, 3 pass all filters — AMD at $162.40, COST at $875.20, and UNH at $582.10. The other 37 are noise you did not pay to trade.",
        "tip": "Write filters as a checklist with checkboxes — if any box is unchecked, the trade is a automatic pass regardless of FOMO.",
        "bullets": [
            "Filters define when your strategy operates — and when it does not",
            "Each filter should be a binary yes/no question, not a feeling",
            "Removing trades via filters improves quality, not missed opportunity",
            "Common filters: trend, volatility, session, R-ratio, liquidity",
            "Review filter effectiveness quarterly using journal tags",
        ],
        "takeaway": "Your edge lives in what you skip as much as what you take. Filters are how you skip intelligently.",
    },
    63: {
        "id": 63,
        "outcome": "You will wait for entry confirmation signals that validate your thesis, reduce premature entries, and distinguish between anticipation and evidence.",
        "intro": "Entry confirmation is the proof your scenario is playing out — the difference between guessing a turn and trading a verified reaction.",
        "core": "Confirmation converts a zone of interest into a trade trigger. A support level becomes actionable when price prints rejection — hammer, engulfing, or hold-and-close — not when price merely approaches the level.\n\nConfirmation types vary by strategy: breakout traders want close beyond level plus retest hold; pullback traders want counter-trend momentum loss plus bullish candle at support; mean reversion traders want wick rejection at range extreme.\n\nAnticipation entries bet the confirmation will come — higher reward if right, higher stop-out rate when wrong. Confirmation entries sacrifice some price for higher probability. Most developing traders improve by shifting right on the timeline.\n\nDefine confirmation on your decision timeframe. A 1-minute pin bar at daily support is insufficient if your stop and target are daily structure-based — confirm on the timeframe that matches your trade management.",
        "chart_title": "Entry confirmation trigger",
        "chart_caption": "Price approaches a level (interest zone), then prints a confirmation signal (rejection, break-and-hold) before entry — not before.",
        "example": "Bitcoin approaches $61,500 support — your interest zone. Anticipation entry at $61,520 gets stopped at $60,800 when support fails (-$720 per coin). Confirmation rule: 4H bullish engulfing off $61,500 with stop below $60,750. Engulfing prints at $61,680 close; you enter $61,700, stop $60,720, target $64,200. Support holds; trade reaches $63,800 (+$2,100). Same level — confirmation saved the thesis.",
        "tip": "List your confirmation trigger in one sentence on every trade plan — if price has not done that exact thing, you are anticipating, not confirming.",
        "bullets": [
            "Confirmation is evidence your scenario is active — not hope it will be",
            "Rejection candles, break-and-hold closes, and retest holds are common triggers",
            "Anticipation entries save price but increase false signal rate",
            "Confirm on the timeframe that matches your stop and target structure",
            "One clear trigger sentence prevents ambiguous 'looks good' entries",
        ],
        "takeaway": "Amateurs enter at the level; professionals enter on the reaction. Confirmation is patience converted into probability.",
    },
    64: {
        "id": 64,
        "outcome": "You will plan exits before entry — stop, targets, scale rules, and time stops — so you never manage a trade without a predefined escape map.",
        "intro": "Exit planning is deciding how you will lose small, win appropriately, or time out — before you know which outcome will occur.",
        "core": "Every trade plan needs three exits: stop loss (thesis invalidation), profit target or scale plan (reward realization), and optional time stop (exit if nothing happens by bar N). Entering without all three is flying without landing gear.\n\nStops belong at structural invalidation. Targets belong at logical resistance, measured moves, or R-multiples defined by your strategy's historical average winner. Time stops prevent capital trapped in dead positions bleeding opportunity cost.\n\nExit plans must be written before entry and honored without negotiation mid-trade — except for predefined trailing rules that activate at milestones. 'It might come back' is not an exit plan.\n\nPartial exit plans specify fractions and levels: 50% at 2R, trail remainder. Blended planning prevents the common failure of reaching profit then round-tripping to stop.",
        "chart_title": "Exit plan map",
        "chart_caption": "Before entry, mark stop, targets, scale levels, and time stop. Every outcome has a predefined response.",
        "example": "Long Shopify at $68.40 on pullback to daily support. Exit plan written pre-entry: Stop $66.90 (below swing low, -$1.50/share). Target 1: sell half at $71.40 (+2R, +$3.00). Target 2: trail rest with stop below each 4H higher low. Time stop: exit remainder if no progress toward $71.40 within 8 trading days. Day 5 hits $71.55 — half sold. Day 9 trail stopped at $70.10 on remainder. Blended +$2.35/share average versus unplanned hold that round-tripped to $67.20.",
        "tip": "Place stop and limit orders immediately after fill when possible — automation beats mid-trade negotiation with yourself.",
        "bullets": [
            "Define stop, targets, and optional time stop before every entry",
            "Stop = thesis failure point; target = logical reward zone",
            "Scale-out plans prevent giving back open profits",
            "Time stops free capital from trades that go nowhere",
            "Mid-trade exit changes without predefined rules are usually emotional",
        ],
        "takeaway": "Plan the exit when you still think clearly — at entry — not when fear or greed owns the mouse.",
    },
    65: {
        "id": 65,
        "outcome": "You will periodically review whether your trading edge still exists, detect edge decay from regime change or rule drift, and adjust or pause strategies based on evidence.",
        "intro": "Markets evolve, execution slips, and rules erode. Edge review asks the uncomfortable question: would I start this strategy today with fresh capital?",
        "core": "Edge review compares recent live or journaled performance to historical expectations — win rate, average R, profit factor, max drawdown, rule compliance. Significant deviation triggers investigation, not immediate abandonment.\n\nCauses of edge decay: market regime shift (trend to chop), increased competition on obvious setups, cost changes, or your own filter drift (taking B-grades again). Each requires different fixes — regime filters, pausing, or process tightening.\n\nReview cadence: monthly quick stats, quarterly deep review with 50+ trade sample, annual strategy audit against backtest assumptions. Sample size matters — do not kill a strategy after seven losses.\n\nWhen edge review shows persistent negative expectancy over 100+ plan-compliant trades, stop trading that strategy live. Paper test revisions before returning capital.",
        "chart_title": "Edge review dashboard",
        "chart_caption": "Track win rate, average R, profit factor, and drawdown against backtest benchmarks. Divergence signals investigation.",
        "example": "Your 2024 breakout strategy backtest: 47% win rate, 2.1R avg win, profit factor 1.55. Live Jan–Mar 2025: 38% win rate, 1.6R avg win, profit factor 0.92 over 62 trades — all plan-compliant. Investigation shows market spent 70% of days in tight ranges versus 40% in backtest period. You add ADX > 25 filter and pause live trading two weeks while paper testing. Revised filter restores paper profit factor to 1.4 — edge was filtered out, not gone.",
        "tip": "Compare live stats only on plan-compliant trades — mixing rule breaks into edge review corrupts the diagnosis.",
        "bullets": [
            "Edge review compares live performance to historical expectations",
            "Regime change, costs, and rule drift all erode edge",
            "Use sufficient sample size before declaring edge dead — 50–100+ trades",
            "Monthly stats, quarterly deep review, annual full audit",
            "Persistent negative expectancy on compliant trades means pause and revise",
        ],
        "takeaway": "Edge is not permanent — it is maintained through measurement and honest review. What worked last year may need filters this year.",
    },
    66: {
        "id": 66,
        "outcome": "You will detect market structure shifts in real time, adjust bias when character changes, and stop applying trend tactics in ranges or vice versa.",
        "intro": "Market structure shift is when the swing map changes — trend becomes range, range breaks to trend, or leadership flips. Trading the old character after a shift is expensive.",
        "core": "Structure shifts appear as breaks of key pivots: in uptrend, a lower low below the last HL signals potential shift; in range, acceptance beyond boundary signals breakout shift. Change of character (ChoCH) often precedes full trend reversal.\n\nFractal awareness matters — a 15-minute bearish shift inside a daily uptrend may be a pullback, not a reversal. Define which timeframe's structure governs your bias and which governs entry timing.\n\nWhen structure shifts, old setups deactivate. Trend pullback longs off broken support become traps. Range fades after breakout acceptance become stop hunts. Update your playbook label: 'trend mode' or 'range mode' or 'stand aside.'\n\nMechanical labeling prevents denial — mark last HH, HL, LH, LL after each session close and act when progression breaks.",
        "chart_title": "Structure shift detection",
        "chart_caption": "When swing progression breaks — lower low in uptrend or break of range — market character changes. Old tactics may no longer apply.",
        "example": "Apple daily structure: HH at $195, HL at $188, HH at $198, HL at $192 — bullish. Price drops to $186, closing below $192 HL. Structure shifts to neutral/bearish. You stop taking long pullbacks to 20 EMA; next valid playbook is short rallies toward $192 resistance or wait for new HL above $198 to restore bullish bias. A trader who keeps buying dips from $190 to $185 loses -$5/share chasing the old character.",
        "tip": "After any trade stopped out, check whether structure changed on your bias timeframe — sometimes the stop was the map updating.",
        "bullets": [
            "Structure shift = break in swing progression on your bias timeframe",
            "ChoCH and BOS signal continuation or character change",
            "Deactivate old setup types when structure shifts",
            "Higher timeframe structure overrides lower timeframe noise",
            "Update swing labels mechanically — denial is costly",
        ],
        "takeaway": "Trade the market's current character, not the one from yesterday. Structure shift is your signal to change tactics or wait.",
    },
    67: {
        "id": 67,
        "outcome": "You will read basic order flow concepts — aggression, absorption, and delta — to confirm or challenge your chart thesis at key levels.",
        "intro": "Order flow shows who is hitting the market aggressively and whether passive liquidity is absorbing or folding — the auction beneath the candles.",
        "core": "Order flow tracks transactions: market buys lift the ask (aggressive buyers), market sells hit the bid (aggressive sellers). Footprint charts, DOM, and delta (buy volume minus sell volume) expose this activity inside each candle.\n\nAt support, bullish scenario includes aggressive selling absorbed by passive bids — large sell delta but price holds. At resistance, aggressive buying into resting offers that eventually overwhelm price signals rejection.\n\nOrder flow confirms or denies chart levels. A breakout with strong positive delta and rising CVD (cumulative volume delta) supports continuation; a breakout with negative delta and long upper wicks warns of trap.\n\nYou do not need expensive tools to start — watch bid/ask aggression on your platform, note delta on key level tests, and compare to your candle read. Order flow supplements structure; it does not replace it.",
        "chart_title": "Order flow at a level",
        "chart_caption": "Aggressive buying into resistance that fails suggests rejection. Aggressive selling at support that gets absorbed suggests defense.",
        "example": "ES futures test 5,300 resistance. Chart shows upper wick rejection. Footprint on the 5-minute bar shows 62% sell delta despite price ticking to 5,302 — aggressive buyers absorbed by passive offers, then sellers hit bid aggressively on close at 5,296. You fade toward 5,285 with stop above 5,304. Without order flow, the wick alone might have been enough; delta confirmed sellers took control at the high.",
        "tip": "Compare delta at a level test to the prior test — weakening sell delta at support on retest supports long thesis.",
        "bullets": [
            "Order flow reveals aggressive versus passive participation",
            "Delta and CVD show net buying or selling pressure inside candles",
            "Absorption at support: selling aggression without price breakdown",
            "Breakouts with negative delta warrant skepticism",
            "Use order flow to confirm structure — not to replace it",
        ],
        "takeaway": "Charts show what happened; order flow hints at who forced it. Together they sharpen execution at critical levels.",
    },
    68: {
        "id": 68,
        "outcome": "You will set price and indicator alerts so the market notifies you at key levels, reducing screen time and impulsive mid-range trading.",
        "intro": "Alerts let the market come to you. They replace passive chart-watching with active preparation triggered only when price reaches your predefined zones.",
        "core": "Effective alerts mark structural levels — support, resistance, breakout triggers — and optional indicator conditions (RSI at 30 in uptrend, price crossing 20 EMA). When an alert fires, you open the chart, run your checklist, and decide — not react blindly.\n\nAlert discipline prevents overtrading: no alert, no chart during off-hours. This breaks the habit of finding setups because you are bored and staring at candles.\n\nSet alerts with notes: 'AAPL daily support $172 — check for 4H hammer.' Context in the alert reminds future-you what to look for. Naked price alerts cause confusion when they fire.\n\nAvoid alert overload — 50 alerts on one symbol creates noise. Curate watchlists to 10–20 instruments with 2–3 levels each maximum.",
        "chart_title": "Alert-driven workflow",
        "chart_caption": "Price reaches a pre-marked level, alert fires, trader opens chart and runs checklist. Most session time is preparation, not watching.",
        "example": "You mark Tesla: alert at $248.00 (daily 20 EMA pullback zone) and $255.50 (breakout trigger). You do not watch TSLA intraday. At 11:14 AM, $248 alert fires — you open chart, see 1H hammer at $247.80 with volume, run checklist (trend up, 2.3R available, session OK), enter $248.50, stop $246.20. Without alerts, you might have traded three mediocre mid-range setups earlier out of boredom.",
        "tip": "Name every alert with the setup type and checklist reminder — alerts are invitations to analyze, not commands to buy.",
        "bullets": [
            "Alerts trigger analysis at predefined levels — not impulsive watching",
            "Include setup context in alert notes for clarity when they fire",
            "No alert firing means no trade requirement — reduces overtrading",
            "Limit alerts per symbol to avoid notification fatigue",
            "When alert fires, run full checklist before entry — alert ≠ automatic trade",
        ],
        "takeaway": "Professionals wait for their price; amateurs watch every tick. Alerts are how you wait without missing your level.",
    },
    69: {
        "id": 69,
        "outcome": "You will screen markets efficiently for setups matching your strategy criteria, build focused watchlists, and spend analysis time only on qualified candidates.",
        "intro": "Screening is the funnel that finds needles in the haystack — instruments and conditions that match your edge — before you ever open a detailed chart.",
        "core": "Screeners filter universes by your strategy's measurable criteria: above 200-day MA, RSI between 40–60 in uptrend, ATR percentile, sector strength, earnings gap, or proximity to key level. Output is a short watchlist, not five hundred symbols.\n\nMatch screener logic to your written filters — if your strategy requires daily uptrend plus 4H pullback, screen for daily trend first, then monitor pullbacks on the shortlist manually or with secondary alerts.\n\nRefresh watchlists on a schedule — pre-market for day/swing traders, weekly for position traders. Stale lists cause trades on names that no longer qualify.\n\nScreening saves time but does not replace chart confirmation. A screener hit is a candidate, not an entry.",
        "chart_title": "Setup screening funnel",
        "chart_caption": "Universe of thousands filters to dozens via screener criteria, then to a handful via chart review and checklist.",
        "example": "Your swing long screener: US stocks, price $20–$200, avg volume > 1M, daily close above 50 and 200 EMA, within 3% of 20 EMA, RS vs SPY positive. Monday output: 14 names including Deere at $412.30, Starbucks at $92.15, and Caterpillar at $358.90. You set alerts on each at 20 EMA touch and deep-review only when alerts fire — down from scanning 3,000 symbols manually.",
        "tip": "Save screener settings with the exact same rules as your written strategy filters — divergence between screen and plan creates confusion.",
        "bullets": [
            "Screeners apply measurable strategy criteria to large universes",
            "Output is a focused watchlist — not an automatic buy list",
            "Align screener logic exactly with your written trade filters",
            "Refresh lists on a defined schedule — stale candidates waste time",
            "Chart confirmation and checklist still required after every screen hit",
        ],
        "takeaway": "Screening finds where to look; analysis decides whether to trade. Automate the search, not the judgment.",
    },
    70: {
        "id": 70,
        "outcome": "You will use a structured pre-trade checklist covering trend, setup, risk, and mental state so no trade executes unless all mandatory criteria pass.",
        "intro": "A trade checklist is the last gate before capital is risked — a physical or digital list that converts your plan into yes/no decisions under pressure.",
        "core": "Effective checklists cover four zones: market context (trend, regime, session), setup quality (A/B grade, confirmation present), risk math (stop logical, size calculated, R acceptable), and trader state (within daily limits, calm, no rule breaks today).\n\nEvery item is binary — checked or not. 'Mostly yes' is no. One unchecked mandatory item means pass, regardless of how good the chart looks.\n\nChecklists fight impulsive overrides. The act of reading each line slows the click and surfaces FOMO, revenge, or fatigue before they execute.\n\nCustomize to your strategy — a scalper's checklist differs from a swing trader's — but keep it short enough to use every time (8–12 items max). Unused checklists are decoration.",
        "chart_title": "Pre-trade checklist flow",
        "chart_caption": "Sequential yes/no checks on context, setup, risk, and state. All mandatory items must pass before entry is allowed.",
        "example": "Checklist before shorting GBP/USD at 1.2680: ✓ Daily downtrend (below 50 EMA), ✓ 4H rejection at 1.2695 resistance, ✓ Stop 1.2710 logical (+30 pips), ✓ Target 1.2610 = 2.3R, ✓ Size = $280 risk (0.7%), ✓ Trade 1 of 2 today, ✓ Emotional state 6/10, ✓ Confirmation candle closed. All pass — execute. Earlier, a USD/JPY setup failed 'daily trend aligned' — automatic pass despite tempting price action.",
        "tip": "Print your checklist and keep it visible — physical paper survives platform crashes and tab overload.",
        "bullets": [
            "Checklists convert strategy rules into binary pre-entry gates",
            "Cover context, setup quality, risk math, and trader mental state",
            "One failed mandatory item = no trade, no exceptions",
            "Keep lists short (8–12 items) so you actually use them every time",
            "Customize to your strategy — generic lists miss your edge requirements",
        ],
        "takeaway": "If it is not on the checklist, it is not part of your edge. Check every box or walk away.",
    },
    71: {
        "id": 71,
        "outcome": "You will conduct structured post-trade analysis on every closed trade, classify outcomes by process quality, and extract actionable lessons without rumination.",
        "intro": "Post-trade analysis closes the feedback loop — it turns each trade from a P&L blip into data that improves the next decision.",
        "core": "Immediately after closing, log: entry/exit prices, setup type, planned versus actual R, rule compliance (yes/no per rule), screenshot, and one sentence on what worked or failed. Delay loses detail — memory edits charts within hours.\n\nClassify trades: plan-compliant win, plan-compliant loss, rule-break win (dangerous — reinforces bad behavior), rule-break loss. Only the first two categories inform strategy edge; the last two inform psychology fixes.\n\nPost-trade analysis is not self-flagellation. A good loss — stop hit at planned level on valid setup — earns a green tag. A bad win — oversized FOMO chase that worked — earns a red tag despite profit.\n\nWeekly, aggregate post-trade tags for patterns: 'stopped out before target' may mean stops too tight; 'rule-break wins' may mean overconfidence growing.",
        "chart_title": "Post-trade review cycle",
        "chart_caption": "Log immediately after close, classify by process quality, aggregate weekly for pattern discovery.",
        "example": "Short oil at $79.20, stop $79.65, target $77.80. Stopped at $79.65 for -1R (-$450). Post-trade log: setup = range fade at $79.30 resistance, grade A, all rules followed, stop logical (above range high). Tag: good loss. Screenshot shows wick rejection was valid; breakout followed on news — acceptable outcome. Without analysis, you might 'widen stops next time' — wrong lesson. Correct lesson: setup was valid, variance happened.",
        "tip": "Set a 3-minute timer after every close — when it rings, logging must be done before opening another chart.",
        "bullets": [
            "Log every trade immediately with prices, R, rules, and screenshot",
            "Classify by process quality, not just profit or loss",
            "Good losses on valid setups are successful risk management",
            "Bad wins that break rules are warnings, not victories",
            "Weekly aggregation reveals patterns single trades hide",
        ],
        "takeaway": "Post-trade analysis asks 'did I execute the plan?' before 'did I make money?' — process first, P&L second.",
    },
    72: {
        "id": 72,
        "outcome": "You will track win rate correctly, interpret it alongside average R, and avoid optimizing for win rate alone at the expense of expectancy.",
        "intro": "Win rate is the percentage of trades that profit — useful context, but dangerously misleading without average win and loss size.",
        "core": "Win rate = winning trades / total trades. A 70% win rate sounds impressive until average losses are 3R and average wins are 0.5R — negative expectancy despite 'winning most of the time.'\n\nTrack win rate by setup type, session, and market regime in your journal. Aggregate headline win rate hides that you win 65% on pullbacks but 25% on breakouts — guiding where to focus.\n\nMinimum sample: 30 trades for rough direction, 100+ for confidence. Do not abandon a strategy after 8 losses if backtest win rate was 42% — streaks cluster.\n\nWin rate pairs with profit factor and expectancy. Report all three together: '44% win rate, 2.3R avg win, 1R avg loss, expectancy +0.5R' tells the truth; '44% win rate' alone does not.",
        "chart_title": "Win rate in context",
        "chart_caption": "Win rate alone misleads. Combined with average win and loss size, it reveals whether the strategy actually makes money.",
        "example": "Trader A: 68% win rate, avg win +0.6R, avg loss -1.2R over 100 trades. Expectancy = (0.68×0.6) − (0.32×1.2) = 0.408 − 0.384 = +0.024R — barely positive, fragile. Trader B: 40% win rate, avg win +2.8R, avg loss -1R. Expectancy = (0.40×2.8) − (0.60×1) = 1.12 − 0.60 = +0.52R — strong edge with lower win rate. Chasing Trader A's win rate would destroy Trader B's math.",
        "tip": "Calculate win rate separately for each setup tag in your journal — aggregate numbers often hide your best and worst patterns.",
        "bullets": [
            "Win rate = winners divided by total trades — context required",
            "High win rate with large losses can still mean negative expectancy",
            "Track win rate by setup type, session, and regime",
            "Require 30–100+ trades before drawing conclusions",
            "Always report win rate alongside average R and expectancy",
        ],
        "takeaway": "Win rate is one number in a equation — never optimize it alone. Expectancy is the score that matters.",
    },
    73: {
        "id": 73,
        "outcome": "You will calculate and track expectancy per trade and per strategy, use it to compare approaches, and make data-driven decisions about what to trade and what to cut.",
        "intro": "Expectancy is the average amount you expect to make or lose per trade over time — the single best number for whether your trading makes statistical sense.",
        "core": "Expectancy (in R) = (Win Rate × Average Win R) − (Loss Rate × Average Loss R). Positive expectancy means the strategy pays over enough trials; negative means you donate over time regardless of occasional big wins.\n\nTrack rolling expectancy over 20, 50, and 100 trade windows. Rising rolling expectancy suggests improvement or favorable regime; falling expectancy triggers edge review.\n\nConvert R expectancy to dollars: expectancy 0.5R at $250 risk = $125 expected per trade over the sample. Multiply by trades per month for rough income expectation — before taxes and before variance.\n\nCompare expectancy across strategies in your journal. Cut the sub-zero ones ruthlessly; double focus on the highest positive expectancy with sufficient sample.",
        "chart_title": "Expectancy tracking",
        "chart_caption": "Rolling expectancy over trade count shows whether your edge is stable, improving, or decaying.",
        "example": "Journal export: 80 trades, 46 wins, 34 losses. Avg win +2.1R, avg loss -0.95R (some moved to breakeven). Expectancy = (0.575 × 2.1) − (0.425 × 0.95) = 1.2075 − 0.40375 = +0.80375R. At $200 risk, ≈ $161 expected per trade. Monthly 12 trades ≈ $1,932 gross expectation — before a 6-trade losing streak wipes $1,200 and reminds you variance surrounds expectancy.",
        "tip": "Update expectancy monthly in a spreadsheet — one cell with the formula prevents you from guessing whether you are actually profitable.",
        "bullets": [
            "Expectancy = (Win% × Avg Win) − (Loss% × Avg Loss) in R",
            "Positive expectancy is required for long-term profitability",
            "Track rolling expectancy over 20/50/100 trade windows",
            "Convert R expectancy to dollars using your fixed risk per trade",
            "Compare expectancy across strategies to decide what to keep or cut",
        ],
        "takeaway": "If expectancy is negative, no mindset work fixes it — change the strategy or execution. If positive, protect it with discipline.",
    },
    74: {
        "id": 74,
        "outcome": "You will recognize common trading mistakes — revenge trading, moving stops, overtrading, no plan — map them to your journal, and apply targeted fixes.",
        "intro": "Most traders lose from repeated behavioral mistakes, not from one missing indicator. Naming the patterns is the first step to stopping them.",
        "core": "Classic mistakes: trading without a written plan; moving stops wider; cutting winners early and holding losers; overtrading out of boredom; revenge trading after losses; sizing up after wins; chasing FOMO moves; ignoring daily loss limits; confusing analysis with action.\n\nEach mistake has a signature in your journal — time of day, market condition, emotional tag. 'Rule break losses cluster on Wednesdays after 2 PM' is fixable with a session rule; vague 'I need discipline' is not.\n\nGood wins on bad process are among the most dangerous mistakes — they reinforce the behavior that will eventually blow the account.\n\nFix one mistake at a time with a specific rule: not 'be better' but 'no entries after 3 PM unless A-setup with alert.' Measure violation rate weekly.",
        "chart_title": "Common mistake patterns",
        "chart_caption": "Behavioral mistakes repeat in recognizable patterns. Journals expose them; specific rules fix them.",
        "example": "Review of 60 trades reveals: 18 rule-break trades, net -12R; 42 plan-compliant, net +8R. Rule breaks include 7 revenge entries after morning losses (net -9R), 5 FOMO chases (net -4R), 6 oversize trades (net +1R — lucky). Fix priority: hard stop after morning -2R eliminates revenge cluster. Next month rule breaks drop to 4, net -1R; compliant trades net +11R. Same edge, fewer self-inflicted wounds.",
        "tip": "Keep a 'mistake tally' column in your journal — counting violations makes invisible habits visible.",
        "bullets": [
            "Most underperformance comes from behavioral mistakes, not bad setups",
            "Common errors: no plan, stop moves, revenge, FOMO, overtrading",
            "Journal tags reveal when and why mistakes cluster",
            "Bad-process wins reinforce destructive habits",
            "Fix one mistake with one specific rule at a time",
        ],
        "takeaway": "You already know the mistakes — your journal proves which ones you still pay for. Fix those before hunting new setups.",
    },
    75: {
        "id": 75,
        "outcome": "You will run structured improvement loops — hypothesize, test, measure, adjust one variable at a time — so your trading evolves through evidence rather than random changes.",
        "intro": "Improvement loops turn trading from hope into iteration. Change one thing, measure the result, keep or discard — repeat for years.",
        "core": "An improvement loop has four steps: observe (journal data shows a problem), hypothesize (one specific change might help), test (apply change for defined sample — 20–30 trades minimum), measure (compare metrics to baseline), adopt or revert.\n\nChange one variable at a time. Adding a filter, new timeframe, and size change simultaneously makes attribution impossible. 'What helped?' becomes unanswerable.\n\nBaseline metrics before change: win rate, avg R, expectancy, rule compliance, max DD. After sample, compare honestly — not cherry-picking the best three trades.\n\nImprovement targets process first (compliance, fewer mistakes), then strategy filters, then sizing. Jumping to new strategies before fixing execution repeats the same failure on a fresh chart.",
        "chart_title": "Improvement loop cycle",
        "chart_caption": "Observe journal data, change one rule, test over sufficient sample, measure against baseline, adopt or revert — then loop again.",
        "example": "Baseline 40 trades: expectancy +0.3R, 12 stop-outs tagged 'stopped before target reached.' Hypothesis: move to breakeven at +1R instead of +0.5R reduces premature stop-outs. Test next 35 trades with single change. Result: stop-outs before target drop from 30% to 18%, avg win rises 1.9R to 2.2R, expectancy +0.52R. Adopt rule. Next loop: test ADX filter on breakout subset — one variable only.",
        "tip": "Write the hypothesis and success criteria before the test trades — deciding after results invites hindsight bias.",
        "bullets": [
            "Improvement loop: observe, hypothesize, test, measure, adopt or revert",
            "Change one variable per loop — otherwise you cannot know what worked",
            "Require 20–30+ trades minimum per test for rough signal",
            "Fix process and compliance before chasing new strategies",
            "Define success metrics before testing, not after results arrive",
        ],
        "takeaway": "Trading mastery is thousands of small loops, not one breakthrough. Iterate with data, one change at a time, for as long as you trade.",
    },
})
