# Part 1: lessons 1-25
LESSON_CONTENT = {
    1: {
        "id": 1,
        "outcome": "You will understand how buyers and sellers interact to set price, why markets exist, and how supply and demand create every move you see on a chart. You will also learn to identify which side is temporarily in control.",
        "intro": "Every price tick is the result of a negotiation between buyers and sellers. A market is not merely an exchange screen — it is a continuous auction where participants decide what an asset is worth right now.",
        "core": "When more participants want to buy than sell, price rises because buyers must bid higher to find willing sellers. When sellers overwhelm buyers, price falls. This imbalance — not magic indicators — drives every trend, breakout, and reversal.\n\nMarkets exist because people hold different views on value and operate on different time horizons. A pension fund may sell into strength while a day trader buys the same breakout; both can be rational for their goals. Your edge begins when you read who controls price in your timeframe.\n\nLiquidity — the ease of buying or selling without moving price — shapes how fast balance shifts. Thin markets gap; deep markets absorb orders smoothly. Recognizing liquidity conditions helps you avoid trading size into a vacuum.\n\nAs a trader, your job is not to forecast the economy but to interpret the auction in real time: where is demand absorbing supply, and where is supply overwhelming demand?",
        "chart_title": "Supply and demand balance",
        "chart_caption": "When buying pressure exceeds selling pressure, price rises. When selling dominates, price falls. The equilibrium shifts constantly throughout each session.",
        "example": "BTC/USDT trades at $42,000 in a balanced range on Binance. After a positive ETF headline, aggressive buyers lift offers to $42,800, then $43,500 as resting sell orders get filled. Traders who recognized the shift from balance to buyer control entered near $43,100 with a stop below $42,600. Those who waited for 'confirmation' at $44,200 bought into thinner liquidity and gave back gains on the first 4H pullback.",
        "tip": "Before every trade, ask: who is in control right now — buyers or sellers? If you cannot answer clearly on your chart timeframe, wait.",
        "bullets": [
            "Markets are auctions — price is where supply meets demand",
            "Aggressive buying lifts price; aggressive selling pushes it down",
            "Liquidity depth determines how violently balance can shift",
            "News and events change the balance suddenly — plan for gaps",
            "Your timeframe defines which auction you are actually trading",
        ],
        "takeaway": "Price is not random — it reflects the real-time balance between buyers and sellers. Read that balance and you have the foundation for everything else.",
    },
    2: {
        "id": 2,
        "outcome": "You will learn how transaction data becomes a visual chart, why traders rely on charts, and how to read timeframe, scale, and basic price structure at a glance.",
        "intro": "A chart transforms thousands of trades into a visual record of behavior over time. Instead of scanning tables of numbers, you see trends, ranges, and reaction levels in seconds.",
        "core": "Every chart plots price against time. The horizontal axis marks when activity occurred; the vertical axis marks at what price. From this layout you immediately see whether an asset trends up, down, or sideways — and how quickly.\n\nCharts do not predict the future; they document what participants actually paid. That history is your starting context: prior highs act as memory zones where sellers previously appeared; prior lows mark where buyers stepped in.\n\nTimeframe selection changes the story. A 5-minute chart may show a breakout while the daily chart still sits inside a multi-week range. Always know which timeframe defines your bias and which refines your entry.\n\nLine, bar, and candlestick formats display the same underlying data differently. Candlesticks add open-close psychology; bars emphasize highs and lows; line charts smooth noise by connecting closes.",
        "chart_title": "Price chart example",
        "chart_caption": "A line chart connects closing prices across periods. Each point represents one bar — minute, hour, or day depending on your selected timeframe.",
        "example": "You open BTC/USDT on the daily chart on TradingView. Price climbed from $38,000 to $44,500 over three weeks with shallow pullbacks. Without indicators you already see an uptrend, a recent swing high near $44,800 as resistance, and prior pullback lows near $41,200 as support. The chart gave actionable context before you placed a single tool on screen.",
        "tip": "Master plain price on one timeframe before stacking indicators — most indicators are derivatives of what the chart already shows.",
        "bullets": [
            "Charts record historical transactions — they describe the past, not guarantee the future",
            "Always check the timeframe label before interpreting any pattern",
            "Higher timeframes show context; lower timeframes refine entries",
            "Line, bar, and candlestick charts display the same data differently",
            "Mark obvious swing highs and lows before adding complexity",
        ],
        "takeaway": "A chart is your most honest window into market behavior. Learn to read it clearly before you risk capital.",
    },
    3: {
        "id": 3,
        "outcome": "You will master candlestick anatomy — open, high, low, close — and interpret what each candle reveals about buyer and seller behavior within one period.",
        "intro": "Candlestick charts dominate modern trading because each candle compresses four prices into one shape that exposes sentiment at a glance.",
        "core": "Every candle represents one period — one minute, one hour, one day. It contains four prices: open (start), close (end), high (peak), and low (trough). The body spans open to close; wicks extend to the extremes.\n\nIf close is above open, the candle is bullish (typically green): buyers controlled the period. If close is below open, the candle is bearish (red): sellers controlled it. Body size reflects conviction; small bodies signal indecision.\n\nUpper wicks show rejection from higher prices — buyers tried to push up but sellers responded. Lower wicks show rejection from lower prices — sellers drove price down but buyers absorbed supply. Long wicks at key levels often mark turning points.\n\nSingle candles mean little in isolation. Read them in sequence: a bullish engulfing after a downtrend differs completely from the same pattern mid-range in chop.",
        "chart_title": "Candlestick chart",
        "chart_caption": "Each candle summarizes one period. Green bodies close above open; red bodies close below. Wicks show how far price traveled before settling.",
        "example": "On a 1-hour ETH/USDT chart, price tests $2,450 support on Binance. The next candle prints a small body near the top with a long lower wick to $2,380 and minimal upper wick — a hammer. Sellers pushed down hard, but buyers absorbed the flow and closed near the open. Combined with support, this rejection hints at a long entry with stop below $2,370.",
        "tip": "Context beats pattern names — one hammer at support matters; the same shape in chop is noise.",
        "bullets": [
            "Body size shows conviction; doji bodies signal indecision",
            "Long upper wicks mean rejection from higher prices",
            "Long lower wicks mean rejection from lower prices",
            "Read the last 3–5 candles together, not in isolation",
            "Color convention varies by platform — know yours",
        ],
        "takeaway": "Each candle is a snapshot of a battle. Read the body for who won, the wicks for where they fought, and the sequence for trend context.",
    },
    4: {
        "id": 4,
        "outcome": "You will identify uptrends, downtrends, and sideways markets using swing structure, and understand why trading with trend generally offers higher probability.",
        "intro": "Trend is the path of least resistance on your chart. Recognizing it early keeps you aligned with dominant force instead of fighting it.",
        "core": "An uptrend forms when price produces higher highs and higher lows — each pullback stops above the prior low and each rally exceeds the prior peak. A downtrend is the mirror: lower highs and lower lows.\n\nSideways markets lack clear progression; price oscillates between defined boundaries. Many losses come from applying trend tactics in ranges or range tactics in strong trends.\n\nTrend exists on every timeframe simultaneously. The 15-minute chart may uptrend while the daily chart downtrends. Conflicts create chop or sharp reversals — know which timeframe sets your directional bias.\n\nTrend following does not mean buying blindly at any price. It means preferring long setups in uptrends and short setups in downtrends, and reducing size or standing aside when structure breaks.",
        "chart_title": "Identifying an uptrend",
        "chart_caption": "Connect swing lows in an uptrend and swing highs in a downtrend. Structure breaks — such as a lower low in an uptrend — signal potential trend change.",
        "example": "SOL/USDT on the 4-hour chart rallies from $95 to $128 with pullbacks holding above $102, $108, and $115. Each low is higher than the last. You plan long entries on pullbacks toward $118 support rather than shorting new highs, aligning with structure until a lower low prints below $115.",
        "tip": "Mark the last two swing highs and swing lows — if you cannot draw a clear trend, the market may be ranging.",
        "bullets": [
            "Uptrend: higher highs and higher lows",
            "Downtrend: lower highs and lower lows",
            "Sideways: overlapping swings without clear progression",
            "Trend direction depends on the timeframe you trade",
            "Structure breaks are early warnings, not instant reversals",
        ],
        "takeaway": "Trade with the trend on your chosen timeframe until structure proves otherwise. Fighting dominant flow is an expensive habit.",
    },
    5: {
        "id": 5,
        "outcome": "You will define support and resistance, mark them on charts, and understand why price reacts at prior decision zones.",
        "intro": "Support and resistance are the memory of the market — levels where buyers or sellers previously took control and may do so again.",
        "core": "Support is a price zone where buying interest historically absorbed selling pressure, causing price to bounce. Resistance is where selling overwhelmed buyers, causing price to stall or reverse.\n\nThese levels are zones, not laser lines. Markets are messy; expect wicks to pierce levels briefly before acceptance or rejection. The more times a level is tested without breaking, the more attention it attracts — but also the more orders may stack there, leading eventually to breakouts.\n\nPrior swing highs become resistance on retests; prior swing lows become support. Round numbers ($100, 1.1000) and weekly/monthly highs/lows often act as magnets because many participants anchor orders there.\n\nWhen price breaks through resistance with acceptance — closes beyond the level on meaningful volume — that zone often flips to support (role reversal). Failed breaks create traps for breakout traders.",
        "chart_title": "Support and resistance zones",
        "chart_caption": "Horizontal zones mark areas where price repeatedly reversed. Watch for bounces, breaks, and role reversals after acceptance beyond a level.",
        "example": "BNB/USDT stalls three times near $320 before finally closing above $325 on heavy Binance volume. The old resistance near $320 becomes support on the next pullback. You watch for a hold above $318 on the retest to join the continuation long with stop below $312.",
        "tip": "Draw zones, not single-pixel lines — give price room to breathe while keeping invalidation clear.",
        "bullets": [
            "Support = historical buying interest; resistance = historical selling interest",
            "Levels are zones; wicks often poke through before resolution",
            "Repeated tests strengthen attention but can weaken the level over time",
            "Broken resistance often becomes support after acceptance",
            "Combine structure levels with trend direction for better context",
        ],
        "takeaway": "Mark where price changed direction before — those zones remain battlegrounds until the market decisively moves on.",
    },
}
