# Part 5: lessons 76-100
from _lesson_data_part4 import LESSON_CONTENT

LESSON_CONTENT.update({
    76: {
        "id": 76,
        "outcome": "You will synthesize trend, volatility, session, and recent price behavior into a single market context read before every trade — and adjust expectations when context conflicts with your setup.",
        "intro": "A setup without context is a coin flip with better graphics. Market context is the environmental layer that tells you whether your edge is likely active today or dormant.",
        "core": "Market context combines four lenses: trend direction on your decision timeframe and one level above, volatility regime (compressed, normal, or expanded), session characteristics (Asia quiet, London transitional, New York active), and recent behavior (range, impulse, news-driven gap, or post-event drift).\n\nThe same bullish rejection candle means different things in an uptrend during London overlap versus a choppy Asia session inside a weekly range. Context does not replace your setup rules — it filters when those rules deserve full size, reduced size, or no trade at all.\n\nBuild a pre-trade context checklist: What is the higher-timeframe bias? Is volatility expanding or contracting? Which session am I in? Did recent price action respect or violate key levels? Score context as favorable, neutral, or hostile before clicking.\n\nAdvanced traders spend more time reading context than hunting entries. When context is hostile — low liquidity holiday, major news in ten minutes, conflicting higher-timeframe structure — the highest-EV decision is often no decision.",
        "chart_title": "Market context layers",
        "chart_caption": "Trend, volatility, session, and recent structure stack into one read. A valid setup in hostile context deserves caution or pass.",
        "example": "Your strategy buys pullbacks in daily uptrends. EUR/USD daily trends up, but the 4-hour chart shows overlapping swings inside 1.0850–1.0920 for five days with ATR at a two-week low during Tokyo session. Context score: trend favorable, volatility compressed, session quiet, recent behavior ranging. You downgrade from full size to half size or wait for London open expansion before entering — the setup may fire, but context says edge is thin.",
        "tip": "Write a one-line context summary before every trade — if you cannot describe the environment in ten words, you have not read it yet.",
        "bullets": [
            "Context = trend + volatility + session + recent behavior",
            "Same setup carries different odds in different environments",
            "Use a pre-trade context checklist every session",
            "Hostile context favors pass or reduced size, not forced entries",
            "Higher-timeframe bias filters lower-timeframe signals",
        ],
        "takeaway": "Context changes how you interpret every signal. Read the environment first, then decide whether your setup deserves action.",
    },
    77: {
        "id": 77,
        "outcome": "You will recognize false confidence after winning streaks, distinguish process success from random variance, and maintain sizing and discipline when results feel easy.",
        "intro": "Nothing erodes risk discipline faster than a hot streak. False confidence is the quiet belief that you have suddenly become invincible — when variance just smiled on you.",
        "core": "False confidence appears after consecutive wins, oversized gains on marginal setups, or a strategy performing above its historical average for a short window. You start skipping checklists, widening size, trading lower-grade setups, and interpreting every wick as confirmation.\n\nWinning streaks are statistically normal in any positive-expectancy system. Flip a slightly biased coin fifty times and you will see runs of heads. Those runs do not mean the coin changed — your process did not either unless you changed it.\n\nCountermeasures are mechanical: fixed maximum risk regardless of recent P&L, mandatory checklist even when 'obvious,' streak alerts that trigger review not celebration, and comparing live results to backtest bands (if win rate jumps 15 points above baseline, suspect variance).\n\nTrue confidence is quiet and evidence-based — it survives losses because it rests on sample size, not yesterday's P&L. False confidence is loud and fragile — it shatters on the first normal loss after a streak.",
        "chart_title": "Variance versus skill",
        "chart_caption": "Winning streaks occur naturally in probabilistic systems. Discipline means treating streaks as data, not proof of mastery.",
        "example": "After eight winners in twelve trades, you feel sharp and double size on a B-grade breakout without volume confirmation. It fails for -2R while a normal -1R would have been manageable. Your journal shows the setup failed checklist on two items you ignored because 'everything has been working.' False confidence turned variance into damage.",
        "tip": "After three consecutive wins, run your checklist twice — streaks are when rules matter most, not least.",
        "bullets": [
            "False confidence follows short-term outperformance, not process change",
            "Winning streaks are normal in positive-expectancy systems",
            "Keep size fixed regardless of recent results",
            "Compare live stats to backtest baselines to detect variance spikes",
            "True confidence survives losses; false confidence needs constant wins",
        ],
        "takeaway": "A hot streak proves your system can win — not that you should abandon the system that produced it.",
    },
    78: {
        "id": 78,
        "outcome": "You will scale strategy size and frequency only after statistical and behavioral proof of stability — and define clear criteria for when scaling is justified versus premature.",
        "intro": "Scaling is not about ambition — it is about evidence. Growing before your process is stable magnifies every leak in your system.",
        "core": "Scaling a strategy means increasing position size, adding correlated instruments, or trading more frequently. Each dimension adds risk. Size scaling affects slippage and emotional response; frequency scaling increases decision load and correlation exposure.\n\nPrerequisites for scaling: minimum sample size (often 50–100 live trades matching backtest), drawdown within expected bands, rule compliance above 90%, and stable execution metrics (slippage, fill quality). If any pillar wobbles, fix before growing.\n\nScale in steps — 25% size increases after each validated block of trades, not doubling overnight. Paper-trade or micro-size new instruments before full allocation. Track whether edge degrades at larger size (market impact, emotional interference).\n\nScaling frequency is often more dangerous than scaling size. More trades mean more decisions, more fatigue, more overlap. Add setups only when current ones are fully automated in your routine.",
        "chart_title": "Scaling readiness gates",
        "chart_caption": "Increase size or frequency only after sample size, drawdown, and discipline metrics pass defined thresholds.",
        "example": "Your pullback strategy shows 52% win rate and 1.8 profit factor over 80 live trades with max 12% drawdown. Plan allows 25% size increase. You bump risk from 1% to 1.25% and trade another 40 trades before next review. A peer with 15 trades and 80% win rate doubles size — next regime shift produces -20% DD they cannot psychologically handle.",
        "tip": "Define scaling rules in writing while account is flat — never decide growth size after a winning week.",
        "bullets": [
            "Scale only after sufficient live sample and stable metrics",
            "Increase size in small steps, not dramatic jumps",
            "Rule compliance and drawdown bands gate growth decisions",
            "Frequency scaling adds decision load — grow setups slowly",
            "Monitor whether edge degrades at larger size or more trades",
        ],
        "takeaway": "Growth should follow evidence, not excitement. Scale when the process is boringly consistent, not when results feel easy.",
    },
    79: {
        "id": 79,
        "outcome": "You will adapt tactics to changing market regimes while keeping core risk rules intact — and distinguish productive flexibility from undisciplined strategy hopping.",
        "intro": "Markets evolve. Rigid traders break when conditions shift; undisciplined traders chase every new pattern. Adaptive thinking sits between — flexible tactics, immovable risk.",
        "core": "Adaptive thinking means recognizing when your environment changed — trend to range, low vol to high vol, correlated risk-on to dispersion — and adjusting which playbook is active without abandoning position sizing, stop rules, or daily loss limits.\n\nProductive adaptation: disable breakout trades during compression; switch from mean reversion to trend following after structure break; reduce size when ATR doubles; stand aside during major event weeks. These are pre-defined regime responses written into your plan.\n\nDestructive adaptation: abandoning a strategy after ten losses without sample review, adding indicators mid-drawdown, copying social media setups, or rewriting rules trade-by-trade. That is reactive noise, not adaptation.\n\nBuild a regime map with IF-THEN rules: IF weekly ATR percentile > 80 AND structure is ranging, THEN mean reversion only at boundaries with half size. IF daily trend breaks with acceptance, THEN disable fade setups for five sessions. Adaptation is planned, not improvised.",
        "chart_title": "Regime-based playbook switching",
        "chart_caption": "Different market environments activate different tactical modules. Core risk rules remain constant across all regimes.",
        "example": "Your plan includes trend pullbacks and range fades. Nasdaq shifts from trending to three-week balance with declining volume. Your regime filter flags 'range.' You disable pullback longs mid-range and only fade extremes at boundaries with tighter targets. When price accepts above range high on volume, you re-enable trend module. Risk per trade never changed — only active tactics did.",
        "tip": "Pre-write two alternate playbooks for trending and ranging markets — decide switches on criteria, not feelings.",
        "bullets": [
            "Adapt tactics to regime; never adapt core risk rules away",
            "Productive adaptation uses pre-defined IF-THEN regime rules",
            "Strategy hopping after short losses is not adaptation",
            "Disable modules when environment invalidates their edge",
            "Re-enable tactics only when objective criteria confirm regime shift",
        ],
        "takeaway": "Flexibility is a skill — change how you hunt when the terrain changes, but never change how much you risk without evidence.",
    },
    80: {
        "id": 80,
        "outcome": "You will design a multi-year progression path with skill milestones, capital phases, and review cadences — treating trading as a craft built incrementally, not a lottery ticket.",
        "intro": "Overnight success in trading is a myth told by survivors. Long-term progression is deliberate skill stacking across years, not weeks.",
        "core": "Trading progress follows phases: learning mechanics (charts, risk math), sim and small-size execution, strategy validation with minimum sample, scaling with discipline, and ongoing refinement. Skipping phases creates hidden debt — you 'succeed' until size or regime exposes gaps.\n\nDefine milestones: Month 1–3 master risk sizing and journaling; Month 4–6 complete 100 sim trades at 90%+ rule compliance; Month 7–12 live micro-size with same compliance target; Year 2 evaluate expectancy over 200+ trades before meaningful scale. Adjust timelines to your schedule, but keep sequence.\n\nCapital phases matter: learning capital (money you can lose without lifestyle impact), validation capital (small live proving ground), and growth capital (added only after metrics confirm). Never merge learning and rent money.\n\nReview cadence scales with experience: daily process notes, weekly stats, monthly strategy review, quarterly plan revision, annual goal reset. Progress is measured in compliance and sample quality, not single-month P&L.",
        "chart_title": "Long-term skill progression",
        "chart_caption": "Competence builds through phased milestones — mechanics, validation, live proof, scale. Each phase has exit criteria before the next begins.",
        "example": "Year one goal: 150 live trades at 0.5% risk, 85%+ checklist compliance, journal complete. You hit 162 trades, 88% compliance, break-even P&L after costs. Year two plan: maintain compliance, increase to 0.75% risk after 50 more trades if DD stays under 15%. A friend skips to 2% risk after two profitable months and blows validation phase in one week.",
        "tip": "Set one skill milestone per quarter — mastering one behavior beats chasing ten indicators per month.",
        "bullets": [
            "Progress follows phases: learn, sim, validate live, then scale",
            "Define capital phases separate from lifestyle money",
            "Milestones measure compliance and sample size, not one month's P&L",
            "Skipping phases creates hidden skill debt",
            "Review daily process, weekly stats, monthly strategy, quarterly plan",
        ],
        "takeaway": "Think in years, act in sessions. Small improvements compounded with discipline outperform heroic shortcuts every time.",
    },
    81: {
        "id": 81,
        "outcome": "You will map volatility patterns across Asia, London, and New York sessions — and match strategy type, size, and expectations to each session's typical behavior.",
        "intro": "The clock matters as much as the chart. Session volatility determines how far price moves, how often setups trigger, and how wide your stops must be.",
        "core": "Major markets rotate through Asia (often lower volatility, range development), London (volume influx, trend initiation, false breaks), and New York (continuation or reversal of London, macro data spikes). Overlap periods — London/New York — typically carry highest volume and range expansion.\n\nSession volatility affects strategy fit: scalps and tight-stop breakouts suit high-liquidity overlaps; swing entries from daily levels tolerate quieter sessions; mean reversion often works in Asia ranges that London later breaks.\n\nTrack average range per session for your instrument. If London averages 40 pips and Asia 15, expecting London-style moves at Tokyo lunch sets wrong targets and stops. Adjust ATR-based stops and profit targets by session multiplier.\n\nDay-of-week patterns add nuance — Monday gaps and Friday position squaring behave differently. Build a session playbook: which setups are allowed when, and which are banned (e.g., no tight breakout trades first five minutes of cash equity open).",
        "chart_title": "Session volatility timeline",
        "chart_caption": "Volatility and volume typically rise through London and New York overlaps. Match strategy aggression to session character.",
        "example": "You trade GBP/USD breakout retests. Backtest shows 62% win rate during London–NY overlap but 38% during Asia. Plan update: full size on overlap breaks with acceptance; no breakout entries Asia session — only watchlist prep. First month after change: fewer trades, higher average R, lower frustration from false breaks in thin hours.",
        "tip": "Log session tag on every journal entry for thirty trades — your edge may cluster in hours you did not expect.",
        "bullets": [
            "Asia, London, and New York carry distinct volatility profiles",
            "Overlap sessions usually offer highest volume and range",
            "Adjust stops and targets to session-average range",
            "Ban strategies that backtest poorly in specific sessions",
            "Day-of-week effects modify session expectations further",
        ],
        "takeaway": "Different sessions need different expectations. Trade the right tactic in the right hour — not every setup belongs in every session.",
    },
    82: {
        "id": 82,
        "outcome": "You will read opening auction dynamics, distinguish genuine opening drive from opening trap, and apply rules for when to engage versus observe the first minutes of a session.",
        "intro": "The open is where overnight information meets fresh liquidity. It can launch trends or trap traders who confuse speed for direction.",
        "core": "Market open behavior — whether equity cash open, FX London fix, or futures pit open — concentrates orders, gaps, and emotional reactions into minutes. Opening range often sets the day's initial balance; breaks of opening range can trend; failures revert toward range mid.\n\nOpening drives show directional acceptance: consecutive strong closes beyond opening range with volume. Opening traps spike beyond prior high/low, reverse quickly, and close back inside range — hunting stops from overnight participants and pre-market breakout orders.\n\nRules for engagement: wait for opening range to form (often 5–15 minutes for equities, first hour bar for some futures); require acceptance beyond range, not wick only; reduce size on open trades until pattern confirms; never chase first candle without invalidation defined.\n\nGap opens add complexity: gap-and-go continues direction; gap-fill reverts toward prior close. Classify gap size relative to ATR — small gaps fill more often; large news gaps may not fill for days.",
        "chart_title": "Opening range behavior",
        "chart_caption": "The opening range often defines early balance. Acceptance beyond it suggests drive; rejection back inside suggests trap.",
        "example": "S&P futures gap up 0.8% on CPI beat. First five minutes push higher, then a 5-min candle closes back below opening range high with long upper wick. You skip long breakouts and watch for fade toward opening range mid. Price reverses 12 points — traders who bought the initial spike without acceptance gave back gains.",
        "tip": "Mark opening range high and low before taking direction — if you cannot see the range, you cannot see the trap.",
        "bullets": [
            "Open concentrates orders, gaps, and volatility into minutes",
            "Wait for opening range formation before directional bets",
            "Acceptance beyond range differs from wick-only spikes",
            "Reduce size on open trades; traps are common",
            "Classify gaps by size relative to ATR for bias",
        ],
        "takeaway": "Open behavior can be unpredictable. Observe first, define the range, then decide — speed at the open is not edge by itself.",
    },
    83: {
        "id": 83,
        "outcome": "You will prepare for scheduled and unscheduled news events, adjust exposure around high-impact releases, and read post-news price action without gambling on headlines.",
        "intro": "News can override the cleanest technical setup in seconds. Advanced traders do not predict headlines — they manage exposure around them.",
        "core": "News impact operates on three channels: surprise relative to expectations (actual vs forecast), liquidity withdrawal before release (wider spreads, thin books), and post-release repricing as algorithms and humans digest details.\n\nScheduled events — CPI, FOMC, NFP, earnings — belong on your calendar with impact ratings. Default rules: flat or reduced exposure into red-folder events unless your strategy explicitly trades post-release structure; widen expected slippage on stops; no new entries five minutes before major releases.\n\nPost-news trading favors structure over prediction: wait for initial spike, identify acceptance or rejection, trade retest of broken level or fade of failed extension with defined risk. First move is often noise; second move reveals positioning.\n\nUnscheduled headlines — geopolitical shocks, CEO resignations — require instant risk audit: what open exposure do I have, where are stops, can I reduce size immediately? Pre-defined 'headline protocol' beats improvisation.",
        "chart_title": "News release price reaction",
        "chart_caption": "Major releases often produce spike, pause, then directional resolution. Trading structure after the spike beats guessing direction before it.",
        "example": "FOMC at 2:00 PM. You flatten EUR/USD long into event per plan. Post-release spike to 1.0950 reverses to 1.0880 within twenty minutes — classic whipsaw. You wait for 1-hour close below pre-release consolidation at 1.0890 and short retest at 1.0895 with stop above spike high. Direction came from structure after chaos, not from predicting the statement.",
        "tip": "Maintain a red-folder calendar synced to your trading timezone — surprise is often just poor scheduling on your part.",
        "bullets": [
            "News impact = surprise, liquidity shift, and repricing speed",
            "Reduce or flatten exposure before high-impact scheduled events",
            "Post-news structure trades beat pre-news direction guesses",
            "First spike is often noise; wait for acceptance or rejection",
            "Maintain headline protocol for unscheduled shock events",
        ],
        "takeaway": "News can override technical setups. Manage exposure around events and trade structure after the release — not hope before it.",
    },
    84: {
        "id": 84,
        "outcome": "You will measure correlation between positions, avoid hidden concentration risk, and use correlation awareness to size and diversify intentionally.",
        "intro": "Two trades can look different while betting the same outcome. Correlation reveals hidden overlap that doubles risk when you thought you diversified.",
        "core": "Correlation measures how two instruments move together — +1 means lockstep, -1 means inverse, 0 means independent. Risk-on days lift equities, oil, and AUD together; flight-to-quality lifts USD and bonds while crushing stocks.\n\nHidden overlap example: long NASDAQ, long EUR/USD, long BTC — three symbols, one risk-on bet. A single macro shock hits all three. Portfolio heat maps expose this; single-trade thinking hides it.\n\nUse correlation pragmatically: before adding a position, ask if it increases net exposure to a theme (dollar strength, tech momentum, energy supply). Reduce size on correlated adds or choose hedging positions with negative correlation when intentional.\n\nCorrelation is unstable — it rises in crises when diversification fails most. Static correlation matrices help planning; live stress awareness helps survival. During panic, most risk assets correlate toward +1.",
        "chart_title": "Correlated market movement",
        "chart_caption": "Related instruments often move together during macro shifts. Multiple positions may express one underlying bet.",
        "example": "You hold long ES, long NQ, and long semiconductor ETF — correlation above 0.85 on rolling twenty-day window. A hawkish Fed comment hits all three for -1R each simultaneously — effective loss -3R on one macro view. Plan update: max one equity index directional bet unless hedged; rotate expressions instead of stacking.",
        "tip": "Before every new trade, name the macro theme it expresses — if it matches an open position, you are adding size, not diversifying.",
        "bullets": [
            "Correlation reveals whether trades express the same underlying bet",
            "Risk-on and risk-off regimes cluster movement across assets",
            "Check overlap before adding positions, not after losses",
            "Reduce size on correlated adds or choose intentional hedges",
            "Correlations spike toward +1 in crises — plan for convergence",
        ],
        "takeaway": "Correlated trades multiply exposure. See the portfolio as one risk picture, not isolated tickets.",
    },
    85: {
        "id": 85,
        "outcome": "You will evaluate total account exposure across open positions, set portfolio-level risk caps, and balance opportunity against concentration limits.",
        "intro": "One trade at a time is how beginners think. Portfolio thinking is how survivors stay solvent when five positions move together.",
        "core": "Portfolio thinking aggregates: total open risk as percentage of equity, sector or theme concentration, correlation-adjusted exposure, and available dry powder for new A-setups. Single-trade risk of 1% times five correlated trades is not 1% — it may be 3–4% effective.\n\nSet portfolio rules: maximum simultaneous open risk (e.g., 3% total), maximum positions per theme, maximum daily new risk added, and circuit breaker when portfolio heat exceeds threshold regardless of individual trade quality.\n\nOpportunity cost matters: full portfolio heat means passing new A-setups or closing weaker positions to free risk budget. Ranking open trades by setup grade and unrealized R helps decide what to cut when capital is tied up.\n\nPortfolio thinking also spans time — stagger entries to avoid loading all risk into one session or news window. Spread decision points to reduce single-moment failure.",
        "chart_title": "Portfolio risk aggregation",
        "chart_caption": "Individual trade risk sums into portfolio heat. Correlation adjusts effective exposure beyond simple addition.",
        "example": "Account $100,000, rule max 3% portfolio heat. You hold three trades risking 1% each — ES long, crude long, AUD long — all risk-on correlated. Effective heat ~2.6% after correlation adjustment. Fourth A-setup appears also risk-on. You pass or close weakest trade (-0.3R floating) to stay under cap rather than stack fourth correlated bet.",
        "tip": "Track 'portfolio heat' in your journal header daily — a number beats gut feel when deciding whether to add risk.",
        "bullets": [
            "Portfolio heat = sum of open risk adjusted for correlation",
            "Set max simultaneous exposure and theme concentration limits",
            "Full heat means pass new setups or close weaker positions",
            "Stagger entries across time to avoid single-moment overload",
            "Rank open trades when risk budget is constrained",
        ],
        "takeaway": "A group of trades is one risk picture. Manage the portfolio, not just the last setup you saw.",
    },
    86: {
        "id": 86,
        "outcome": "You will document and execute a daily repeatable process — from pre-market prep through post-session review — that reduces randomness and makes improvement measurable.",
        "intro": "Edge without process is luck with amnesia. A repeatable process turns scattered good decisions into a system you can audit, teach, and improve.",
        "core": "A repeatable process spans: pre-market (calendar, levels, watchlist, context read), pre-trade (checklist, size calc, invalidation), execution (entry protocol, no impulsive adds), management (stop/target rules, no discretionary widening), and post-trade (journal within five minutes, end-of-day summary).\n\nRepeatability means same steps in same order every session — not same outcomes. Outcomes vary; process compliance is your control variable. Track compliance percentage weekly; target 90%+ before scaling size.\n\nProcess documentation lives in one place: written plan, checklist printout or app, journal template. Version it — date every revision so you know which rules produced which sample.\n\nWhen results disappoint, diagnose process first: Did I skip steps? Did I trade outside hours? Did I violate size rules? Fix process before rewriting strategy.",
        "chart_title": "Daily trading process loop",
        "chart_caption": "Prep, execute, journal, review — the same loop every session. Consistency of steps creates consistency of improvement.",
        "example": "Your written process: 7:00 AM mark levels on six instruments; 8:00 AM context score; trade only 9:30–11:30 with checklist; journal each trade before next entry; 4:00 PM daily summary. Month review shows 92% process compliance on winning weeks, 71% on losing weeks — losses correlated with skipped prep, not mysterious market change.",
        "tip": "Time-block each process step on your calendar — if prep is not scheduled, it will not happen consistently.",
        "bullets": [
            "Process spans prep, checklist, execution, management, and review",
            "Track compliance percentage — it is your primary control variable",
            "Document and version your process in one accessible place",
            "Diagnose process breaks before blaming strategy or market",
            "Same steps daily; outcomes will still vary probabilistically",
        ],
        "takeaway": "Repeatability creates consistency. Follow the same process every session and improvement becomes measurable instead of mythical.",
    },
    87: {
        "id": 87,
        "outcome": "You will recognize decision fatigue before quality degrades, reduce unnecessary choices through defaults and rules, and structure your session to preserve judgment for high-stakes moments.",
        "intro": "Every discretionary choice spends mental fuel. By afternoon, the same trader who passed a B-setup at 9 AM clicks into a mediocre trade at 2 PM — not because the market changed, but because the brain is tired.",
        "core": "Decision fatigue accumulates from: scanning too many instruments, debating marginal setups, adjusting indicators live, managing too many open positions, and context-switching between strategies. Quality of judgment declines even when willpower feels intact.\n\nReduction strategies: fixed watchlist size (five symbols, not fifty), default 'no' for trades failing any checklist item, automated alerts instead of constant watching, pre-decided session windows, and meal or walk breaks before second trading block.\n\nBatch decisions: mark all levels once pre-market; size formula in spreadsheet; exit rules predefined. Reserve discretion for A-setup timing, not daily reinvention of basics.\n\nTrack error rate by time of day in journal. If rule violations cluster after 1 PM, shorten session or add mandatory break. Protecting focus is a performance edge, not laziness.",
        "chart_title": "Decision quality over session",
        "chart_caption": "Judgment often degrades as choices accumulate. Fewer decisions and structured breaks preserve quality for key moments.",
        "example": "Journal review shows 78% rule compliance on trades before noon, 54% after 2 PM. You implement hard stop: no new entries after 12:30 PM unless pre-flagged A-setup at marked level. Next month compliance rises to 85% overall; afternoon losses drop 60%. Same strategy, fewer tired decisions.",
        "tip": "Set a daily maximum decision budget — e.g., two full checklist evaluations after lunch, period.",
        "bullets": [
            "Decision fatigue degrades judgment before willpower admits it",
            "Reduce choices via fixed watchlists, defaults, and automation",
            "Batch prep decisions; reserve discretion for A-setup timing",
            "Track rule violations by time of day to find fatigue patterns",
            "Shorten session or break before second block if errors cluster",
        ],
        "takeaway": "Fewer choices can improve performance. Protect your focus for the trades that deserve it — not the ones that appear when you are tired.",
    },
    88: {
        "id": 88,
        "outcome": "You will classify the current environment as trending, ranging, or volatile-transition — and activate only the strategy modules matched to that environment.",
        "intro": "Strategy without environment fit is fighting the terrain. The trading environment tells you which tools belong in your hands today.",
        "core": "Three primary environments: trending (directional structure, pullbacks hold, breakouts follow through), ranging (defined boundaries, mean reversion works, breakouts fail often), volatile transition (expanding ATR, structure unclear, whipsaws frequent — often post-news or regime shift).\n\nEach environment favors different modules: trend following and breakout continuation in trends; range fades and smaller targets in balance; reduced size or stand aside in volatile transition until structure clarifies.\n\nClassification uses objective inputs: ADX or slope, higher-high/higher-low sequence, range width relative to ATR, volume trend. Re-classify at session open and after major structure breaks — environment is dynamic.\n\nMismatch damage: mean reverting in a breakout trend; trend following in a two-week rectangle; full size in transition chop. Environment filter is the first gate in your plan.",
        "chart_title": "Trending versus ranging environment",
        "chart_caption": "Trending markets reward continuation; ranging markets reward fades at boundaries. Mismatch between strategy and environment erodes edge.",
        "example": "Gold trends from $2,300 to $2,420 over three weeks — HH/HL intact, pullbacks shallow. Environment: trend. You run pullback long module only. It enters range $2,410–$2,430 for eight days — environment shifts to balance. You disable trend adds mid-range and switch to boundary fades until acceptance above $2,430 or below $2,410 confirms breakout.",
        "tip": "Label environment type on your daily prep sheet — one word: TREND, RANGE, or TRANSITION.",
        "bullets": [
            "Primary environments: trending, ranging, volatile transition",
            "Each environment activates different strategy modules",
            "Classify with objective structure and volatility inputs",
            "Re-classify after session open and major structure breaks",
            "Environment mismatch is a leading cause of strategy failure",
        ],
        "takeaway": "Strategy should match environment. Trade the right style for today's terrain — not yesterday's winning tactic.",
    },
    89: {
        "id": 89,
        "outcome": "You will allocate risk budget across setups by grade, theme, and time horizon — giving A-setups full size, B-setups reduced size, and C-setups zero.",
        "intro": "Not every valid-looking trade deserves equal capital. Risk allocation is how you bet more when edge is thick and less when it is thin.",
        "core": "Risk allocation tiers: A-setup (full plan size, all filters align), B-setup (half size, one filter soft), C-setup (no trade — missing confluence, hostile context, or poor R). Grading happens before entry, never after to justify oversizing.\n\nThematic allocation caps exposure to one macro view — max 2% total to USD-short expressions regardless of individual ticket count. Time horizon allocation separates scalp risk budget from swing risk budget so one style cannot consume the other's capital.\n\nDynamic allocation adjusts to account state: reduce all tiers by 50% in drawdown; restore only after new equity high or defined recovery trades. Winning streaks do not automatically upgrade B to A — grade is setup quality, not recent P&L.\n\nDocument allocation math in plan: base risk 1%, A=1%, B=0.5%, portfolio max 3%. Calculator enforces tiers; emotion does not override.",
        "chart_title": "Risk allocation by setup grade",
        "chart_caption": "Full size for A-setups with full confluence; reduced for B; zero for C. Allocation precedes entry, not follows regret.",
        "example": "Base risk 1% ($500 on $50k). Monday A-setup pullback in trend with context favorable: 1% risk. Tuesday similar pattern but during Asia with compressed vol — B-grade: 0.5%. Wednesday breakout without volume — C-grade: pass. Weekly heat stays under 3% while capturing best opportunities at appropriate size.",
        "tip": "Write setup grade on every journal line before entry — if grade and size disagree, fix size before click.",
        "bullets": [
            "Allocate risk by setup grade: A full, B half, C zero",
            "Grade setups before entry using written criteria",
            "Cap thematic exposure across correlated positions",
            "Reduce all tiers during drawdown; restore by rule, not feeling",
            "Recent P&L does not change setup grade",
        ],
        "takeaway": "Not every setup deserves the same size. Allocate risk intentionally — more where edge is thick, zero where it is not.",
    },
    90: {
        "id": 90,
        "outcome": "You will conduct structured performance reviews across large samples — separating luck from edge, behavior from strategy, and signal from noise in your results.",
        "intro": "One trade proves nothing. One month proves little. Performance review at scale is how you learn what actually works versus what felt good.",
        "core": "Review layers: outcome metrics (win rate, avg R, profit factor, max DD), process metrics (checklist compliance, rule breaks, session timing), and setup metrics (performance by grade, instrument, session, environment tag).\n\nMinimum sample before conclusions: 30 trades for initial patterns, 100 for strategy confidence, 200+ for scaling decisions. Short samples overreact to variance — a 70% win rate over fifteen trades means little.\n\nCompare live to backtest bands. If live profit factor drops 40% below backtest, investigate slippage, regime change, or discipline leaks before tweaking rules. If live exceeds backtest dramatically, suspect variance and maintain size discipline.\n\nReview cadence: weekly tactical (rule breaks, emotional tags), monthly strategic (setup performance, environment fit), quarterly structural (plan revisions, one change at a time). Document every change with hypothesis and review date.",
        "chart_title": "Performance review dashboard",
        "chart_caption": "Outcome, process, and setup metrics together reveal whether results come from edge, luck, or leaks.",
        "example": "Quarterly review of 140 trades: overall 1.4 profit factor, but London pullbacks 1.9 PF vs New York breakouts 0.8 PF. Compliance 87% overall, 62% on NY breakouts — discipline leak identified. Plan change: remove NY breakout module; re-evaluate after next 50 trades. One targeted fix beats adding three new indicators.",
        "tip": "Review performance by tag (session, grade, environment) — aggregate stats hide where edge lives and dies.",
        "bullets": [
            "Review outcome, process, and setup metrics together",
            "Require minimum sample sizes before drawing conclusions",
            "Compare live results to backtest expectation bands",
            "Weekly tactical, monthly strategic, quarterly structural reviews",
            "One documented change per cycle — avoid simultaneous tweaks",
        ],
        "takeaway": "Long-term review beats one-trade judgment. Measure the full picture over enough trades to see truth, not noise.",
    },
    91: {
        "id": 91,
        "outcome": "You will build evidence-based conviction in your edge through sample accumulation, out-of-sample validation, and disciplined execution — distinguishing conviction from hope or arrogance.",
        "intro": "Conviction is not blind belief — it is calibrated confidence earned from repeated proof that your process works across conditions.",
        "core": "Conviction grows through: backtest baseline, sim execution matching rules, live sample meeting minimum N, drawdown within expected range, and successful navigation of at least one adverse regime without abandoning process.\n\nFalse conviction sources: small-sample hot streak, curve-fit backtest, social proof from gurus, or confusing clarity of rules with proof of edge. True conviction survives a 20% drawdown without rewriting everything.\n\nConviction enables proper execution: taking full-size A-setups after three losses because sample says edge intact; holding targets without premature exit; passing B-setups without FOMO. Without conviction, every loss triggers strategy doubt; every win triggers oversize.\n\nMaintain conviction ledger: date, sample size, key metrics, regime notes, planned next validation milestone. Update quarterly — conviction is maintained by ongoing evidence, not one great year.",
        "chart_title": "Evidence-based conviction curve",
        "chart_caption": "Conviction should track accumulated evidence — sample size, stable metrics, regime tests — not short-term P&L swings.",
        "example": "Pullback strategy: 180 backtest trades, 95 live trades, profit factor 1.5 live vs 1.6 backtest, max DD 11% vs 14% backtested. After four consecutive losses you still take trade five at full A-size because metrics and compliance remain in band — conviction from evidence. Trade five wins 2.5R. A trader without conviction would have skipped or halved size arbitrarily.",
        "tip": "List three numbers that justify your conviction — sample N, profit factor, max DD — and reread them after every losing streak.",
        "bullets": [
            "Conviction comes from sample size and stable metrics, not streaks",
            "False conviction follows small samples and curve-fit backtests",
            "True conviction enables full-size execution through normal variance",
            "Maintain conviction ledger updated quarterly with evidence",
            "Conviction survives drawdowns within expected bands",
        ],
        "takeaway": "Evidence builds confidence. Trust your edge when data supports it — not when mood does.",
    },
    92: {
        "id": 92,
        "outcome": "You will identify revenge trading triggers before acting, deploy mechanical circuit breakers after losses, and restore emotional equilibrium without seeking immediate redemption in the market.",
        "intro": "Revenge trading is not a strategy — it is an emotional tax you pay twice: once on the original loss, again on the impulsive trades that follow.",
        "core": "Revenge trading manifests as: immediate re-entry after stop-out, size increase to 'win it back,' trading outside session hours, abandoning checklist ('this one is obvious'), and chasing moves you missed. It feels like urgency; it is cortisol driving risk destruction.\n\nTriggers include: unexpected stop, public loss after winning streak, missed move FOMO compounded by recent loss, and external stress bleeding into session. Identify your top three triggers in journal — they repeat.\n\nMechanical countermeasures: mandatory 15–30 minute cooldown after any loss; daily loss limit halts session; physical leave desk rule; 'two-strike' rule — two losses in row ends day regardless of limit; pre-written self-talk script ('The market owes me nothing today').\n\nRecovery is not redemption on the next candle. Recovery is returning tomorrow with normal size and full checklist. One revenge session can erase a month of disciplined edge.",
        "chart_title": "Revenge trading spiral",
        "chart_caption": "Loss triggers impulsive trades, which create more losses. Circuit breakers interrupt the spiral before damage compounds.",
        "example": "Stopped out -1R on GBP/USD long at 10:15 AM. Without cooldown you short immediately at 10:17 on 'failed breakout' — B-setup, no checklist — stopped -1R. Angry, you long again 10:22, -1R. Three trades, -3R, one morning. With plan: cooldown until 10:45, next trade at 11:00 only if A-setup — you pass mediocre shorts and save -2R.",
        "tip": "After a stop-out, change physical location before any new decision — bathroom, walk, different room. Break the loop.",
        "bullets": [
            "Revenge trading increases size and lowers standards after losses",
            "Identify personal triggers — they repeat predictably",
            "Use cooldowns, daily limits, and two-strike session stops",
            "Recovery means normal process tomorrow, not immediate win-back",
            "One revenge session can erase weeks of disciplined edge",
        ],
        "takeaway": "Walk away before emotion takes over. The market will be there tomorrow; revenge capital might not be.",
    },
    93: {
        "id": 93,
        "outcome": "You will design and maintain simple trading systems with few rules that you can execute, test, and journal consistently — valuing clarity over complexity.",
        "intro": "Complex systems impress in backtests and fail live because no human executes seventeen conditions under pressure. Simple systems survive contact with reality.",
        "core": "Simple systems have: one clear market filter, one entry trigger, one stop rule, one target framework, one size rule. Each component fits on half a page. If explanation takes twenty minutes, execution will fail when stressed.\n\nComplexity costs: more parameters to curve-fit, more discretion hidden in 'slightly' qualifiers, harder journaling tags, slower adaptation cycles. Occam's razor applies — the simplest rules that capture the behavior win long-term.\n\nSimplicity does not mean naive. A daily trend filter plus 4H pullback entry is simple but robust. Fifty-indicator dashboards are complex and fragile.\n\nTest simplicity by teaching: could a disciplined beginner follow your rules without clarification? Could you execute from memory after a bad night's sleep? If no, simplify before scaling.",
        "chart_title": "Simple system architecture",
        "chart_caption": "Filter, trigger, stop, target, size — five components, one page. Simple systems are easier to test, execute, and improve.",
        "example": "Complex version: trend + RSI + MACD cross + volume spike + candle pattern + session filter + news filter — 47 optimized parameters, great 2019 backtest, fails 2024. Simple version: daily uptrend, buy 4H pullback to 20 EMA with bullish close, stop below swing low, target 2R — 48% win rate, stable five years. You trade the simple version live.",
        "tip": "Try removing one rule from your system for backtest — if performance barely changes, that rule was complexity, not edge.",
        "bullets": [
            "Simple systems: one filter, trigger, stop, target, size rule",
            "Complexity increases curve-fit risk and execution failure",
            "If rules need twenty minutes to explain, simplify before live",
            "Simplicity test: execute from memory under mild stress",
            "Remove rules that do not materially change backtest results",
        ],
        "takeaway": "Simple rules are easier to execute. Clarity beats complexity — especially when the market turns hostile.",
    },
    94: {
        "id": 94,
        "outcome": "You will refine strategies through single-variable changes, hypothesis-driven tests, and out-of-sample validation — improving edge without curve-fitting to recent noise.",
        "intro": "Refinement is surgery, not renovation. Change one thing, measure, validate — or you will never know what helped and what hurt.",
        "core": "Strategy refinement loop: identify weakness from tagged journal data (e.g., NY session underperformance), form hypothesis ('disable entries first 15 minutes'), test on out-of-sample or forward live block, adopt or reject based on predefined success criteria.\n\nOne change at a time. Simultaneous tweaks — new filter plus new target plus new size — make attribution impossible and invite overfitting to the last thirty trades.\n\nRefinement boundaries: core hypothesis stays (e.g., trend pullbacks work); tactical filters adjust (session, volume threshold). If core hypothesis fails over 100+ trades, retire strategy — do not refine a corpse.\n\nDocument version history: Strategy v1.2 — added London-only filter 2024-03 — PF 1.4 to 1.55 on forward 40 trades — kept. Versioning prevents accidental reversion and clarifies which rules produced which sample.",
        "chart_title": "Single-variable refinement loop",
        "chart_caption": "Hypothesis, one change, forward test, adopt or reject. Sequential refinement preserves attribution and reduces overfitting.",
        "example": "Breakout strategy shows 55% false break rate on first touch; 32% on retest entries. Hypothesis: retest-only entries. Forward test 35 trades — win rate rises 41% to 54%, avg R improves. Adopt as v2.0. Parallel change adding RSI filter waits for next cycle — not combined in same month.",
        "tip": "Date and name every strategy version in your journal — 'v1.3' tags make performance attribution possible.",
        "bullets": [
            "Refine one variable at a time with written hypothesis",
            "Use journal tags to identify weakness, not gut feel",
            "Forward or out-of-sample test before permanent adoption",
            "Retire failed core hypotheses; refine tactics only on living edge",
            "Version strategy docs with date and change log",
        ],
        "takeaway": "Small refinements are usually safer. Improve one part at a time — or you optimize yourself into a backtest mirage.",
    },
    95: {
        "id": 95,
        "outcome": "You will require statistically meaningful sample sizes before judging strategy changes, understand confidence intervals around win rate, and avoid reactive decisions on short streaks.",
        "intro": "Ten trades prove nothing. Fifty barely whisper. Long sample testing is how you hear what the market is actually telling you.",
        "core": "Sample size math: win rate on 20 trades has enormous confidence interval — 60% might be 40–80% true rate. At 200 trades, interval narrows. Major decisions (scale, retire, rewrite) require large N.\n\nRules of thumb: 30 trades minimum to notice patterns; 100 for strategy health check; 200+ for scaling or major refinement. Combine with profit factor, average R, and max drawdown — not win rate alone.\n\nLong sample testing includes regime coverage: strategy must survive at least one adverse period in sample — not only bull trend years. Walk-forward and rolling window analysis simulate ongoing validation.\n\nPatience during sample building is a skill. Traders abandon viable edges at trade 25 because of normal variance. Pre-commit to sample targets before live start; do not re-evaluate early unless risk limits breach.",
        "chart_title": "Sample size and statistical confidence",
        "chart_caption": "Small samples produce wide uncertainty bands. Larger samples narrow truth — patience before judgment prevents premature strategy death.",
        "example": "After 25 live trades at 36% win rate you consider quitting — backtest showed 45%. Mentor requires 100-trade minimum. Trades 26–100 bring win rate to 44%, profit factor 1.45 — viable. Early quit would have discarded edge. Another trader tweaks rules every 15 trades chasing 60% win rate — five versions, no valid sample on any.",
        "tip": "Write your minimum N on your plan cover page — read it whenever a short streak tempts you to change everything.",
        "bullets": [
            "Small samples produce misleading win rates and profit factors",
            "Use 100+ trades for health checks; 200+ for scaling decisions",
            "Require adverse regime coverage in long samples",
            "Pre-commit to sample targets before live trading begins",
            "Premature strategy abandonment is a hidden cost of impatience",
        ],
        "takeaway": "Big samples give better answers. Judge strategies on enough trades that luck stops dominating the verdict.",
    },
    96: {
        "id": 96,
        "outcome": "You will audit your behavior under drawdown, time pressure, and unexpected volatility — and install safeguards that keep process intact when stakes feel highest.",
        "intro": "Anyone can follow rules in a calm uptrend. Pressure exposes whether your process is real or performative — and weak spots always appear first when money is on the line.",
        "core": "Pressure scenarios: consecutive losses, sudden volatility spike, missed move then chase urge, open position going against you during news, public track record pressure. Each triggers cortisol-driven shortcuts.\n\nBehavioral audit: review journal tags for rule breaks clustered under pressure. Common leaks: moving stops, early exits on winners, late entries on FOMO, oversizing after loss. Name your top three pressure failures explicitly.\n\nSafeguards: reduce auto-size 50% when VIX or ATR percentile exceeds threshold; hard daily stop; buddy or mentor check-in during drawdown; sim replay of worst historical day to practice compliance. Pressure training in sim beats discovering leaks live at full size.\n\nProfessional behavior under pressure is boring: same checklist, same size formula, same walk-away rules. Excitement under stress is a warning sign, not confidence.",
        "chart_title": "Behavior under stress",
        "chart_caption": "Drawdowns and volatility spikes test process integrity. Pre-defined pressure protocols beat improvised heroics.",
        "example": "During March volatility spike, ATR doubles. Plan triggers half-size mode automatically. You take valid setup at half risk; stopped normally -0.5R effective. Peer keeps full size, widens stop 'to avoid noise,' loses -2R when gap blows through. Same setup, different pressure response.",
        "tip": "Sim-trade your plan during the most volatile week of the last year — pressure rehearsal is free tuition.",
        "bullets": [
            "Pressure exposes rule breaks that calm markets hide",
            "Audit journal for violations during drawdown and volatility spikes",
            "Install automatic size reduction when volatility exceeds thresholds",
            "Rehearse worst-case scenarios in sim before live pressure hits",
            "Excitement under stress signals risk — boredom signals process",
        ],
        "takeaway": "Pressure exposes weak spots. Build safeguards for hostile moments — that is when process matters most.",
    },
    97: {
        "id": 97,
        "outcome": "You will trust tested rules during normal variance, execute without second-guessing validated components, and distinguish healthy system confidence from rigid refusal to adapt.",
        "intro": "System confidence is the ability to execute your tested plan through boring and painful periods — because proof says the distribution, not today's result, is what you trade.",
        "core": "System confidence rests on: documented rules, backtest and live sample alignment, defined invalidation for the system itself (not single trades), and separation of trade outcome from system quality in review.\n\nWithout system confidence, you tweak after every loss, skip entries after stops, and override targets on winners. Edge leaks through non-execution — the strategy never gets its fair trial.\n\nHealthy confidence vs rigidity: confidence executes through 15-trade drawdown within backtest DD; rigidity ignores 100-trade degradation and blames 'bad luck.' System kill criteria are pre-written — profit factor below 1.1 over 100 trades, or DD exceeds 2× backtest max — trigger review or retirement.\n\nBuild confidence through repetition: sim weeks executing identical checklist, live micro-size until compliance automatic, then scale. Confidence is a habit of rule-following, not a feeling.",
        "chart_title": "System confidence through variance",
        "chart_caption": "Expected equity curves include drawdowns. System confidence means executing the plan through valleys, not abandoning at first dip.",
        "example": "Strategy hits eight losses in twelve trades — painful but within backtest 95th percentile streak. System confidence: continue A-setups at plan size, no rule changes mid-sample. Trades 13–20 deliver 3.2 avg R on winners; sample recovers. Without confidence you disabled strategy at trade 12 — missed recovery and learned nothing valid.",
        "tip": "When urge to change rules spikes, check if metric breach is predefined kill criteria — if not, execute one more week unchanged.",
        "bullets": [
            "System confidence enables execution through normal drawdowns",
            "Non-execution from doubt leaks edge without revealing strategy failure",
            "Pre-define system kill criteria separate from single trade stops",
            "Rigidity ignores evidence; confidence follows evidence until kill line",
            "Confidence builds through repetitive compliant execution",
        ],
        "takeaway": "Confidence should come from proof. Trust the rules you tested — until predefined evidence says the system, not variance, broke.",
    },
    98: {
        "id": 98,
        "outcome": "You will detect overoptimization in backtests, prefer robust parameters across ranges, and validate strategies with out-of-sample and walk-forward methods before trusting results.",
        "intro": "A perfect backtest is a warning, not a green light. Overoptimization fits noise so tightly that live trading becomes an expensive lesson in humility.",
        "core": "Overoptimization signs: dozens of parameters, win rate above 70% on complex rules, performance cliffs when parameters shift ±5%, incredible equity curve with no meaningful drawdown, optimization on entire dataset without holdout.\n\nRobust strategies tolerate reasonable parameter ranges — 20 vs 21 period MA performs similarly; edge comes from concept, not magic number. Test sensitivity: if 18–25 period window all profit, likely robust; if only 21 works, likely noise.\n\nValidation methods: out-of-sample holdout (train 2018–2022, test 2023–2024), walk-forward (rolling train/test windows), monte carlo shuffle of trade order for DD distribution. Pass multiple methods before live capital.\n\nSimplicity is anti-overfit: fewer rules, fewer degrees of freedom, harder to accidentally fit noise. When in doubt, cut a filter and retest.",
        "chart_title": "Robust versus overfit equity curves",
        "chart_caption": "Overfit systems show perfect historical curves and fail forward. Robust systems show messier history and survive new data.",
        "example": "Optimized scalper: 73% win rate, 47 parameters, max DD 4% 2019–2023. Forward 2024: 41% win rate, -22% DD. Simpler version: 51% win rate, 5 rules, 12% max DD backtest, 10% forward DD, profit factor 1.3. You trade simpler version — boring backtest, live survivability.",
        "tip": "Run parameter sensitivity on every backtest — if performance lives or dies on one number, do not trade it live.",
        "bullets": [
            "Perfect backtests often signal overfit, not edge",
            "Robust strategies work across reasonable parameter ranges",
            "Use out-of-sample and walk-forward validation before live",
            "Fewer rules reduce degrees of freedom and curve-fit risk",
            "Parameter sensitivity tests reveal noise versus signal",
        ],
        "takeaway": "A robust strategy beats a perfect backtest. Fit concepts, not noise — or the market will unfit you expensively.",
    },
    99: {
        "id": 99,
        "outcome": "You will adopt a professional trader mindset focused on process, probabilities, and continuous improvement — replacing prediction fantasies and outcome obsession with executable discipline.",
        "intro": "The market does not reward the smartest forecast. It rewards consistent execution of positive expectancy with controlled risk — a mindset shift from hero to operator.",
        "core": "Professional mindset pillars: think in distributions not certainties; measure process compliance as primary KPI; accept that any single trade is noise; protect capital as job one; improve through iteration not inspiration.\n\nAmateur mindset traps: need to be right on every trade; hide losses from self-review; chase excitement; equate P&L with self-worth; seek the one indicator that fixes everything.\n\nDaily mental reframe: 'Did I execute?' before 'Did I win?' Weekly: 'What did data teach?' not 'What did I make?' Long-term: career measured in years and samples, not sessions.\n\nMindset is trained like technique: gratitude for plan-compliant losses, detachment exercises post-trade, identity as risk manager who sometimes captures edge — not gambler who sometimes gets paid.",
        "chart_title": "Professional versus amateur focus",
        "chart_caption": "Professionals optimize process and probabilities; amateurs optimize excitement and prediction. Mindset determines which curve you compound.",
        "example": "Two traders same strategy. Pro ends month -2R with 94% checklist compliance — notes 'variance, continue.' Amateur same -2R, 61% compliance — rewrites strategy, doubles size next month, -15R. Identical market, different mindset, opposite trajectories.",
        "tip": "Start each session with one process goal ('90% checklist today') — not a P&L goal.",
        "bullets": [
            "Think in probabilities and distributions, not certainties",
            "Process compliance is the primary daily KPI",
            "Any single trade outcome is low-signal noise",
            "Identity as risk manager and operator, not predictor",
            "Improve through data iteration, not emotional reaction",
        ],
        "takeaway": "Think in probabilities, not certainty. Professional mindset compounds process — amateur mindset compounds mistakes.",
    },
    100: {
        "id": 100,
        "outcome": "You will integrate market reading, context, risk allocation, session awareness, psychological discipline, simple systems, and continuous review into one cohesive trading operation — the capstone framework for everything you have learned.",
        "intro": "One hundred lessons converge here. Successful trading is not one skill — it is a system of systems where analysis, risk, psychology, and process reinforce each other or collapse together.",
        "core": "The integrated framework has five pillars that map to your entire curriculum:\n\n1. READ THE MARKET — Structure, price action, context (Lessons 1–10, 36–39, 76, 81–84, 88): Start with trend and levels on higher timeframe. Classify environment (trend, range, transition). Add session and volatility context. Read correlation when holding multiple positions. No entry until context and setup align.\n\n2. CONTROL RISK — Sizing, stops, portfolio heat (Lessons 11–15, 51–55, 85, 89): Calculate size from equity and stop distance. Grade setups A/B/C and allocate risk accordingly. Cap portfolio heat and thematic overlap. Reduce size in drawdown and high volatility automatically.\n\n3. EXECUTE WITH DISCIPLINE — Plan, checklist, process (Lessons 26–30, 66–70, 86–87, 92): Follow repeatable daily process. Use checklist every trade. Manage decision fatigue with session limits. Circuit breakers stop revenge spirals. Simple systems beat complex ones under pressure.\n\n4. MANAGE MINDSET — Variance, confidence, pressure (Lessons 16–20, 56–60, 77, 91, 96–99): Accept losses as tuition. Distinguish false confidence from evidence-based conviction. Behavior under pressure reveals true process. Think in probabilities across long samples.\n\n5. IMPROVE CONTINUOUSLY — Journal, review, refine (Lessons 31–35, 71–75, 90, 94–95, 98): Journal every trade with tags. Review performance by setup, session, environment. Refine one variable at a time. Require long samples before judgment. Avoid overoptimization.\n\nThe daily capstone workflow: Pre-market — mark levels, score context, check calendar, set environment label. Pre-trade — grade setup, calculate size, confirm portfolio heat room. Execute — checklist, no improvisation. Post-trade — journal immediately. End-of-day — process score, not P&L score. Weekly — stats review. Monthly — one refinement hypothesis.\n\nScaling progression (Lessons 78, 80): sim mastery → micro live → sample proof → gradual size increase. Never skip evidence gates.\n\nThis is not a checklist to memorize once — it is an operating system to run every session until automatic. Results emerge from the whole system working together, not from any single brilliant call.",
        "chart_title": "Integrated trading framework",
        "chart_caption": "Five pillars — read, risk, execute, mindset, improve — interlock. Weakness in one pillar undermines the others. The capstone is running all five daily.",
        "example": "Monday capstone in practice: Pre-market — ES daily uptrend (READ), environment TREND, London open approaching (session), no red news (calendar). A-setup pullback to 5,180 with bullish 4H close (READ + EXECUTE). Size 1% A-grade, portfolio heat 1.8% of 3% max (RISK). Checklist six of six (EXECUTE). Stop hit -1R — plan-compliant loss (MINDSET). Journal tagged in five minutes (IMPROVE). No revenge entry (MINDSET + EXECUTE). Tuesday — review shows Monday loss within expectancy; continue unchanged (IMPROVE + MINDSET). One week, one loss, zero process breaks — that is capstone execution.",
        "tip": "Print the five-pillar framework and tape it beside your screen — capstone trading is remembering everything at once until it becomes habit.",
        "bullets": [
            "Five pillars: read market, control risk, execute discipline, manage mindset, improve continuously",
            "Context and environment gate every setup from Lessons 76–88",
            "Risk allocation and portfolio thinking cap total exposure",
            "Simple systems, process, and anti-revenge rules protect execution",
            "Long-sample review and single-variable refinement close the loop",
        ],
        "takeaway": "Results come from the whole system, not one idea. Run all five pillars every session — that is what one hundred lessons built toward.",
    },
})
