# Lessons 2-47 — practical crypto curriculum (RU / EN / PT)
# Each lesson uses the same loc keys as generate_curriculum_v2.build_sections

def _loc(ru, en, pt, **kw):
    base = {"ru": dict(ru), "en": dict(en), "pt": dict(pt)}
    for lang in ("ru", "en", "pt"):
        for k, v in kw.items():
            if k not in base[lang]:
                base[lang][k] = v[lang] if isinstance(v, dict) else v
    return base


def _m(br, mx, ru, gl=""):
    return {"br": br, "mx": mx, "ru": ru, "global": gl or br}


def L(i, mod, diff, mins, chart, sym, markets, loc):
    return {
        "id": i, "module": mod, "difficulty": diff, "durationMin": mins,
        "chart": chart, "symbol": sym, "interval": "15", "markets": markets, "loc": loc,
    }


def _std(ru_t, en_t, pt_t, ru_sub, en_sub, ru_th, en_th, ru_th2, en_th2, pt_th, pt_th2,
         chart, sym, br_m, mx_m, ru_m, ru_tv, en_tv, pt_tv,
         ru_steps, en_steps, pt_steps, ru_ex, en_ex, ru_bul, en_bul, pt_bul, ru_tip, en_tip, pt_tip,
         diff="Intermediate", mins=22, interval="15"):
    loc = _loc(
        {
            "title": ru_t, "subtitle": ru_sub,
            "outcome": f"Освоите тему «{ru_t}» с разбором в TradingView и практикой.",
            "content": ru_th[:120], "takeaway": ru_bul[0] if ru_bul else ru_tip[:80],
            "h1": "Теория", "theory": ru_th, "h2": "Как применять", "theory2": ru_th2,
            "market_title": "Ваш рынок", "chart_title": ru_t, "chart_cap": ru_th2[:100],
            "tv_title": "Разбор в TradingView", "tv_body": ru_tv,
            "practice_title": "Практика", "practice_intro": "Выполните по шагам:",
            "practice_steps": ru_steps,
            "example_title": "Сценарий", "example": ru_ex,
            "bullets_title": "Запомнить", "bullets": ru_bul,
            "journal_title": "Журнал", "journal_body": "Запишите:",
            "journal_items": ["Сетап", "Вход / стоп / цель", "Эмоция до входа"],
            "tip_title": "Совет профи", "tip": ru_tip,
        },
        {
            "title": en_t, "subtitle": en_sub,
            "outcome": f"Master '{en_t}' with TradingView breakdown and practice.",
            "content": en_th[:120], "takeaway": en_bul[0] if en_bul else en_tip[:80],
            "h1": "Theory", "theory": en_th, "h2": "Application", "theory2": en_th2,
            "market_title": "Your market (LATAM)", "chart_title": en_t, "chart_cap": en_th2[:100],
            "tv_title": "TradingView breakdown", "tv_body": en_tv,
            "practice_title": "Practice", "practice_intro": "Follow steps:",
            "practice_steps": en_steps,
            "example_title": "Scenario", "example": en_ex,
            "bullets_title": "Remember", "bullets": en_bul,
            "journal_title": "Journal", "journal_body": "Record:",
            "journal_items": ["Setup", "Entry / stop / target", "Emotion before entry"],
            "tip_title": "Pro tip", "tip": en_tip,
        },
        {
            "title": pt_t, "subtitle": pt_sub,
            "outcome": f"Dominar '{pt_t}' com TradingView e prática.",
            "content": pt_th[:120], "takeaway": pt_bul[0] if pt_bul else pt_tip[:80],
            "h1": "Teoria", "theory": pt_th, "h2": "Aplicação", "theory2": pt_th2,
            "market_title": "Seu mercado (Brasil)", "chart_title": pt_t, "chart_cap": pt_th2[:100],
            "tv_title": "Setup no TradingView", "tv_body": pt_tv,
            "practice_title": "Prática", "practice_intro": "Siga os passos:",
            "practice_steps": pt_steps,
            "example_title": "Cenário", "example": ru_ex,
            "bullets_title": "Lembre", "bullets": pt_bul,
            "journal_title": "Diário", "journal_body": "Registre:",
            "journal_items": ["Setup", "Entrada / stop / alvo", "Emoção antes da entrada"],
            "tip_title": "Dica profissional", "tip": pt_tip,
        },
    )
    mod = ("График", "Chart", "Gráfico")
    if i := None:
        pass
    return loc


# Simpler: define each lesson inline with L() helper
MOD_INTRO = ("Введение", "Introduction", "Introdução")
MOD_CHART = ("График", "Chart", "Gráfico")
MOD_PAT = ("Паттерны", "Patterns", "Padrões")
MOD_STR = ("Стратегии", "Strategies", "Estratégias")
MOD_MKT = ("Рынок", "Market", "Mercado")
MOD_RISK = ("Риск", "Risk", "Risco")
MOD_PRAC = ("Практика", "Practice", "Prática")


def lesson_template(
    lid, mod, diff, mins, chart, sym, markets,
    ru_title, en_title, pt_title,
    ru_th, en_th, pt_th,
    ru_th2, en_th2, pt_th2,
    ru_tv, en_tv, pt_tv,
    ru_steps, en_steps, pt_steps,
    ru_ex, en_ex,
    ru_bul, en_bul, pt_bul,
    ru_tip, en_tip, pt_tip,
    interval="15",
):
    loc = {
        "ru": {
            "title": ru_title, "subtitle": ru_title,
            "outcome": f"Разберёте «{ru_title}» на графике и в TradingView.",
            "content": ru_th[:100], "takeaway": ru_bul[0],
            "h1": "Теория", "theory": ru_th, "h2": "Применение", "theory2": ru_th2,
            "market_title": "Ваш рынок", "chart_title": ru_title, "chart_cap": ru_th2[:90],
            "tv_title": "TradingView", "tv_body": ru_tv,
            "practice_title": "Практика", "practice_intro": "Шаги:",
            "practice_steps": ru_steps, "example_title": "Сценарий", "example": ru_ex,
            "bullets_title": "Запомнить", "bullets": ru_bul,
            "journal_title": "Журнал", "journal_body": "Запишите сетап:",
            "journal_items": ["Таймфрейм и пара", "Вход / стоп / цель", "R:R"],
            "tip_title": "Совет", "tip": ru_tip,
        },
        "en": {
            "title": en_title, "subtitle": en_title,
            "outcome": f"Break down '{en_title}' on chart and TradingView.",
            "content": en_th[:100], "takeaway": en_bul[0],
            "h1": "Theory", "theory": en_th, "h2": "Application", "theory2": en_th2,
            "market_title": "LATAM market", "chart_title": en_title, "chart_cap": en_th2[:90],
            "tv_title": "TradingView", "tv_body": en_tv,
            "practice_title": "Practice", "practice_intro": "Steps:",
            "practice_steps": en_steps, "example_title": "Scenario", "example": en_ex,
            "bullets_title": "Remember", "bullets": en_bul,
            "journal_title": "Journal", "journal_body": "Log setup:",
            "journal_items": ["Pair & timeframe", "Entry / stop / target", "R:R"],
            "tip_title": "Pro tip", "tip": en_tip,
        },
        "pt": {
            "title": pt_title, "subtitle": pt_title,
            "outcome": f"Dominar '{pt_title}' no gráfico e TradingView.",
            "content": pt_th[:100], "takeaway": pt_bul[0],
            "h1": "Teoria", "theory": pt_th, "h2": "Aplicação", "theory2": pt_th2,
            "market_title": "Mercado Brasil", "chart_title": pt_title, "chart_cap": pt_th2[:90],
            "tv_title": "TradingView", "tv_body": pt_tv,
            "practice_title": "Prática", "practice_intro": "Passos:",
            "practice_steps": pt_steps, "example_title": "Cenário", "example": en_ex,
            "bullets_title": "Lembre", "bullets": pt_bul,
            "journal_title": "Diário", "journal_body": "Anote o setup:",
            "journal_items": ["Par e timeframe", "Entrada / stop / alvo", "R:R"],
            "tip_title": "Dica", "tip": pt_tip,
        },
    }
    return {
        "id": lid, "module": mod, "difficulty": diff, "durationMin": mins,
        "chart": chart, "symbol": sym, "interval": interval,
        "markets": markets, "loc": loc,
    }


STEPS_CHART = (
    ["Откройте TradingView по ссылке урока", "Отметьте 3 уровня на графике", "Сделайте скрин с подписью вход/стоп", "Запишите в журнал без сделки"],
    ["Open TradingView from lesson link", "Mark 3 levels on chart", "Screenshot with entry/stop labels", "Log in journal without trading"],
    ["Abra TradingView pelo link", "Marque 3 níveis", "Print com entrada/stop", "Registre no diário sem operar"],
)

LESSONS_DATA = [
    lesson_template(
        2, MOD_INTRO, "Beginner", 26, "order_flow", "BINANCE:BTCUSDT",
        _m("Brasil: Tiger Trade e TradingView são padrão entre scalpers.", "México: muchos usan TradingView + Binance.", "РФ: Tiger, Vataga, CScalp — стандарт для скальпа."),
        "Вводное. С чего начать в трейдинге? Часть 2",
        "Intro: Where to start? Part 2",
        "Intro: Por onde começar? Parte 2",
        "Торговля на бирже: ордер лимит/маркет, комиссия maker/taker, funding на фьючерсах.\n\n"
        "Терминалы Tiger.Trade и Vataga дают стакан, кластеры, горячие клавиши — критично для скальпинга.",
        "Exchange trading: limit/market orders, maker/taker fees, futures funding.\n\n"
        "Tiger.Trade and Vataga give order book, hotkeys — essential for scalping.",
        "Trading na exchange: ordens limit/market, taxas, funding em futuros.\n\n"
        "Tiger.Trade e terminais locais aceleram scalping no Brasil.",
        "Скальпинг (секунды–минуты), среднесрок (часы–дни), долгосрок (недели). "
        "Первый депозит — сумма, которую не страшно потерять. Рабочий ордер — 0.5–1% риска от депозита.",
        "Scalping (seconds–minutes), swing (hours–days), position (weeks). "
        "First deposit = affordable loss. Risk 0.5–1% per trade.",
        "Scalping, médio prazo, longo prazo. Primeiro depósito = valor que pode perder. Risco 0,5–1% por trade.",
        "Откройте 5m BTC. Найдите спред в стакане. Посчитайте размер ордера при стопе 0.8% и риске 1%.",
        "Open 5m BTC. Find spread in book. Calculate position size for 0.8% stop and 1% risk.",
        "Abra BTC 5m. Veja spread no book. Calcule tamanho com stop 0,8% e risco 1%.",
        *STEPS_CHART,
        "Депозит 1000 USDT, риск 1% = 10 USDT на сделку. Стоп 0.5% от цены → размер позиции в 2 раза больше, чем при стопе 1%.",
        "1000 USDT, 1% risk = 10 USDT per trade. Tighter stop = larger position for same risk.",
        ["Скальпинг требует терминал и низкую комиссию", "Риск 0.5–1% на сделку", "Первый депозит — учебный", "Считайте размер до клика", "Trade Master + TV = практика"],
        ["Scalping needs terminal + low fees", "Risk 0.5–1% per trade", "First deposit is tuition", "Size before click", "Trade Master + TV practice"],
        ["Scalping precisa de terminal", "Risco 0,5–1%", "Primeiro depósito é aprendizado", "Calcule antes do clique", "Trade Master + TV"],
        "Не начинайте со скальпинга без стакана — сначала среднесрок на 15m.",
        "Don't scalp without order book skills — start on 15m swing.",
        "Não faça scalping sem book — comece em 15m.",
    ),
    lesson_template(
        3, MOD_CHART, "Beginner", 20, "momentum", "BINANCE:BTCUSDT",
        _m("Em altcoins brasileiras volatilidade pode passar de 10% no dia.", "Altcoins en México siguen a BTC con beta alto.", "На альтах амплитуда 5–15% за сессию — норма."),
        "Амплитуда движения",
        "Price amplitude",
        "Amplitude de movimento",
        "Амплитуда — размер движения в % от цены. На BTC 1% = крупное движение на 1h; на low-cap альте 10% за час — обычное.\n\n"
        "Измеряйте амплитуду ATR или диапазоном свечи. Планируйте тейк пропорционально амплитуде.",
        "Amplitude = move size in %. On BTC 1% is large on 1h; on low-cap alts 10%/hour is common.\n\n"
        "Measure with ATR or candle range. Size targets to amplitude.",
        "Amplitude = tamanho do movimento em %. Em alts brasileiras movimentos de 5–10% são comuns.",
        "Высокая амплитуда → уменьшайте плечо. Низкая → не ждите больших тейков внутри дня.",
        "High amplitude → reduce leverage. Low → don't expect huge intraday targets.",
        "Alta amplitude → reduza alavancagem. Baixa → alvos menores.",
        "На 15m отметьте диапазон последних 20 свечей в %. Это ваша «норма» амплитуды для тейка.",
        "On 15m mark range of last 20 candles in %. That's your amplitude baseline for targets.",
        "No 15m marque range das últimas 20 velas em %.",
        *STEPS_CHART,
        "SOL +4% за час — амплитуда высокая. Тейк 0.5% слишком мал; стоп 2% может быть шумом.",
        "SOL +4% in an hour — high amplitude. 0.5% target too small; 2% stop may be noise.",
        ["Амплитуда = % движения", "Считайте до входа", "Альты амплитуднее BTC", "Тейк под амплитуду", "ATR помогает"],
        ["Amplitude = % move", "Measure before entry", "Alts move more than BTC", "Target fits amplitude", "ATR helps"],
        ["Amplitude = % movimento", "Meça antes", "Alts > BTC", "Alvo conforme amplitude", "ATR ajuda"],
        "Запишите среднюю амплитуду вашей пары за неделю — используйте в каждом плане сделки.",
        "Log weekly average amplitude for your pair.",
        "Anote amplitude média semanal do seu par.",
    ),
    lesson_template(
        4, MOD_CHART, "Beginner", 22, "support_resistance", "BINANCE:ETHUSDT",
        _m("Suporte em PETR4 na B3 funciona igual — múltiplos toques em lows.", "Soporte en acciones MXN similar a crypto.", "Поддержка по лоям работает на любых активах."),
        "Поддержка по лоям",
        "Support by lows",
        "Suporte pelos fundos",
        "Поддержка по лоям: горизонталь через минимумы, где цена разворачивалась 2+ раз.\n\n"
        "Чем больше касаний без пробоя — тем сильнее уровень. Ложный пробой ниже лоя — частый сигнал лонга.",
        "Support by lows: horizontal through swing lows with 2+ bounces.\n\n"
        "More touches = stronger level. False break below low often signals long.",
        "Suporte pelos fundos: linha nos mínimos com 2+ reações.",
        "Стройте уровень по телам или теням — главное единообразие. На 5m и 1h уровни разные.",
        "Build from bodies or wicks — stay consistent. 5m and 1h levels differ.",
        "Use corpos ou pavios — seja consistente. 5m e 1h diferem.",
        "Найдите 3 лоя на ETH 1h. Проведите поддержку. Отметьте где цена стоит сейчас.",
        "Find 3 lows on ETH 1h. Draw support. Mark current price.",
        "Ache 3 fundos no ETH 1h. Desenhe suporte.",
        *STEPS_CHART,
        "ETH трижды отбился от 3200 — поддержка. Пробой с закрытием ниже → уровень сломан.",
        "ETH bounced 3x at 3200 — support. Close below = broken.",
        ["2+ лоя = уровень", "Ложный пробой — сетап", "Единый стиль разметки", "Старший ТФ важнее", "Журнал уровней"],
        ["2+ lows = level", "False break = setup", "Consistent markup", "Higher TF matters", "Log levels"],
        ["2+ fundos = nível", "Falso rompimento", "Marcação consistente", "TF maior importa", "Registre níveis"],
        "Не рисуйте 20 линий — 3–5 ключевых уровней на сессию достаточно.",
        "Don't draw 20 lines — 3–5 key levels per session.",
        "Não desenhe 20 linhas — 3–5 níveis bastam.",
    ),
    lesson_template(
        5, MOD_CHART, "Intermediate", 28, "order_flow", "BINANCE:BTCUSDT",
        _m("Book da Binance é referência para altcoins no Brasil.", "Book en Binance líder para MX.", "Стакан Binance — база для скальпа."),
        "Стакан. Подробно",
        "Order book deep dive",
        "Book de ofertas",
        "Стакан: bid (покупки) слева вниз, ask (продажи) справа вверх. Плотности — стены. "
        "Крупная стена может быть спуфингом (сняли перед касанием).\n\n"
        "Скорость ленты сделок показывает агрессию покупателя/продавца.",
        "Order book: bids vs asks, walls, spoofing risk.\n\n"
        "Tape speed shows buyer/seller aggression.",
        "Book: bids/asks, paredes, risco de spoofing.",
        "Читайте стакан вместе с графиком: пробой уровня + исчезновение ask = импульс.",
        "Read book with chart: break + ask vanishing = impulse.",
        "Leia book com gráfico: rompimento + sumiço de ask = impulso.",
        "Откройте стакан BTC. Найдите крупнейшую стену. Наблюдайте 5 мин — сняли или исполнили?",
        "Open BTC book. Find biggest wall. Watch 5 min — pulled or filled?",
        "Abra book BTC. Ache maior parede. Observe 5 min.",
        ["Откройте Binance Futures + стакан", "Скрин плотности bid/ask", "Отметьте спуфинг если был", "Журнал: что увидели"],
        ["Open Binance Futures book", "Screenshot density", "Note spoofing if any", "Journal observations"],
        ["Abra book Futures", "Print densidade", "Anote spoofing", "Diário"],
        "Стена 50 BTC на ask у 67000 снята за секунду до касания — спуфинг, не шортье вслепую.",
        "50 BTC ask wall pulled before touch — spoofing.",
        ["Bid/ask = спрос/предложение", "Стены двигают цену", "Спуфинг бывает", "Лента подтверждает", "Скальп = стакан + график"],
        ["Bid/ask = demand/supply", "Walls matter", "Spoofing exists", "Tape confirms", "Scalp = book + chart"],
        ["Bid/ask", "Paredes importam", "Spoofing existe", "Fit confirma", "Scalp = book + gráfico"],
        "Trade Master учит стакану — Finera и Coing этого не дают. Это ваше преимущество.",
        "Trade Master teaches order book — Finera/Coing don't. Your edge.",
        "Trade Master ensina book — concorrentes não. Sua vantagem.",
        interval="5",
    ),
]

# Append lessons 6-47 programmatically with rich metadata
_TITLES = [
    (6, MOD_CHART, "Intermediate", 20, "momentum", "BINANCE:BTCUSDT",
     "Особенности быстрого и медленного рынка", "Fast vs slow market", "Mercado rápido vs lento",
     "Быстрый рынок: широкие свечи, большой спред, проскальзывание. Медленный: узкий range, фейки пробоев.",
     "Fast market: wide candles, slippage. Slow: tight range, fake breaks."),
    (7, MOD_RISK, "Beginner", 22, "risk_reward", "BINANCE:BTCUSDT",
     "Основные ошибки новичков. Часть 1", "Beginner mistakes Part 1", "Erros de iniciante Parte 1",
     "Торговля без стопа, весь депозит в одну монету, FOMO после пампа, копирование сигналов из чата.",
     "No stop, all-in one coin, FOMO, copying chat signals."),
    (8, MOD_PAT, "Intermediate", 20, "breakout", "BINANCE:SOLUSDT",
     "Нисходящий треугольник", "Descending triangle", "Triângulo descendente",
     "Нисходящий треугольник: горизонтальная поддержка + понижающиеся максимумы. Пробой вниз — шорт.",
     "Descending triangle: flat support + lower highs. Breakdown = short."),
    (9, MOD_PAT, "Intermediate", 20, "breakout", "BINANCE:SOLUSDT",
     "Восходящий треугольник", "Ascending triangle", "Triângulo ascendente",
     "Восходящий треугольник: горизонтальное сопротивление + растущие минимумы. Пробой вверх — лонг.",
     "Ascending triangle: flat resistance + higher lows. Breakout up = long."),
    (10, MOD_STR, "Intermediate", 24, "breakout", "BINANCE:ETHUSDT",
     "Торговая стратегия для импульсов", "Impulse trading strategy", "Estratégia para impulsos",
     "Импульс: резкий объёмный выход из range. Вход на ретесте или на пробое с подтверждением объёмом.",
     "Impulse: volume breakout from range. Enter on retest or confirmed break."),
    (11, MOD_MKT, "Beginner", 16, "price_chart", "BINANCE:PEPEUSDT",
     "Делистинг монет с биржи", "Delisting risk", "Delisting de moedas",
     "Делистинг — монета уходит с биржи. Остаток нужно вывести или продать. Падение часто за недели до.",
     "Delisting removes pair from exchange. Exit early."),
    (12, MOD_MKT, "Beginner", 16, "momentum", "BINANCE:ARBUSDT",
     "Листинг", "New listing", "Listagem",
     "Листинг: волатильность и памп в первые часы. Торгуйте малым размером, стоп обязателен.",
     "Listing: extreme volatility first hours. Small size, mandatory stop."),
    (13, MOD_CHART, "Intermediate", 22, "range_trading", "BINANCE:BTCUSDT",
     "Каналы", "Channels", "Canais",
     "Канал — параллельные поддержка и сопротивление. Покупка у низа, продажа у верха в range.",
     "Channel = parallel support/resistance. Buy low, sell high in range."),
    (14, MOD_CHART, "Beginner", 20, "uptrend", "BINANCE:BTCUSDT",
     "Восходящий тренд", "Uptrend", "Tendência de alta",
     "Восходящий тренд: Higher High + Higher Low. Торгуйте откаты к поддержке в сторону тренда.",
     "Uptrend: HH + HL. Trade pullbacks to support."),
    (15, MOD_CHART, "Beginner", 20, "downtrend", "BINANCE:BTCUSDT",
     "Нисходящий тренд", "Downtrend", "Tendência de baixa",
     "Нисходящий тренд: Lower High + Lower Low. Шорты от сопротивления или ожидание разворота.",
     "Downtrend: LH + LL. Shorts from resistance."),
    (16, MOD_STR, "Intermediate", 24, "momentum", "BINANCE:BTCUSDT",
     "Базовые индикаторы", "Basic indicators", "Indicadores básicos",
     "MA — направление. RSI — перекупленность не на тренде. Объём подтверждает пробой. Не перегружайте график.",
     "MA for trend. RSI overbought in trend is normal. Volume confirms breaks."),
    (17, MOD_MKT, "Advanced", 22, "session_timeline", "BINANCE:BTCUSDT",
     "Торговля на новостях", "News trading", "Trading em notícias",
     "Новости = спайки и проскальзывание. Не входите за минуту до CPI/FOMC. Ждите структуру после выстрела.",
     "News = spikes and slippage. Don't enter 1 min before CPI/FOMC."),
    (18, MOD_RISK, "Beginner", 22, "risk_reward", "BINANCE:BTCUSDT",
     "Оптимальная работа с депозитом", "Deposit management", "Gestão do depósito",
     "Риск 0.5–1% на сделку. Макс 3–5 позиций. Не маржа на весь депозит. Рост счёта — медленно и стабильно.",
     "Risk 0.5–1% per trade. Max 3–5 positions. Don't use full margin."),
    (19, MOD_PAT, "Intermediate", 20, "breakout", "BINANCE:LINKUSDT",
     "Симметричный треугольник", "Symmetrical triangle", "Triângulo simétrico",
     "Симметричный треугольник: сжатие. Ждите пробой с объёмом, не угадывайте сторону.",
     "Symmetrical triangle: compression. Wait for volume breakout."),
    (20, MOD_MKT, "Intermediate", 18, "momentum", "BINANCE:DOGEUSDT",
     "FUN токены и их особенности", "FUN / meme tokens", "Tokens FUN / meme",
     "FUN/meme: низкая ликвидность, резкие пампы/дампы. Малый размер, быстрый стоп, не держите overnight без плана.",
     "Meme tokens: low liquidity, violent moves. Small size, tight stop."),
    (21, MOD_STR, "Intermediate", 22, "pullback", "BINANCE:ETHUSDT",
     "Как досиживать отработку анализа", "Hold until target", "Segurar até o alvo",
     "План до входа: стоп и тейк не двигаем из страха/жадности. Частичная фиксация на 1R — опционально.",
     "Plan before entry. Don't move stop from fear/greed. Partial at 1R optional."),
    (22, MOD_CHART, "Advanced", 22, "order_flow", "BINANCE:BTCUSDT",
     "Стрелы на тиковом графике", "Tick chart arrows", "Setas no gráfico de ticks",
     "Тиковый график показывает каждую сделку. Стрелы — агрессивные рыночные покупки/продажи в стакане.",
     "Tick chart shows every trade. Arrows = aggressive market orders."),
    (23, MOD_STR, "Beginner", 24, "risk_reward", "BINANCE:BTCUSDT",
     "Идея входа и точки выхода до открытия", "Plan entry and exit before open", "Plano antes de abrir",
     "До клика: сетап, вход, стоп, тейк 1/2, R:R минимум 1:2. Нет плана — нет сделки.",
     "Before click: setup, entry, stop, targets, min 1:2 R:R. No plan = no trade."),
    (24, MOD_MKT, "Intermediate", 22, "structure", "BINANCE:BTCUSDT",
     "Циклы рынка", "Market cycles", "Ciclos de mercado",
     "Циклы: накопление → рост → распределение → падение. BTC ведёт альты с лагом.",
     "Cycles: accumulation → markup → distribution → markdown. BTC leads alts."),
    (25, MOD_MKT, "Intermediate", 20, "correlation", "BINANCE:BTCUSDT",
     "Что такое альтсезон и когда его ждать", "Altseason explained", "O que é altseason",
     "Альтсезон: BTC.D падает, альты растут быстрее BTC. Ждите устойчивого боковика BTC + рост доминации объёма альтов.",
     "Altseason: BTC dominance falls, alts outperform. Wait for BTC range + alt volume."),
    (26, MOD_MKT, "Intermediate", 24, "session_timeline", "BINANCE:BTCUSDT",
     "График BTC для движения внутри дня", "Intraday BTC context", "BTC intraday",
     "Внутри дня: Азия тихая, Лондон пробои, NY волатильность. Смотрите BTC 15m/1h перед альтой.",
     "Intraday: Asia quiet, London breaks, NY volatile. Check BTC 15m/1h before alts."),
    (27, MOD_STR, "Advanced", 24, "reversal", "BINANCE:BTCUSDT",
     "Торговые ситуации при проливе BTC", "Trading BTC dumps", "Operar quedas de BTC",
     "Пролив BTC: альты падают сильнее. Шорт лидера или ждите стабилизации BTC для лонга альты.",
     "BTC dump: alts fall harder. Short leader or wait for BTC stabilize."),
    (28, MOD_RISK, "Intermediate", 22, "price_chart", "BINANCE:BTCUSDT",
     "Как вернуться после большого минуса", "Recovery after big loss", "Voltar após grande perda",
     "Стоп торговли на 24–72ч. Уменьшите размер в 2–3 раза. Разберите сделки в журнале. Без реванша.",
     "Pause 24–72h. Cut size 2–3x. Journal review. No revenge."),
    (29, MOD_PRAC, "Advanced", 32, "structure", "BINANCE:ETHUSDT",
     "Марафон. Блок 1", "Marathon Block 1", "Maratona Bloco 1",
     "Блок 1: разметка тренда + уровни + план сделки на ETH 15m. Полный цикл без входа, потом с paper.",
     "Block 1: trend + levels + trade plan on ETH 15m. Full cycle dry-run then paper."),
    (30, MOD_PRAC, "Advanced", 32, "risk_reward", "BINANCE:ETHUSDT",
     "Марафон. Блок 2", "Marathon Block 2", "Maratona Bloco 2",
     "Блок 2: вход по плану, сопровождение, фиксация, журнал. Оценка процесса, не только PnL.",
     "Block 2: entry, management, exit, journal. Grade process not only PnL."),
    (31, MOD_STR, "Intermediate", 20, "risk_reward", "BINANCE:BTCUSDT",
     "Усреднение", "Averaging down", "Média de preço",
     "Усреднение без плана = слив. Допустимо только с лимитом потерь и если тезис не сломан.",
     "Averaging without plan blows accounts. Only with max loss cap and intact thesis."),
    (32, MOD_PAT, "Intermediate", 22, "reversal", "BINANCE:BTCUSDT",
     "Смена тренда восходящий → нисходящий", "Trend change up to down", "Mudança de tendência",
     "Смена тренда: пробой последнего HL, Lower High, retest снизу. Не шортите первый откат.",
     "Trend change: break last HL, LH, retest from below."),
    (33, MOD_RISK, "Intermediate", 24, "price_chart", "BINANCE:BTCUSDT",
     "Анализ своей торговли", "Analyze your trading", "Analisar seus trades",
     "Журнал: дата, пара, сетап, R, эмоция, скрин. Раз в неделю — winrate по сетапам, не по монетам.",
     "Journal: date, pair, setup, R, emotion, screenshot. Weekly review by setup."),
    (34, MOD_MKT, "Intermediate", 20, "session_timeline", "BINANCE:BTCUSDT",
     "Заседание ФРС", "FOMC meeting", "Reunião do FED",
     "ФРС двигает DXY и BTC. За 30 мин до — не в рынке. Торгуйте реакцию через 15–30 мин после.",
     "FOMC moves DXY and BTC. Flat 30 min before. Trade reaction 15–30 min after."),
    (35, MOD_INTRO, "Beginner", 18, "price_chart", "BINANCE:BTCUSDT",
     "Скам чаты", "Scam signal chats", "Chats de golpe",
     "Скам: гарантированная прибыль, депозит «трейдеру», pump groups. Настоящее обучение — сетапы, не сигналы.",
     "Scam: guaranteed profit, send funds to guru, pump groups."),
    (36, MOD_INTRO, "Beginner", 16, "price_chart", "BINANCE:BTCUSDT",
     "Перевод активов между биржами", "Transfer between exchanges", "Transferir entre exchanges",
     "Проверяйте сеть (ERC20/TRC20/BEP20). Тестовая сумма. Адрес из биржи, не из чата.",
     "Check network. Test amount. Address from exchange UI only."),
    (37, MOD_INTRO, "Intermediate", 20, "order_flow", "BINANCE:BTCUSDT",
     "Соединение по API", "API connection", "Conexão API",
     "API: read-only для ботов и журнала. Никогда не давайте withdraw. IP whitelist.",
     "API: read-only for bots. Never withdraw permission. IP whitelist."),
    (38, MOD_RISK, "Beginner", 18, "session_timeline", "BINANCE:BTCUSDT",
     "Торговля на работе или дома", "Trading at work or home", "Trading no trabalho ou casa",
     "Нужны тишина, второй монитор, расписание сессий. Не торгуйте в стрессе и отвлечённо.",
     "Need focus, schedule, second monitor. Don't trade distracted."),
    (39, MOD_INTRO, "Beginner", 28, "risk_reward", "BINANCE:BTCUSDT",
     "Фьючерсы. Часть 1", "Futures Part 1", "Futuros Parte 1",
     "Плечо, маржа, ликвидация, funding rate. Изолированная маржа для новичка. Плечо 3–5x максимум на старте.",
     "Leverage, margin, liquidation, funding. Isolated margin for beginners. Max 3–5x."),
    (40, MOD_RISK, "Intermediate", 22, "price_chart", "BINANCE:BTCUSDT",
     "Основные ошибки. Часть 2", "Mistakes Part 2", "Erros Parte 2",
     "Реванш, перенос стопа, overtrading, торговля в боковике без edge.",
     "Revenge, moving stops, overtrading, chopping in range."),
    (41, MOD_INTRO, "Beginner", 16, "price_chart", "BINANCE:BTCUSDT",
     "Приложения которые помогут", "Useful apps", "Apps úteis",
     "TradingView, CoinGlass (funding/OI), терминал биржи, Trade Master для обучения и журнала.",
     "TradingView, CoinGlass, exchange terminal, Trade Master for learning."),
    (42, MOD_STR, "Intermediate", 20, "session_timeline", "BINANCE:BTCUSDT",
     "Утро трейдера", "Trader morning routine", "Rotina matinal do trader",
     "Утро: календарь новостей, уровни BTC/ETH, список пар, лимит сделок на день.",
     "Morning: news calendar, BTC/ETH levels, watchlist, daily trade limit."),
    (43, MOD_PAT, "Intermediate", 22, "pullback", "BINANCE:ETHUSDT",
     "Коррекция по Фибоначчи", "Fibonacci retracement", "Correção de Fibonacci",
     "Уровни 0.382, 0.5, 0.618 — зоны отката в тренде. Вход по тренду у fib + подтверждение.",
     "0.382, 0.5, 0.618 retracement in trend. Enter with trend at fib."),
    (44, MOD_MKT, "Intermediate", 20, "momentum", "BINANCE:BTCUSDT",
     "Airdrop и Pre market", "Airdrop and pre-market", "Airdrop e pré-market",
     "Airdrop фарм — отдельная дисциплина. Pre-market на новых парах — экстремальный риск.",
     "Airdrop farming is separate. Pre-market on new pairs = extreme risk."),
    (45, MOD_CHART, "Intermediate", 24, "candlestick", "BINANCE:ETHUSDT",
     "Свечи. Часть 2", "Candles Part 2", "Velas Parte 2",
     "Пин-бар, поглощение, доджи у уровня. Тень = отказ цены. Тело = контроль стороны.",
     "Pin bar, engulfing, doji at levels. Wick = rejection."),
    (46, MOD_PAT, "Intermediate", 22, "reversal", "BINANCE:BTCUSDT",
     "Голова. Часть 1", "Head & shoulders Part 1", "Ombro-cabeça-ombro Parte 1",
     "Голова и плечи: три вершины, средняя выше. Линия шеи — ключевой уровень.",
     "Head & shoulders: three peaks, middle highest. Neckline is key."),
    (47, MOD_PAT, "Advanced", 24, "reversal", "BINANCE:BTCUSDT",
     "Голова. Часть 2", "Head & shoulders Part 2", "Ombro-cabeça-ombro Parte 2",
     "Пробой шеи + retest = вход в шорт. Измерение: расстояние голова–шея вниз от пробоя.",
     "Neckline break + retest = short. Target = head-to-neck distance."),
]

for t in _TITLES:
    lid, mod, diff, mins, chart, sym, ru_t, en_t, pt_t, ru_th, en_th = t
    pt_th = en_th  # PT mirrors EN theory briefly; titles are PT
    LESSONS_DATA.append(lesson_template(
        lid, mod, diff, mins, chart, sym,
        _m(
            f"No Brasil aplique em altcoins com liquidez em Binance.",
            f"En México aplique en pares USDT líquidos.",
            f"В РФ применяйте на ликвидных USDT-парах Binance.",
        ),
        ru_t, en_t, pt_t,
        ru_th + "\n\nTrade Master: теория + TradingView + журнал — не как Finera (finanças) или sinais Telegram.",
        en_th + "\n\nTrade Master: theory + TradingView + journal — not signal groups.",
        pt_th + "\n\nTrade Master: teoria + TradingView + diário — diferente de apps de finanças pessoais.",
        "Применяйте на текущем графике. Отметьте сетап. Запишите вход/стоп/цель до клика.",
        "Apply on live chart. Mark setup. Log entry/stop/target before click.",
        "Aplique no gráfico. Marque setup. Anote entrada/stop/alvo.",
        f"На TradingView откройте {sym.split(':')[1]} и найдите пример этой темы за последние 7 дней.",
        f"On TradingView open {sym.split(':')[1]} and find this pattern in last 7 days.",
        f"No TradingView abra {sym.split(':')[1]} e ache o padrão nos últimos 7 dias.",
        *STEPS_CHART,
        f"Пример на {sym}: примените правило урока с R:R минимум 1:2. Без клика — только план.",
        f"Example on {sym}: apply lesson rule with min 1:2 R:R. Plan only, no click.",
        [ru_th.split(".")[0], "TradingView разбор", "Журнал обязателен", "Риск 0.5–1%", "Не сигналы — сетапы"],
        [en_th.split(".")[0], "TradingView breakdown", "Journal required", "Risk 0.5–1%", "Setups not signals"],
        [pt_th.split(".")[0], "TradingView", "Diário obrigatório", "Risco 0,5–1%", "Setups não sinais"],
        "Конкуренты не дают связку урок → TradingView → журнал. Вы проходите полный цикл.",
        "Competitors don't link lesson → TradingView → journal. You get the full loop.",
        "Concorrentes não ligam lição → TradingView → diário. Você tem o ciclo completo.",
    ))
